<?php 
		
		if($this->objTp == 1){
		    if(count($this->objContaspagar)>0){
		    ?>
    	        <div class="widget">
    	 			<table style="width: 100%" class="tableStatic">
    	            	<thead>
    	                	<tr>
    	                        <td >Id</td>
    	                        <td >Fornecedor</td>
    	                        <td >Emissão</td>
    	                        <td >Prox Vencimento</td>
    	                        <td >Valor</td>
    	                        <td >Valor parc</td>
    	                        <td >Situação</td>
    	                        <td width="10%">Opções</td>
    	                    </tr>
    	                </thead>
    	                <tbody>
    					<?php							
    					foreach ($this->objContaspagar as $listpagar):
    					?>
    					<tr  >
    						<td style="text-align: center;" >
    							P<?=substr("000000".$listpagar->idfin,-6)?>
    						</td>
    						<td align="left">
    							<?php 
    							if(($listpagar->id_fornecedor!=0) and ($listpagar->id_fornecedor!=NULL)): 
    								echo $listpagar->EMPRESA;
    							elseif(($listpagar->id_usuarios!=NULL) and ($listpagar->id_usuarios!="")): 
    								echo $listpagar->nome;
    							else: 
    								echo $listpagar->out_fornecedor;
    							endif;
    							
    							?>
    						</td>
    						<td style="text-align: center;">
    							<?=$listpagar->dtcad?>
    						</td>
    						<td style="text-align: center;">
    							<?=$listpagar->dtvencimento?>
    						</td>
    						<td style="text-align: right;">
    							<?=number_format($listpagar->valor,2,",",".")?>
    						</td>
    						<td style="text-align: right;">
    							<?=number_format($listpagar->valor_apagar,2,",",".")?>
    						</td>
    						<td style="text-align: center;">
    							<?php 						
    	
    							if($listpagar->conciliado != 0 and $listpagar->conciliado != ""): 
    								echo '<font color="#2a9cec">Conciliado</font>';
    			                elseif($listpagar->quitado == 1): 
    			                	echo '<font color="#009900">Pago</font>';
    			                elseif(($listpagar->quitado == 0) and (strtotime($listpagar->vencimento) < strtotime(date("Y-m-d"))) and (!empty($listpagar->dtvencimento))):
    			                	echo '<font color="#F00">Em atraso</font>';
    			                else: echo 'Em Aberto'; endif;
    			                
    							?>
    						</td>
    						<td  style="text-align: center;" >
    			                <a href="<?=$this->baseUrl(); ?>/admin/administracao/financeiroztlpagcad/pay/<?=md5($listpagar->idfin)?>" ><img src="<?=$this->baseUrl()?>/public/sistema/imagens/icons/middlenav/magnify.png" width="16" border="0" title="Visualizar"></a>
    			            </td>  
    					</tr>
    					<?php  endforeach; ?>
                    </tbody>
                </table>            
            </div>
           
    		<?php 
		    }else{
    		?>
    		<div class="widget first" style="padding: 10px; text-align: center; border-top: 1px solid #d5d5d5;">
     			Nenhuma conta encontrada!
    		</div>	
    		<?php 
    		}    		
		}else{
		    if(!empty($this->objContasreceber)){	
			?>
			<div class="widget">
	 			<table style="width: 100%" class="tableStatic">
	            	<thead>
	                	<tr>
	                        <td >Id</td>
	                        <td >Fatura</td>
	                        <td >Cliente/Funcionário</td>
	                        <td >Emissão</td>
	                        <td >Prox Vencimento</td>
	                        <td >Valor</td>
	                        <td >Valor parc</td>
	                        <td >Situação</td>
	                        <td width="10%">Opções</td>
	                    </tr>
	                </thead>
	                <tbody>
					<?php							
					foreach ($this->objContasreceber as $listreceber):
					?>
					<tr  >
						<td style="text-align: center;" >
							R<?=substr("000000".$listreceber->idfin,-6)?>
						</td>
						<td style="text-align: center;" >
							<?php echo $listreceber->fat?>
						</td>
						<td align="left">
							<?php 
    							if(($listreceber->id_fornecedor!=0) and ($listreceber->id_fornecedor!=NULL)): 
    								echo $listreceber->EMPRESA;
    							elseif(($listreceber->id_usuarios!=NULL) and ($listreceber->id_usuarios!="")): 
    								echo $listreceber->nome;
    							else: 
    								echo $listreceber->out_fornecedor;
    							endif;
    							
    						?>
						</td>
						<td style="text-align: center;">
							<?=$listreceber->dtcad?>
						</td>
						<td style="text-align: center;">
							<?=$listreceber->dtvencimento?>
						</td>
						<td style="text-align: center;">
							<?=number_format($listreceber->valor,2,",",".")?>
						</td>
						<td style="text-align: right;">
							<?=number_format($listreceber->valor_apagar,2,",",".")?>
						</td>
						<td style="text-align: center;">
							<?php 					
							
							if($listreceber->conciliado != 0 and $listreceber->conciliado != ""):
								echo '<font color="#2a9cec">Conciliado</font>';
			                elseif($listreceber->quitado == 1): 
			                	echo '<font color="#009900">Pago</font>';
			                elseif(($listreceber->quitado == 0) and (strtotime($listreceber->vencimento) < strtotime(date("Y-m-d"))) and (!empty($listreceber->dtvencimento))):
			                	echo '<font color="#F00">Em atraso</font>';
			                else: echo 'Em Aberto'; endif;                
							?>
						</td>
						<td  style="text-align: center;" >
			                <a href="<?=$this->baseUrl(); ?>/admin/administracao/financeiroztlreccad/rec/<?=md5($listreceber->idfin)?>" ><img src="<?=$this->baseUrl()?>/public/sistema/imagens/icons/middlenav/magnify.png" width="16" border="0" title="Visualizar"></a>
			            </td>  
					</tr>
					<?php								
					endforeach;						
				?>
					</tbody>
				</table>
			</div>
	       
			<?php 
		    }else{
				?>
				<div class="widget first" style="border: 1px solid #d5d5d5; padding: 15px" >
		 			Nenhuma conta encontrada!
				</div>	
				<?php 
			}
		}
	?>