
<?php
if($this->objTipo!=3){
	?>
	<div style="text-align: left;">
		<input type="radio" name="tipoexibe" checked="checked" onclick="buscaContasconcilia(<?=$this->objTipo?>,<?=$this->objIdc?>,<?=$this->objConta?>,0);"> Contas &nbsp; 
		<input type="radio" name="tipoexibe" onclick="buscaContasconcilia(3,<?=$this->objIdc?>,<?=$this->objConta?>,<?=$this->objTipo?>);"> Transferências
	</div>
	<?php
	if(!empty($this->objContaspagar)){
		foreach ($this->objConc as $concilia);
	
		if($concilia->valor < 0) $valorconc = $concilia->valor*(-1);
		else $valorconc = $concilia->valor;
	?>
	
	<form name="concilia" id="concilia"  method="post" class="mainForm">
		<input type="hidden" name="idc" value="<?=$this->objIdc?>" >
		<input type="hidden" name="tipo" value="<?=$this->objTipo?>" >
		<input type="hidden" name="conta" value="<?=$this->objConta?>" >
		<input type="hidden" name="valorconta" id="valorconta" value="<?=$valorconc?>" >
		
		<div class="fix"></div>
		<div class="widget" style="overflow: auto; width: 605px; height: 350px;">
			<table class="tableStatic" style="width: 100%">
				<thead>	
					<tr>
						<td style="text-align: center;"><?=$this->translate->_("ID")?></td>
						<td>Emissão</td>
						<td>Vencimento</td>
						<td>Valor</td>
						<td>&nbsp;</td>
					</tr>
				</thead>
				<tbody>
		
				<?php 	
				$totalsel = 0;
				foreach ($this->objContaspagar as $listpagar){
					?>
					<tr style="font: 11px Arial, Helvetica, sans-serif;">
						<td align="center">
							<?php if($this->objTipo==1):?>
							P<?=substr("000000".$listpagar->id_financeiropag,-6)?>/<?=$listpagar->parc?>
							<?php else: ?>
							R<?=substr("000000".$listpagar->id_financeirorec,-6)?>/<?=$listpagar->parc?>
							<?php endif;?>
						</td>
						<td class="td_orc_min" align="center">
							<?=$listpagar->dtcad?>
						</td>
						<td class="td_orc_min" align="center">
							<?=$listpagar->dtvenc?>
						</td>
						<td class="td_orc_min" align="right">
							<?=number_format(($listpagar->valor_pago),2,",",".")?>
							<input type="hidden" name="valor_<?=$listpagar->idfin?>" id="valor_<?=$listpagar->idfin?>" value="<?php echo $listpagar->valor_pago?>">
						</td>
						<td class="td_orc_min" align="center">
							<input type="checkbox" value="1" name="<?=$listpagar->idfin?>" id="<?=$listpagar->idfin?>" <?php if($this->objIdc==$listpagar->st_conc) echo 'checked="checked"';?> onchange="somaContasconcilia(this.id);">
							<?php 
							if($this->objIdc==$listpagar->st_conc) $totalsel += $listpagar->valor_pago;
							?>
						</td>
					</tr>
					<?php								
					}	
				?>
				</tbody>
			</table>
			
		</div>	
		<div class="fix"></div>
			
		<div class="widgets"> 
			<div style="text-align: left; margin-top: 10px; width: 50%" class="left" id="divsalvar">
				<input type="button" id="btnsalvar" name="btnsalvar" value="Salvar" onclick="conciliaContas();" class="basicBtn" style="opacity: 0.3">
			</div>
			<div style="text-align: right; margin-top: 10px; width: 35%" class="right">
				Total selecionado: <span id="totalsel"><?=number_format(($totalsel),2,",",".")?></span>
				<input type="hidden" name="totalselecionando" id="totalselecionando" value="<?php echo $totalsel?>">
			</div>
		</div>
		
		<div class="fix"></div>
		
	</form>
	<?php 
	}else{
		echo "Nenhuma conta para concilhar!";
	}
	
}else{
?>
	
	<div style="text-align: left;">
		<input type="radio" name="tipoexibe" onclick="buscaContasconcilia(<?=$this->objTpant?>,<?=$this->objIdc?>,<?=$this->objConta?>,3,'0');"> Contas &nbsp; 
		<input type="radio" name="tipoexibe" checked="checked" onclick="buscaContasconcilia(3,<?=$this->objIdc?>,<?=$this->objConta?>,<?=$this->objTpant?>,'0');"> Transferências
	</div>
	
	<div style="text-align: left;">
	Selecione um banco:<br />
	<div class="styled-select" style="width: 170px">
	<select name="bancobusca" onchange="buscaContasconcilia(3,<?=$this->objIdc?>,<?=$this->objConta?>,<?=$this->objTpant?>,this.value);" style="width: 192px">
		<option value="0"><?=$this->translate->_("Selecione")?></option>
		<?php 
		foreach ($this->objContasbanc as $listconta):
			if($listconta->id!=$this->objConta): 
			?>
			<option value="<?=$listconta->id?>" <?php if($lispagamento->id_financeirocontas==$listconta->id) echo 'selected="selected"';?>  ><?=$listconta->nome?></option>
			<?php
			endif;
		endforeach;?>
	</select>
	</div>
	</div>
	
	<?php 
	
	if(!empty($this->objContaspagar)){
	?>
	
	<form action="<?php echo $this->baseUrl(); ?>/admin/administracao/regconciliaztl" method="post" name="concilia" id="concilia" class="mainForm">
	<input type="hidden" name="idc" value="<?=$this->objIdc?>" >
	<input type="hidden" name="tipo" value="<?=$this->objTipo?>" >
	<input type="hidden" name="conta" value="<?=$this->objConta?>" >
	<input type="hidden" name="buscconta" value="<?=$this->objBancobusca?>" >
	
	<div class="widget" style="overflow: auto; width: 605px; height: 350px;">
	<table class="tableStatic" style="width: 100%">
		<thead>	
			<tr>
				<td style="text-align: center;">ID</td>
				<td>Data</td>
				<td>Valor</td>
				<td>&nbsp;</td>
			</tr>
		</thead>
		<tbody>
		<?php 
		foreach ($this->objContaspagar as $listpagar){
			?>
			<tr >
				<td align="center">
					<?=$listpagar->idconc?>
				</td>
				<td align="center">
					<?=$listpagar->dtcad?>
				</td>
				<td align="right">
					<?=number_format(($listpagar->valor),3,",",".")?> &nbsp; 
				</td>
				<td align="center">
					<input type="radio" name="radiovalida" value="<?=$listpagar->idconc?>" >
				</td>
			</tr>
			<?php
		}
	?>
	</tbody>
	</table>
	
	</div>	
		<div class="fix"></div>
		
		<div style="text-align: left; margin-top: 10px">
			<input type="button" name="salvar" value="Salvar" onclick="conciliaContas()" class="basicBtn">
		</div>
	
	</form>
	
	<?php 
	}
}
?>