<form method="post" name="formcredito" class="mainForm">
	<div class="widgets">
	<?php
		if(count($this->objCreditos)>0):
		?>       
        <div class="widget">
 			<table style="width: 100%" class="tableStatic">
            	<thead>
                	<tr>
                        <td >Id</td>
                        <td >Emissão</td>
                        <td >Valor</td>
                        <td width="15%">Opções</td>
                    </tr>
                </thead>
                <tbody>
				<?php							
				foreach ($this->objCreditos as $listcreditos):
				?>
				<tr  >
					<td style="text-align: center;" >
						C<?php echo substr("000000".$listcreditos->idcredito,-6)?>
					</td>
					<td style="text-align: center;">
						<?=$listcreditos->dtcad?>
					</td>
					<td style="text-align: right;">
						<?=number_format($listcreditos->valorcredito,2,",",".")?>
					</td>
					<td  style="text-align: center;" >
		                <input type="checkbox" name="credito_<?php echo $listcreditos->idcredito?>" value="<? echo "C".substr("000000".$listcreditos->idcredito,-6)."|".$listcreditos->idcredito."|".number_format($listcreditos->valorcredito,2,",",".")."|".$listcreditos->valorcredito."|".$listcreditos->id_clientes?>">
		            </td>  
				</tr>
				<?php  endforeach; ?>
                </tbody>
            </table>            
        </div>
       
       <div style="text-align: left; padding-top: 10px">
       <input type="button" class="greenBtn" value="Adicionar crédito" onclick="adicionarCreditos()">
       </div>
       
		<?php 
	else :
	?>
	<div class="widget first" style="padding: 10px; text-align: center; border-top: 1px solid #d5d5d5;">
 		Nenhum credito encontrado!
	</div>	
	<?php 
	endif;
	?>
</div>

</form>