<table width="100%" cellspacing="0" cellpadding="0" >
<tr>
	<td align="left">	
		<table width="100%" style="margin-bottom: 5px" cellspacing="0" cellpadding="0" >
			<tr>
				<td align="left">
					<a href="<?php echo $this->baseUrl(); ?>/admin/painel">HOME</a>&nbsp; 
					<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
					<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/mailing">EMAIL MARKETING</a>&nbsp;
					<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
					<b><a href="<?php echo $this->baseUrl(); ?>/admin/administracao/mailingnovo">NOVO EMAIL</a></b>  
				</td>				
			</tr>
		</table>
	</td>
</tr>
<tr>
	<td>
		<table width="100%" class="borda_titulo">
			<tr>
		    	<td width="left">NOVO MAILING</td>
		    </tr>
		</table>
	</td>
</tr>

</table>