<!-- Content -->
	<div class="content">   

<!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a> </li>
                	<li class="lastB">Financeiro</li>         
                </ul>
            </div>
        </div>       

        
        <div class="title"><h5>Financeiro</h5></div>

		<div style="float: right;">
			<a href="<?=$this->baseUrl(); ?>/admin/administracao/financeiroztlpag"><?=$this->translate->_("Pagar")?></a> |
    		<a href="<?=$this->baseUrl(); ?>/admin/administracao/financeiroztlrec"><?=$this->translate->_("Receber")?></a> | 
    		<a href="<?=$this->baseUrl(); ?>/admin/administracao/financeiroztlbancos"><?=$this->translate->_("Administração")?></a> | 					    		  
    		<a href="<?=$this->baseUrl(); ?>/admin/administracao/financeiroztlconc"><?=$this->translate->_("Conciliação")?></a>
		</div>		

		<div class="widgets" >
			<div class="widget" style="border-top: 1px solid #d5d5d5;">
				<div class="left" style="width: 50%">
					<div style="margin: 10px 30px 10px 30px; width: 100%">
						<img src="<?php echo $this->baseUrl(); ?>/public/sistema/imagens/rightArrow.png" width="5" height="7" />&nbsp;<b>CONTAS À PAGAR</b><br>
						&nbsp; &nbsp; 
						<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeiroztlpag" >
						Todas as contas
						</a><br>
						&nbsp; &nbsp; 
						<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeiroztlpag/fil/avencer" >
						Contas a vencer: <b><?=count($this->objContasvencpag)?></b>
						</a><br>
						&nbsp; &nbsp; 
						<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeiroztlpag/fil/avencersem" >
						Contas a vencer nessa semana: <b><?=count($this->objContasvencsempag)?></b>
						</a><br>
						&nbsp; &nbsp; 
						<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeiroztlpag/fil/avencerhoje" >
						Contas a vencer hoje: <b><?=count($this->objContasvenchojepag)?></b>
						</a><br>
						&nbsp; &nbsp; 
						<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeiroztlpag/fil/vencidas" >
						Contas vencidas: <b><?=count($this->objContasvencidaspag)?></b>
						</a><br>
						&nbsp; &nbsp; 
						<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeiroztlcreditos" >Créditos</a>
					</div>				
					<div style="margin: 10px 30px 10px 30px; width: 100%">
						<img src="<?php echo $this->baseUrl(); ?>/public/sistema/imagens/rightArrow.png" width="5" height="7" />&nbsp;<b>CONTAS À RECEBER</b><br>
						&nbsp; &nbsp; 
						<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeiroztlrec" >
						Todas as contas
						</a><br>
						&nbsp; &nbsp; 
						<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeiroztlrec/fil/avencer" >
						Contas a vencer: <b><?=count($this->objContasvencrec)?></b>
						</a><br>
						&nbsp; &nbsp; 
						<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeiroztlrec/fil/avencersem" >
						Contas a vencer nessa semana: <b><?=count($this->objContasvencsemrec)?></b>
						</a><br>
						&nbsp; &nbsp; 
						<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeiroztlrec/fil/avencerhoje" >
						Contas a vencer hoje: <b><?=count($this->objContasvenchojerec)?></b>
						</a><br>
						&nbsp; &nbsp; 
						<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeiroztlrec/fil/vencidas" >
						Contas vencidas: <b><?=count($this->objContasvencidasrec)?></b>
						</a>
					</div>
					<div style="margin: 10px 30px 30px 30px; width: 100%">
						<img src="<?php echo $this->baseUrl(); ?>/public/sistema/imagens/rightArrow.png" width="5" height="7" />&nbsp;<b>RELATÓRIOS</b><br>
						&nbsp; &nbsp; 
						<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeiroztlrelcontaspg" >
						Contas a pagar
						</a><br>
						&nbsp; &nbsp; 
						<a href="<?php echo $this->baseUrl(); ?>/admin/relatorios/financeirorelreceber" >
						Contas a receber
						</a><br>
						&nbsp; &nbsp;
						<a href="<?php echo $this->baseUrl(); ?>/admin/relatorios/financeirogerencial">
						Financeiro Gerencial
						</a><br />
						&nbsp; &nbsp;
						<a href="<?php echo $this->baseUrl(); ?>/admin/relatorios/financeirocomissoes">
						Comissões sobre venda
						</a><br />
						&nbsp; &nbsp;
						<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeiroztlduplicatas">
						Duplicatas descontadas
						</a><br />
						<!-- &nbsp; &nbsp; 
						<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/painelatividades/tp/1/ids/<?php echo md5($usuario->ID);?>" >
						Contas a receber
						</a><br>
						&nbsp; &nbsp; 
						<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/painelatividades/tp/1/ids/<?php echo md5($usuario->ID);?>" >
						Demostração do Resultado de Exercício
						</a><br />
						&nbsp; &nbsp; 
						<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/painelatividades/tp/1/ids/<?php echo md5($usuario->ID);?>" >
						Emissão de boletos
						</a><br />
						&nbsp; &nbsp; 
						<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/painelatividades/tp/1/ids/<?php echo md5($usuario->ID);?>" >
						Extrato de contas
						</a>
						<br />
						&nbsp; &nbsp; 
						<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/painelatividades/tp/1/ids/<?php echo md5($usuario->ID);?>" >
						Plano de contas
						</a>
						<br />
						&nbsp; &nbsp; 
						<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/painelatividades/tp/1/ids/<?php echo md5($usuario->ID);?>" >
						Plano de contas
						</a>
						 -->
					</div>
					
				</div>
				<div class="right" style="width: 30%; border: 1px solid #d5d5d5; padding: 10px; margin: 20px">
					<?php if(count($this->objTotalpagvenc)>0) foreach ($this->objTotalpagvenc as $contasvencpag);?>
					Total à pagar<br />
					Em atraso: <span style="font-size: 14px; font-weight: bold;"><?php echo number_format($contasvencpag->valor,2,",",".")?></span> <br />
					<?php if(count($this->objTotalpag)>0) foreach ($this->objTotalpag as $contaspag);?>
					À vencer: <span style="font-size: 14px; font-weight: bold;"><?php echo number_format($contaspag->valor,2,",",".")?></span>
				</div>
				<div class="right" style="width: 30%; border: 1px solid #d5d5d5; padding: 10px; margin-right: 20px">
					<?php if(count($this->objTotalrecvenc)>0) foreach ($this->objTotalrecvenc as $contasvencrec);?>
					Total à receber<br />
					Em atraso: <span style="font-size: 14px; font-weight: bold;"><?php echo number_format($contasvencrec->valor,2,",",".")?></span> <br />
					<?php if(count($this->objTotalrec)>0) foreach ($this->objTotalrec as $contasrec);?>
					À vencer: <span style="font-size: 14px; font-weight: bold;"><?php echo number_format($contasrec->valor,2,",",".")?></span>
				</div>
				<div class="clear"></div>
			</div>
		</div>
	</div>