<?php
header("Content-type: application/msexcel");
header("Content-Disposition: attachment; filename=Conciliacao.xls");
?>
<table width="800" class="borda_titulo" style="margin-bottom: 6px" align="center">
    <tr>
        <td width="left">
            <?
            echo "FINANCEIRO"." - "."AUDITORIA BANCÁRIA";
            ?>

        </td>
    </tr>
</table>

<table width="800" cellpadding="0" cellspacing="0" align="center">
    <tr>
        <td>
            <table width="100%" style="border: 1px solid #000;">
                <tr>
                    <td class="tdpar" colspan="3">
                        PERÍODO: <?php echo $this->dtIni?> À <?php echo $this->dtFim?>
                    </td>
                </tr>
            </table>
        </td>
    </tr>

    <tr>
        <td>
            <table class="mytable" width="100%" cellspacing="0" cellpadding="0" style="margin-top: 5px">
                <tr>
                    <th class="th_canto_min"><?="ORD"?></th>
                    <th class="th_orc_min"><?="DATA"?></th>
                    <th class="th_orc_min"><?="CONTA"?></th>
                    <th class="th_orc_min"><?="VALOR"?></th>
                    <th class="th_orc_min"><?="MOEDA"?></th>
                    <th class="th_orc_min"><?="CONCILIACAO (EMISSÃO - VENC)"?></th>
                    <th class="th_orc_min" ><?="STATUS"?></th>
                    <th class="th_orc_min" ><?="SALDO"?></th>
                </tr>
                <?php
                foreach ($this->objConciliac as $listconc) {
                    ?>
                    <tr  >
                        <td  class="td_orc_min" align="center">
                            <font ><?=substr("000000".$listconc->idconc,-6)?></font>
                        </td>
                        <td class="td_orc_min" align="center">
                            <font ><?=$listconc->dtcad?></font>
                        </td>
                        <td class="td_orc_min" align="center">
                            <font ><?=$listconc->contaC?></font>
                        </td>
                        <td class="td_orc_min" align="right">
                            <font ><?=number_format($listconc->valorConc,2,",",".")?></font>
                        </td>
                        <td class="td_orc_min" align="center">
                            <font ><?=$listconc->moedaConta?></font>
                        </td>
                        <td class="td_orc_min" align="center" >
                            <?php
                                echo $listconc->contaConc;
                                echo $listconc->pagamentos;
                                echo $listconc->recebimentos;
                            ?>
                        </td>
                        <td class="td_orc_min" align="left"> &nbsp;  &nbsp;
                            <?php
                            if($listconc->valida != 0) echo " &nbsp; Validado";
                            if($listconc->sitConc != 1) echo " &nbsp; Excluido";
                            ?>
                        </td>
                        <td class="td_orc_min" style="text-align: right"> &nbsp;  &nbsp;
                            <?php
                                foreach ($this->objSaldoc as $key => $saldo) {
                                    if($saldo->id == $listconc->idC) {
                                        echo number_format($saldo->saldo,2,",",".");
                                        $this->objSaldoc[$key]->saldo = $saldo->saldo - $listconc->valorConc;
                                    }
                                }
                            ?>
                        </td>
                    </tr>
                    <?php
                }
                ?>
            </table>
        </td>
    </tr>
</table>
</body>
</html>