<div id="siscorpo">
	<div id="sisnavegacao">
		<a href="<?=$this->baseUrl()?>/admin/painel"><?=$this->translate->_("HOME")?></a>&nbsp; 
		<img src="<?=$this->baseUrl()?>/images/seta.png" width="5" height="7" />&nbsp;
		<a href="<?=$this->baseUrl()?>/admin/administracao/financeiroztlpag"><?=$this->translate->_("FINANCEIRO")?></a>&nbsp;
		<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
		<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeiroztlbancos"><?=$this->translate->_("ADM");?></a>&nbsp;
		<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
		<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeiroztlbancos"><?=$this->translate->_("BANCOS");?></a>&nbsp;
		<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
		<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeiroztlbancos"><b><?=$this->translate->_("CADASTRO BANCOS");?></b></a>&nbsp;			    		
	</div>
	<div id="sistitulo"><?=$this->translate->_("CADASTRO CONTAS BANCÁRIAS")?></div>
	<div id="sisconteudo">  
		<form action="<?php echo $this->baseUrl(); ?>/admin/administracao/cadbancosztl" method="post" name="bancos" id="bancos">
			<input type="hidden" name="idbanco" >
			<table width="100%" border="0" style="margin-bottom: 8px; display: block; border: 1px solid #000; padding: 4px; " id="tabela">
			    <tr>
			    	<td align="left" >
			    		<?=$this->translate->_("Nome da conta")?>:<br>							 
			    		<input type="text" style="text-transform: uppercase;" size="20" name="nome" id="nome" >
			    	</td>
			    	<td align="left" >
			    		<?=$this->translate->_("Banco")?>:<br>							 
			    		<input type="text" style="text-transform: uppercase;" size="15" name="banco" id="banco" >
			    	</td>
			    	<td align="left" >
			    		<?=$this->translate->_("Agência")?>:<br>							 
			    		<input type="text" style="text-transform: uppercase;" size="10" name="agencia" id="agencia" >
			    	</td>							    	
				</tr>
				<tr>
					<td align="left" >
			    		<?=$this->translate->_("Conta")?>:<br>							 
			    		<input type="text" style="text-transform: uppercase;" size="18" name="conta" id="conta" >
			    	</td>
			    	<td align="left" colspan="2"><br />
			    		<input type="submit" value="<?=$this->translate->_("Salvar")?>" >
			    	</td>
			    </tr>
			</table>  
		</form>
	</div>
</div>