	<script type="text/javascript" src="<?=$this->baseUrl()?>/public/sistema/js/financeiro.js"></script>
	<script type="text/javascript" src="<?=$this->baseUrl()?>/public/sistema/js/buscaajax/buscaGenerica.js"></script>

	<script>
		$(function(){   
		    $("#filtros").click(function(){
		    	$("#divfiltros").toggle("slow");
		    	$("#btnpesq").toggle("slow");		    	
		    });

			$("#resultado").hide();
			buscaFinanceiro();
					    
		    $(".btnpesq").click(function(){
		    	buscaFinanceiro();
			});

			function buscaFinanceiro(){
				$("#resultado").show();
			    
				var url = '/admin/administracao/buscaduplicatas'+
				'/dtini/'+$('input[name=dtini]').val().replace('/','-').replace('/','-')+
				'/dtfim/'+$('input[name=dtfim]').val().replace('/','-').replace('/','-')+
				'/bancorecebimentorec/'+$("select[name=bancorecebimentorec] option:selected").val();

		    	buscaGenerica(url,'resultado');
			}

			$("#exportar").click(function(){
				window.location='/admin/administracao/financeiroztlduplicatasexp'+
				'/dtini/'+$('input[name=dtini]').val().replace('/','-').replace('/','-')+
				'/dtfim/'+$('input[name=dtfim]').val().replace('/','-').replace('/','-')+
				'/bancorecebimentorec/'+$("select[name=bancorecebimentorec] option:selected").val();
			});
			
		});
		
	</script>
	
<!-- Content -->
	<div class="content">   

<!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a> </li>
                	<li ><a href="<?=$this->baseUrl(); ?>/admin/administracao/financeiroztl">Financeiro</a></li>
                	<li class="lastB">Duplicatas descontadas</li>           
                </ul>
            </div>
        </div>       

		<div class="title"><h5>Duplicatas descontadas</h5>
			<div style="float: right; padding: 10px">
				<a href="javascript:void(0)" id="exportar" ><img title="Exportar para MS Excel" src="<?=$this->baseUrl(); ?>/public/sistema/imagens/icons/middlenav/excelDocwhite.png" border="0" width="18" /> </a>
			</div>
		</div>

		<div class="widgets" >
        	<!-- Busca ------------------------------------------------------ -->
			<div class="widget" style="border: 1px solid #d5d5d5; padding: 10px" >  
				<form method="post" name="busca" id="busca" class="mainForm">
					<table style="width: 100%">
					    <tr>
							<td class="tdbusca" style="vertical-align: middle;">
								<div style="float: left; width: 30%"> 
									<input placeholder="Data inicio" type="text" style="width: 80px" name="dtini" id="dtini" class="data datepicker">
								</div>
								<div style="float: left;">
									<input placeholder="Data final" type="text" style="width: 80px"  name="dtfim" id="dtfim" class="data datepicker">
								</div>
							</td>
							<td  class="tdbusca">								
								<div class="styled-select" style="width: 200px">
									<select name="bancorecebimentorec" style="text-transform: uppercase; width: 222px">
										<option value="0">Banco origem</option>
										<?php 
										foreach ($this->objContasbanc as $listconta):
											?>
											<option value="<?=$listconta->id?>" ><?=$listconta->nome?></option>
											<?php														
										endforeach;?>
									</select>
								</div>
							</td>
							<td style="text-align: right; vertical-align: middle;" class="tdbusca">
								<input type="button" class="blueBtn btnpesq" value="Pesquisar">
							</td>
						</tr>								
					</table>
				</form>
			</div>
						
			<div id="resultado">
				<div style="border: 1px solid #d5d5d5; padding: 15px">
					<img src="<?php echo $this->baseUrl?>/public/sistema/imagens/loaders/loader6.gif"> <i>Aguarde...</i>
				</div>
			</div>			
		</div>
	</div>