<!-- Calendarios -->
<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/javascript/calendario/dhtmlgoodies_calendar.css?random=20051112" media="screen"></LINK>
<SCRIPT type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/javascript/calendario/dhtmlgoodies_calendar.js?random=20060118"></script>

<table width="100%" cellpadding="0" cellspacing="0" >
	<tr>
		<td align="left">				
		<table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom: 5px" >
			<tr>
				<td align="left">
					<a href="<?php echo $this->baseUrl(); ?>/admin/painel"><?=$this->translate->_("HOME")?></a>&nbsp; 
					<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
					<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeirochinareturn">					
					<?=$this->translate->_("FINANCEIRO")?>&nbsp; 
					</a>
					<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
					<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeirochinareturn"><b><?=$this->translate->_("RETORNO IMPOSTOS");?></b></a>
				</td>
				<td>
					<table width="100%"  cellpadding="0" cellspacing="0" >
					    <tr>
					    	<td align="right" >
					    		<b>
					    		<a href="<?=$this->baseUrl(); ?>/admin/administracao/financeirochinapag"><?=$this->translate->_("PAGAR")?></a> | 
					    		<a href="<?=$this->baseUrl(); ?>/admin/administracao/financeirochinarec"><?=$this->translate->_("RECEBER")?></a> |  
					    		<?php if($this->objAdm==1): ?>
					    		<a href="<?=$this->baseUrl(); ?>/admin/administracao/financeirochinabancos"><?=$this->translate->_("ADM")?></a> |
					    		<?php endif;?> 
					    		<a href="<?=$this->baseUrl(); ?>/admin/administracao/financeirochinaconc"><?=$this->translate->_("CONCILIAÇÃO")?></a>  
					    		</b>
					    	</td>
						</tr>
					</table>  
				</td>
			</tr>
		</table>
 		</td>
	</tr>
	<tr>
		<td>
			<table width="100%" class="borda_titulo" >
				<tr>
			    	<td width="left"><?=$this->translate->_("RETORNO DE IMPOSTOS")?></td>
			    </tr>
			</table>
		</td>
	</tr>
	<tr>
		<td>
			<table width="100%" style="margin: 5px 0px" cellpadding="0" cellspacing="0" >
			    <tr>
			    	<td align="right" >			    		
			    		<b><a href="<?=$this->baseUrl(); ?>/admin/administracao/financeirochinareturncad"><?=$this->translate->_("RETORNOS CADASTRADOS")?></a></b>  
			    	</td>
				</tr>
			</table><!--  
			 
			<script>
			function mostrarPesquisa(){
			    nTr = document.getElementById("tabela");
			    if(nTr.style.display == "none"){
			        nTr.style.display = "block"
			    }else{
			        nTr.style.display = "none";
			    }
			}
			
			function tipoPesquisa(valor){
			
				if(valor==1){
					document.getElementById("buscid").style.display = "block";
					document.getElementById("data").style.display = "none";
					document.getElementById("busccliente").style.display = "none";
					document.getElementById("dataini").value = "";
					document.getElementById("datafin").value = "";
					document.getElementById("buscacli").value = "";
				}else if(valor==2){
					document.getElementById("data").style.display = "block";
					document.getElementById("buscid").style.display = "none";
					document.getElementById("busccliente").style.display = "none";
					document.getElementById("buscaid").value = "";
					document.getElementById("buscacli").value = "";
				}else if(valor==3){
					document.getElementById("busccliente").style.display = "block";
					document.getElementById("buscid").style.display = "none";
					document.getElementById("data").style.display = "none";
					document.getElementById("buscaid").value = "";
				}
			    
			}
			</script>
		--></td>
	</tr>
	<!--<tr>
		<td>
			<form action="<?=$this->baseUrl()?>/kang/vendas" method="post" name="busca" id="busca">
			<table style="margin: 2px 0px 10px; display: block; border: 1px solid #000; padding: 7px; width: 77%" >
			    <tr>
			    	<td align="left" >
				    	<select name="tipo" onchange="tipoPesquisa(this.value);" style="border: 1px solid #999">
						<option value="2">Por Situação</option>
						<option value="1">Por ID</option>
						<option value="3">Por Cliente</option>
						</select>
						 &nbsp;  &nbsp;    
			    	</td>			    	
			    	<td align="left">
				    	<div style="display: none;" id="busccliente">
							<select name="buscacli" id="buscacli">
								<?php foreach ($this->objFornec as $listcli): ?>
									<option value="<?php echo $listcli->ID?>"><?php echo $listcli->EMPRESA ?></option>
								<?php endforeach; ?>
							</select>
							<input type="submit" value="Pesquisar" style="margin-top: 3px">
						</div>
						<div style="display: none;" id="buscid">
							<input type="text" size="10" name="buscaid" id="buscaid">
							<input type="submit" value="Pesquisar">
						</div>
						<div style="display: block" id="data">
							<select name="situacao" style="width: 120px">
								<option>Aberto</option>
								<option>Pendente</option>
			                    <option>Concluido</option>
							</select>
							<input type="submit" value="Pesquisar">
						</div>						
			    	</td>
				</tr>
			</table>  
			</form>
 		</td>
	</tr>
	--><tr>
		<td> 
		<table width="100%" cellpadding="0" cellspacing="0"> 
			
			<tr>
				<td>        
		           <?php 					
					if (count($this->objList) > 0) :
					?>
					<table align="left" class="mytable" width="100%" cellspacing="0" cellpadding="0" >
				        <tr>
				            <th  class="th_canto_orc" align="center" width="8%">
				                <?=$this->translate->_("ID")?>
				            </th>
				            <th  class="th_orc" align="center" width="19%" >
				                <?=$this->translate->_("DATA VENDA ")?>
				            </th>
				            <th  class="th_orc" align="center" width="30%">
				            	<?=$this->translate->_("CLIENTE ")?>
				            </th>
				            <th  class="th_orc" align="center" width="25%">
				            	<?=$this->translate->_("SITUAÇÃO")?> 
				            </th>
				            <th  class="th_orc" align="center" width="18%">
				                <?=$this->translate->_("OPÇÕES")?>
				            </th>
				       </tr>	
					
					<?php 
					$cor=0;
			    	foreach($this->objList as $lista):
			    	$cor++;
		            if(($cor%2)==0) $class = 'td_orc_par';
		            else $class = 'td_orc';
					?>
					
					<tr >
		                <td  class="<?=$class?>" align="center" >
		                   <?php echo "S".substr("000000".$lista->idped,-6,6)?>
		                </td>
		                <td  class="<?=$class?>" align="center" >
		                	<?php echo $lista->dtvenda?>
		                </td>
		                <td  class="<?=$class?>" align="left" >
		                	<?php echo utf8_encode($lista->EMPRESA)?>
		                </td>
		                <td  class="<?=$class?>" align="center" > 
		                   <?php 
		                   if($lista->statusfin=="0") echo $this->translate->_("ABERTO");
		                   elseif($lista->statusfin=="1") echo $this->translate->_("PENDENTE");
		                   elseif($lista->statusfin=="2") echo '<span style="color: rgb(0, 144, 0);">'.$this->translate->_("CONCLUIDO").'</span>';
		                   ?>                  
		                </td>
		                <td  class="<?=$class?>" align="center" >
		                	<a href="<?=$this->baseUrl()?>/admin/administracao/financeirochinareturnfor/invoice/<?=md5($lista->idped)?>"><img src="<?=$this->baseUrl()?>/images/visualizar_orc.gif" title="<?=$this->translate->_("Visualizar")?>" border="0" height="17" width="17"></a>
		                </td>		                
		            </tr>		            
					<?php  
					endforeach;	
					?>
					<tr>
						<td align="center" colspan="7">
							&nbsp;
			            </td>
			        </tr>
					<tr>
						<td align="center" colspan="7">
							<?php 
							if ((count($this->objList) > 0) and ($this->objPesq!=1)) :
				            	echo $this->objList;
				            endif;
			            	?>
			            </td>
			        </tr>
					</table><?php 							
					else :
					?>
					<center><?=$this->translate->_("Nenhum Invoice Encontrada")?></center>
					<?php 
					endif;
				?>    			
		         </td>
		       </tr>
		  </table>
		</td>
	</tr>
</table>