<!-- Content -->
	<div class="content">   

<!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a> </li>
                	<li class="lastB">Financeiro Shunkang</li>         
                </ul>
            </div>
        </div>       

        
        <div class="title"><h5>Financeiro Shunkang</h5></div>

		<div style="float: right;">
			<b>
			<a href="<?=$this->baseUrl(); ?>/admin/administracao/financeirochinapag"><?=$this->translate->_("Pagar")?></a> |
    		<a href="<?=$this->baseUrl(); ?>/admin/administracao/financeirochinarec"><?=$this->translate->_("Receber")?></a> |
            <a href="<?php echo $this->baseUrl(); ?>/admin/financeiro/relatorios"><?php echo $this->translate->_("Relatórios")?></a> |
    		<a href="<?=$this->baseUrl(); ?>/admin/administracao/financeirochinaconc"><?=$this->translate->_("Conciliação")?></a> |
            <a href="<?=$this->baseUrl(); ?>/admin/administracao/financeirochinabancos"><?=$this->translate->_("Adm")?></a>
            </b>
		</div>		

		<div class="widgets" >
			<div class="widget" style="border-top: 1px solid #d5d5d5;">
				<div style="margin: 10px 30px 10px 30px; width: 100%">
					<img src="<?php echo $this->baseUrl(); ?>/public/sistema/imagens/rightArrow.png" width="5" height="7" />&nbsp;<b>CONTAS À PAGAR</b><br>
					&nbsp; &nbsp; 
					<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeirochinapag" >
					Todas as contas
					</a><br>
					&nbsp; &nbsp; 
					<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeirochinapag/fil/avencer" >
					Contas a vencer: <b><?=count($this->objContasvencpag)?></b>
					</a><br>
					&nbsp; &nbsp; 
					<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeirochinapag/fil/avencersem" >
					Contas a vencer nessa semana: <b><?=count($this->objContasvencsempag)?></b>
					</a><br>
					&nbsp; &nbsp; 
					<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeirochinapag/fil/avencerhoje" >
					Contas a vencer hoje: <b><?=count($this->objContasvenchojepag)?></b>
					</a><br>
					&nbsp; &nbsp; 
					<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeirochinapag/fil/vencidas" >
					Contas vencidas: <b><?=count($this->objContasvencidaspag)?></b>
					</a>
				</div>				
				<div style="margin: 10px 30px 10px 30px; width: 100%">
					<img src="<?php echo $this->baseUrl(); ?>/public/sistema/imagens/rightArrow.png" width="5" height="7" />&nbsp;<b>CONTAS À RECEBER</b><br>
					&nbsp; &nbsp; 
					<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeirochinarec" >
					Todas as contas
					</a><br>
					&nbsp; &nbsp; 
					<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeirochinarec/fil/avencer" >
					Contas a vencer: <b><?=count($this->objContasvencrec)?></b>
					</a><br>
					&nbsp; &nbsp; 
					<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeirochinarec/fil/avencersem" >
					Contas a vencer nessa semana: <b><?=count($this->objContasvencsemrec)?></b>
					</a><br>
					&nbsp; &nbsp; 
					<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeirochinarec/fil/avencerhoje" >
					Contas a vencer hoje: <b><?=count($this->objContasvenchojerec)?></b>
					</a><br>
					&nbsp; &nbsp; 
					<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeirochinarec/fil/vencidas" >
					Contas vencidas: <b><?=count($this->objContasvencidasrec)?></b>
					</a>
				</div>
				<div style="margin: 10px 30px 30px 30px; width: 100%">
					<!--
					<img src="<?php echo $this->baseUrl(); ?>/public/sistema/imagens/rightArrow.png" width="5" height="7" />&nbsp;<b>RELATÓRIOS</b><br>
					
					&nbsp; &nbsp; 
					<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/financeirochinarelcontaspg" >
					Contas a pagar
					</a><br>
					&nbsp; &nbsp; 
					<a href="<?php echo $this->baseUrl(); ?>/admin/relatorios/financeirorelreceber" >
					Contas a receber
					</a><br>
					&nbsp; &nbsp;
					<a href="<?php echo $this->baseUrl(); ?>/admin/relatorios/financeirodre">
					Financeiro Gerencial
					</a><br />
					&nbsp; &nbsp;
					<a href="<?php echo $this->baseUrl(); ?>/admin/relatorios/financeirocomissoes">
					Comissões sobre venda
					</a><br />
					 &nbsp; &nbsp; 
					<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/painelatividades/tp/1/ids/<?php echo md5($usuario->ID);?>" >
					Contas a receber
					</a><br>
					&nbsp; &nbsp; 
					<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/painelatividades/tp/1/ids/<?php echo md5($usuario->ID);?>" >
					Demostração do Resultado de Exercício
					</a><br />
					&nbsp; &nbsp; 
					<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/painelatividades/tp/1/ids/<?php echo md5($usuario->ID);?>" >
					Emissão de boletos
					</a><br />
					&nbsp; &nbsp; 
					<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/painelatividades/tp/1/ids/<?php echo md5($usuario->ID);?>" >
					Extrato de contas
					</a>
					<br />
					&nbsp; &nbsp; 
					<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/painelatividades/tp/1/ids/<?php echo md5($usuario->ID);?>" >
					Plano de contas
					</a>
					<br />
					&nbsp; &nbsp; 
					<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/painelatividades/tp/1/ids/<?php echo md5($usuario->ID);?>" >
					Plano de contas
					</a>
					 -->
				</div>
			</div>
		</div>
	</div>