<h1>Novo</h1>

<?php

$title = $form->get('cfop');
$title->setAttribute('class','form-control');
$title->setLabelAttributes(['class' => 'control-label']);

$content = $form->get('naturezaop');
$content->setAttribute('class','form-control');
$content->setLabelAttributes(['class' => 'control-label']);

$submit = $form->get('submit');
$submit->setAttribute('class','btn btn-primary');

$form->setAttribute('action', $this->url('nfe', ['action'=>'novo']));
$form->prepare();

echo $this->form()->openTag($form);
?>

<?php $message = $this->formElementErrors($title, ['class' => 'help-block']);?>

<div class="form-group <?php echo $message ? 'has-error' : ''?>" >
    <?=$this->formLabel($title);?>
    <?=$this->formElement($title);?>
    <?=$message?>    
</div>

<?php $message = $this->formElementErrors($content, ['class' => 'help-block']);?>
<div class="form-group <?php echo $message ? 'has-error' : ''?>" >
    <?=$this->formLabel($content);?>
    <?=$this->formElement($content);?>
    <?=$message?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>