<script src="<?=$this->baseUrl()?>/public/sistema/js/buscaajax/taiCompras.js"></script>

    <div class="content">
       <!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a> </li>
                	<li ><a href="<?php echo $this->baseUrl(); ?>/admin/shuntaicompras/pedidos">Compras</a> </li>
                	<li ><a href="<?php echo $this->baseUrl(); ?>/admin/shuntaicompras/novopedido">Novo pedido</a> </li>
                	<li class="lastB">Busca de produtos</li>         
                </ul>
            </div>
        </div>       
        
        <div class="title"><h5><?php foreach ($this->objNfor as $nomefor);?>
		<?php echo $nomefor->EMPRESA?></h5></div>

        <div class="widgets">
    	<form action="<?=$this->baseUrl()?>/admin/shuntaicompras/gravacompra" method="post" name="prepedido" id="prepedido" class="mainForm">
    	    
    	    <input type="hidden" name="arrId" id="arrId">
    	    <input type="hidden" name="fornecedor" value="<?=$this->objFor;?>">
      
            <div class="widget">
     			<div class="head" style="border-bottom: 0px">
     			    <div style="float: left; width: 80%">
         			    <h5 class="iFrames">Produtos</h5>
    			    </div>		        
     			</div>
            	<table class="tableStatic" style="width: 100%" id="tabela">
                	<thead>
                    	<tr>
                            <td width="15%">Código</td>
                            <td width="10%">QT</td>
                            <td width="40%">Descrição</td>
                            <td width="">Preço</td>
                            <td width="">Total</td>
                            <td width="">*</td>                                                    
                        </tr>
                    </thead>
                    <tbody>
		                <tr>
		                    <td align="center"  >
            	                <input type="text" name="codigo" id="codigo" style="width: 80px">
            	            </td>
            	            <td align="center" >
            	                <input type="text" name="qt" id="qt" style="width: 60px" class="inteiro">
            	                  <script>
            	                  
            	                  function buscaprod(){
            	                	  var cod = document.getElementById('codigo').value;
            	                	  var qt  = document.getElementById('qt').value;
            	
            	                	  if(cod==''){
            	                    	  document.getElementById('resultado').innerHTML = 'Digite o Código!';
            	                    	  
            	                	  }else if(qt==''){
            	                		  document.getElementById('resultado').innerHTML = 'Digite a quantidade!';
            	                		  
            	                	  }else{
            	                		  MostraOpcao(qt,cod,<?=$this->objFor;?>);
            	                	  }
            	                  }
            	
            					 
            	                  </script>
            	            </td>
            	            <td  class="td" align="center" colspan="4" style="color:#FF0000; font-weight: bold; ">
            	               <div id="resultado" ></div>
            	            </td>
	                    </tr>
	                </tbody>
	           </table>
    	     </div>     
    	           
    	     <div style="padding-top: 10px">
    	     	<input type="button" value="Generate purchase" id="validaCompraprod" class="greenBtn" >
    			<script type="text/javascript">
    			function submitform(){
    				if(document.getElementById("arrId").value!=""){
    					document.prepedido.submit();
    				}else{
    					alert('Plese, select an product!');
    				}
    			}
    			</script>
    		 </div>
        </form>
        </div>
    </div>
