
<body  onload="document.prepedido.codigo.focus();">
<script src="<?php echo $this->baseUrl(); ?>/public/javascript/buscaajax/buscaajaxfabrica.js"></script>    
<script type="text/javascript">

function deleteRow(i,id){
    document.getElementById('txtHint').deleteRow(i);
    var arrId = document.getElementById('arrId').value;
	document.getElementById('arrId').value = arrId.replace(id+";","");

}

</script>        
		
<div id="siscorpo">		
	<div id="sisnavegacao">
		<a href="<?=$this->baseUrl()?>/admin/painel"><?=$this->translate->_("HOME")?></a>&nbsp; 
		<img src="<?=$this->baseUrl()?>/images/seta.png" width="5" height="7" />&nbsp;
		<a href="<?=$this->baseUrl()?>/admin/shuntaicompras/preordem"><?=$this->translate->_("PRÉ ORDEM")?></a>&nbsp;
		<img src="<?=$this->baseUrl()?>/images/seta.png" width="5" height="7" />&nbsp;
		<b><a href="<?=$this->baseUrl()?>/admin/shuntaicompras/preordemnovo"><?=$this->translate->_("NOVA PRÉ ORDEM")?></a></b>
	</div>
	<div id="sistitulo">
		NOVA PRÉ ORDEM
	</div>
	<div id="sisconteudo">
		
	<form action="<?php echo $this->baseUrl(); ?>/admin/shuntaicompras/gravapreordem" method="post" name="prepedido" id="prepedido">
	    <input type="hidden" name="permissao" id="permissao" value="<?php echo $this->objNeg?>">
	    <input type="hidden" name="arrId" id="arrId">    
	    <table align="left" class="mytable" width="100%" cellspacing="0"  id="txtHint">
	        <tr>
	            <th  class="th_canto" align="center" width="15%" >
	                C&Oacute;DIGO
	            </th>
	            <th  class="th_orc" align="center" width="5%">
	                QT
	            </th>
	            <th  class="th_orc" align="center" width="">
	                Descri&ccedil;&atilde;o
	            </th>
	            <th  class="th_orc" align="center" width="5%">
	                &nbsp;
	            </th>
	        </tr>
	        <tr>
	        	<td  class="td" align="center"  >
	                <input type="text" size="7" name="codigo" id="codigo" class="borda_input" onkeydown="if (event.keyCode == '13'){ return false; }; document.getElementById('resultado').innerHTML = '';">
	            </td>
	            <td  class="td" align="center" >
		            <input type="text" size="5" name="qt" id="qt"  onkeydown="if (event.keyCode == '13'){ return false; }; Mascara(this,Integer);"  
		            onclick="document.getElementById('resultado').innerHTML = '';"  onKeyPress="Mascara(this,Integer);" onKeyUp="Mascara(this,Integer);" 
		            onkeyup="mascara_num(this);"  onblur="buscaprod();">
	            </td>
	            <td  class="td" align="left" colspan="2" >
	            	 <div id="resultado" style="color:#FF0000; font-weight: bold;"></div>
	            </td>	            
	        </tr>
	     </table>
	     <script>
	                  
	                  function buscaprod(){
	                	  var cod = document.getElementById('codigo').value;
	                	  var qt  = document.getElementById('qt').value;
	                	  
	                	  if(cod==''){
	                    	  document.getElementById('resultado').innerHTML = 'Digite o c&oacute;digo!';
	                    	  
	                	  }else if(qt==''){
	                		  document.getElementById('resultado').innerHTML = 'Digite a quantidade!';
	                		  
	                	  }else{
	                		  MostraOpcao(cod,qt);
	                		  document.getElementById('codigo').value = "";
	                    	  document.getElementById('qt').value = "";
	                    	
	                	  }
	                  }
					 
		</script>
	     
	     <p align="left" style="margin-top: 5px">
	        &nbsp;<br />
			<input type="submit" value="Salvar" >
		</p>
		</form>
	</div>
</div>
    