<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>ZTL Brasil - www.ztlbrasil.com.br </title>
<link href="<?=$this->baseUrl()?>/public/sistema/imagens/ztl.ico" rel="shortcut icon" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script src="<?php echo $this->baseUrl(); ?>/public/sistema/js/buscaajax/manualGarantias.js"></script>

<style type="text/css">
body {
	margin-left: 10px;
	margin-top: 0px;
	margin-right: 10px;
	margin-bottom: 0px;
	color: #666666;
	font: 13px Arial, Helvetica, sans-serif;
}

.titulo{
	color: #666666;
	font: 15px Arial, Helvetica, sans-serif;
}

a:link {text-decoration: none}
a:visited {
	text-decoration: none;
	color: #990099;
}
a:hover {text-decoration: underline; 
color: #FF0000;
}
a:active {text-decoration: none}

.a2:link {
	text-decoration: none;
	color:#8d8d8d; 
}

.a2:hover {text-decoration: underline; 
color: #515151;
}

</style>
</head>

<body>
<table width="100%" border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td colspan="2" style="border-bottom: 1px solid #0098a1; padding-top: 15px; padding-bottom: 15px" align="left">
		<img alt="ZTL Brasil" src="<?php echo $this->baseUrl(); ?>/images/Figura1.png" />
		</td>
	</tr>
	<tr>
		<td  align="left" valign="top" width="170px" class="titulo" style="border-right: 1px solid #0098a1; height: 20px" >
		Manual Garantias
		</td>
		<td align="left"  rowspan="2" valign="top">
		<div id="imgmanual" style="margin-top: 20px; margin-left: 20px; margin-bottom: 20px" >
			<img alt="Acesso ao Site da ZTL" src="<?=$this->baseUrl(); ?>/public/sistema/upload/manual/garantias/1.jpg" />
			
			<div style="width: 700px; margin-top: 5px; " align="center" >
			<a class="a2" href="javascript:void(0);" onclick="MostraOpcao('2');">Próximo passo >></a>
			</div>
		</div>
		</td>
	</tr>
	<tr>
		<td align="left" valign="top" style="border-right: 1px solid #0098a1;" >
			<table cellpadding="5" cellspacing="2" align="left">
				<tr>
					<td  align="left" valign="top">
					<a href="javascript:void(0);" onclick="MostraOpcao('1');">Acessando o Sistema de Garantias</a>
					</td>
				</tr>
				<tr>
					<td  align="left" valign="top">
					<a href="javascript:void(0);" onclick="MostraOpcao('2');">Visualizando as suas Garantias</a>
					</td>
				</tr>
				<tr>
					<td  align="left" valign="top">
					<a href="javascript:void(0);" onclick="MostraOpcao('3');">Como fazer uma nova solicitação de Garantia</a>
					</td>
				</tr>
				<tr>
					<td  align="left" valign="top">
					<a href="javascript:void(0);" onclick="MostraOpcao('4');">Preenchendo o formulário de Solicitação</a>
					</td>
				</tr>
				<tr>
					<td  align="left" valign="top">
					<a href="javascript:void(0);" onclick="MostraOpcao('5');">Aguardando a autorização para o Envio</a>
					</td>
				</tr>
				<tr>
					<td  align="left" valign="top">
					<a href="javascript:void(0);" onclick="MostraOpcao('6');">Envio recusado. Como proceder?</a>
					</td>
				</tr>
				<tr>
					<td  align="left" valign="top">
					<a href="javascript:void(0);" onclick="MostraOpcao('7');">Envio autorizado. Hora de enviar os produtos à ZTL</a>
					</td>
				</tr>
				<tr>
					<td  align="left" valign="top">
					<a href="javascript:void(0);" onclick="MostraOpcao('8');">Acompanhando a situação da sua Solicitação</a>
					</td>
				</tr>
				<tr>
					<td  align="left" valign="top">
					<a href="javascript:void(0);" onclick="MostraOpcao('9');">Análise Concluída. Saiba qual foi o resultado da sua solicitação</a>
					</td>
				</tr>
				<tr>
					<td  align="left" valign="top">
					<a href="javascript:void(0);" onclick="MostraOpcao('10');">Detalhes da análise</a>
					</td>
				</tr>
				<tr>
					<td  align="left" valign="top">
					<a href="javascript:void(0);" onclick="MostraOpcao('11');">Solicitação Finalizada. Aguarde o envio dos seus produtos</a>
					</td>
				</tr>
				
			</table>
		</td>
	</tr>
</table>
</body>
</html>