<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>ZTL Brasil - www.ztlbrasil.com.br </title>
<link href="<?=$this->baseUrl()?>/public/sistema/imagens/ztl.ico" rel="shortcut icon" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<style>

body {
	margin-left: 10px;
	margin-top: 0px;
	margin-right: 10px;
	margin-bottom: 0px;
	color: #666666;
	font: 13px Arial, Helvetica, sans-serif;
}

.titulo{
	color: #666666;
	font: 15px Arial, Helvetica, sans-serif;
}

a:link {text-decoration: none}
a:visited {text-decoration: none}
a:hover {text-decoration: underline; 
color: #FF0000;
}
a:active {text-decoration: none}


</style>
</head>

<body>
<table width="100%" border="0">
	<tr>
		<td colspan="3" style="border-bottom: 1px solid #0098a1; padding-top: 15px; padding-bottom: 15px" align="left">
		<img alt="ZTL Brasil" src="<?php echo $this->baseUrl(); ?>/images/Figura1.png" />
		</td>
	</tr>
	<tr>
		<td align="left" width="200px" class="titulo">
		Manual Garantias
		</td>
		<td align="left" style="border-left: 1px solid #0098a1;" rowspan="2" width="1px">
		&nbsp;
		</td>
		<td align="left" class="titulo">
		<b>Solicitação de Garantias</b>
		</td>
	</tr>
	<tr>
		<td align="left">
			<table>
				<tr>
					<td  align="left">
					<a href="<?=$this->baseUrl()?>/admin/manual/">Solicitação de Garantias</a>
					</td>
				</tr>
			</table>
		</td>
		
		<td align="left">
			<table>
				<tr>
					<td align="left" >
						Para realizar solicitações de garantia, é necessário que possua acesso ao sistema on-line da ZTL do Brasil, 
						acessado pelo endereço <a href="http://www.ztlbrasil.com.br">http://www.ztlbrasil.com.br</a>.
						<br />
						
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
</body>
</html>