<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Garantias ZTL, garantindo tranquilidade</title>

<style type="text/css">
<!--
body {
	background-image: url(<?php echo $this->baseUrl(); ?>/images/fundo.jpg);
	margin-top: 30px;
	margin-bottom: 0px;
	margin-left: 0px;
	border-top-width: 0px;
	border-right-width: 0px;
	border-bottom-width: 0px;
	border-left-width: 0px;
	border-top-style: 0;
	border-right-style: 0;
	border-bottom-style: 0;
	border-left-style: 0;
	color: #4b4b4b;
	font: 11px "Trebuchet MS", Arial, Helvetica, sans-serif;
	
}

#rolagem{
	
	top: 0px;
	left: 20px;
	width: 300px;
	height : 400px;
	font-family : verdana;
	font-size: 11px;
	overflow : auto;
	margin: 5px 5px 5px 5px;
	padding: 5px 5px 5px 5px;
	
	
}
	
-->
</style>
<script src="../Scripts/swfobject_modified.js" type="text/javascript"></script>
</head>

<body>
<table width="200" border="0" cellspacing="0">
  <tr>  </tr>
</table>

<table border="0" cellspacing="0" cellpadding="0" align="center"> 
	<tr>
	<td width="17" >
	</td>
	<td>
		<img src="<?php echo $this->baseUrl(); ?>/images/banner_topo.png" width="799" height="79" />	
	</td></tr>
	<tr>
	<td>
	</td>
	<td>
	<table border="0" cellspacing="0" cellpadding="0"  width="799"  background="<?php echo $this->baseUrl(); ?>/images/fundo2.png">
		<tr>
			<td width="370px" height="471" rowspan="3"  align="left">
				<table width="90%" align="center" cellpadding="15px">
				<tr><td align="justify">
				<div id="rolagem">

					A Super Garantia <b>ZTL</b> cobre somente os <b>DEFEITOS DE FABRICAÇÃO</b> de nossos produtos, o que é muito difícil acontecer.
					<br /><br />
					O procedimento de cobertura segue duas linhas de ação:
					<br />
					            1- Garantia por KM rodada. Todos os nossos produtos são garantidos por até 30.000KM, ou;
					<br />
					            2- Garantia por tempo de uso. A cobertura é de 90 dias (garantia legal) + 90 dias (Super Garantia Estendida ZTL); totalizando 180 dias de garantia total após a INSTALAÇÃO do produto.
					<br /><br />
					Lembre-se que:
					<br /><br />
					a) A Garantia se encerra aos 30.000KM, caso esta KM seja alcançada antes dos 90 dias de uso contínuo do produto;
					<br />
					b) A confirmação do período de uso só é possível com a devida Nota Fiscal de Venda ao Consumidor Final. Peça ao vendedor que anote a KM do seu veículo no momento da instalação do produto no verso da Nota Fiscal para facilitar nossa análise;
					<br />
					c) Por questões tributárias, o envio de qualquer produto para análise de garantia deve ser feito por um Distribuidor Autorizado ZTL.
					<br />
					d) Lembre-se que a garantia SÓ cobre DEFEITOS DE FABRICAÇÃO. Mal uso ou instalação inadequada não se enquadram no processo de análise de garantia.
					<br />
					e) Em caso de processos de garantia que exijam ressarcimento de mão-de-obra, outros produtos relacionados ao produto ZTL, ou mesmo, danos a terceiros; pedimos ao Distribuidor Autorizado ZTL entrar em contato de forma imediata com o nosso SAC (0800-702 7370) para orientação apropriada antes do envio das amostras para análise. Sem este tipo de orientação fica impossível decidirmos algo sobre o pagamento de qualquer ressarcimento a terceiros ou a outros produtos.
					
					 <br /><br />
					
					Finalmente, para os distribuidores ZTL, as instruções, os procedimentos e o tutorial para envio de análises em garantia estão disponíveis na parte do Acesso Restrito de nosso site.
					<br />
					Conte com nosso suporte sempre que necessário e em caso de dúvidas entre em CONTATO.
					
					<p align="right"><b>Departamento de Engenharia</b></p>
					
				</div>
				
				</td></tr>
				</table>
			
			
			
			</td>
			<td align="left" valign="bottom">
				<table  width="415" height="20"  border="0" cellspacing="0" cellpadding="0">
				  <tr>
				    <td onmouseout="abasflash();" >
				    	<img id="spancli" onmouseover="abas(1);" border="0" src="<?php echo $this->baseUrl(); ?>/images/cliente.png" />
				    	
				    </td>
				    <td onmouseout="abasflash();">
				    	<img id="spanauto" onmouseover="abas(2);" border="0" src="<?php echo $this->baseUrl(); ?>/images/autopecas.png" />
				    	
				    </td>
				    <td onmouseout="abasflash();">
				    	<img id="spandist" onmouseover="abas(3);" border="0" src="<?php echo $this->baseUrl(); ?>/images/distribuidor.png" />
				    	
				    </td>
				    <td width="220" onmouseout="abasflash();" >
				    	<img id="spanztl" onmouseover="abas(4);" border="0" src="<?php echo $this->baseUrl(); ?>/images/ztlbrasil.png" />
				    	
				    </td>
				  </tr>
				</table>
			</td>
		</tr>
		<tr>
			<td align="left" valign="top">
				  <table style="display: block; margin-top: 10px; margin-bottom: 4px" id="flash" width="415"  border="0" cellspacing="0" cellpadding="0">
				    <tr>
				      <td valign="top">
				      
				      	<OBJECT CLASSID="CLSID:D27CDB6E-AE6D-11cf-96B8-444553540000"
						CODEBASE="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,22,0" ID="IncrediFlash" Width="393" Height="262">
						<PARAM NAME="movie" VALUE="<?php echo $this->baseUrl(); ?>/images/Projeto_banner2.swf?317338960">
						<PARAM NAME="bgcolor" VALUE="#FFFFFF">
						<EMBED NAME="IncrediFlash" SRC="<?php echo $this->baseUrl(); ?>/images/Projeto_banner2.swf?317338960" BGCOLOR="#FFFFFF"
						WIDTH="393" HEIGHT="262" TYPE="application/x-shockwave-flash" pluginspage=http://www.macromedia.com/go/getflashplayer">
						</EMBED>
						</OBJECT>
				      
				      </td>
				    </tr>
				  </table>
				   <table style="display: none; margin-bottom: 4px " height="273" width="406" id="eventos" border="0" cellspacing="0" cellpadding="0">
				    <tr>
				      <td id="tdevento" >  </td>
				      
				    </tr>
				  </table>
				  * Passe o mouse sobre os ícones acima para mais detalhes
			</td>
		</tr>
		<tr>
			
			<td align="right">
				  <table width="415" border="0" cellspacing="0" cellpadding="0">
				    <tr>
				      <td  height="85"  ></td>  
				    </tr>
				  </table>
				 </td>
			</tr>
	</table>
	</td>
	</tr>
	<tr>
		<td colspan="2">
			<img src="<?php echo $this->baseUrl(); ?>/images/banner_rodape.png" width="816" height="62" />
		</td>
	</tr>
</table>

<script type="text/javascript">

function abasflash(){
	document.getElementById('flash').style.display = 'block'; 
	document.getElementById('eventos').style.display = 'none';
	
	document.getElementById('spancli').src="../../admin/images/cliente.png";
	document.getElementById('spanauto').src="../../admin/images/autopecas.png";
	document.getElementById('spandist').src="../../admin/images/distribuidor.png";
	document.getElementById('spanztl').src="../../admin/images/ztlbrasil.png";
}

function abas(aba){
	if(aba==1){
		document.getElementById('spancli').src ="../../admin/images/cliente_aba.png";
		document.getElementById('tdevento').innerHTML ='<img src="../../admin/images/cliente_aba_II.png" />';

		document.getElementById('spanauto').src ="../../admin/images/autopecas.png";
		document.getElementById('spandist').src ="../../admin/images/distribuidor.png";
		document.getElementById('spanztl').src ="../../admin/images/ztlbrasil.png";
	}else if(aba==2){
		document.getElementById('spanauto').src="../../admin/images/autopecas_aba.png";
		document.getElementById('tdevento').innerHTML ='<img src="../../admin/images/autopecas_aba_II.png" />';

		document.getElementById('spancli').src="../../admin/images/cliente.png";
		document.getElementById('spandist').src="../../admin/images/distribuidor.png";
		document.getElementById('spanztl').src="../../admin/images/ztlbrasil.png";
	}else if(aba==3){
		document.getElementById('spandist').src="../../admin/images/distribuidor_aba.png";
		document.getElementById('tdevento').innerHTML ='<img src="../../admin/images/distribuidor_aba_II.png" />';

		document.getElementById('spanauto').src="../../admin/images/autopecas.png";
		document.getElementById('spancli').src="../../admin/images/cliente.png";
		document.getElementById('spanztl').src="../../admin/images/ztlbrasil.png";
	}else if(aba==4){
		document.getElementById('spanztl').src="../../admin/images/ztlbrasil_aba.png";
		document.getElementById('tdevento').innerHTML ='<img src="../../admin/images/ztlbrasil_aba_II.png" />';

		document.getElementById('spanauto').src="../../admin/images/autopecas.png";
		document.getElementById('spandist').src="../../admin/images/distribuidor.png";
		document.getElementById('spancli').src="../../admin/images/cliente.png";
	}
	
	document.getElementById('flash').style.display = 'none'; 
	document.getElementById('eventos').style.display = 'block';
}



</script>
</body></html>