<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>ZTL Brasil - www.ztlbrasil.com.br </title>
	<link href="<?=$this->baseUrl()?>/public/sistema/imagens/ztl.ico" rel="shortcut icon" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="description" content="<?=$this->translate->_("ZTL do Brasil importação, exportação e comercio")?>" />
	<meta name="keywords" content="rolamentos, cubo de roda, rolamento, embreagem, embreagens, ponta de eixo, pontas de eixo, bomba dagua, bombas dagua, roda, scania, homocinetica, homocineticas, transmissoes" />
	
	<link href="<?php echo $this->baseUrl(); ?>/css/estilo.css" rel="stylesheet" type="text/css" />
	<link href="<?php echo $this->baseUrl(); ?>/css/sistemaestilo.css" rel="stylesheet" type="text/css" />
	<link href="<?php echo $this->baseUrl(); ?>/css/tabulacao.css" rel="stylesheet" type="text/css" />	
	
	<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/javascript/mascaras.js"></script>
	
</head>

<body>
<?php 
if(count($this->objDet)>0):
	foreach ($this->objDet as $listdet);
	$ped = $listdet->idped;
endif;
?>

<div id="siscorpo">
	<?php 
	if(!empty($this->objForsel)):
	?>
	
	<div id="sistitulo" style="width: 900px; margin: 0 auto; height: 25px; margin-top: 10px; line-height: 25px">
	<?=$this->translate->_("LISTA DE PACOTES")?>
	<?php 
	foreach ($this->objFor as $fornecedor): 
		if($this->objForsel == $fornecedor->id_for): 	
			echo " - ".$fornecedor->EMPRESA." (".$fornecedor->nome.")";
		endif;
	endforeach; ?>
	</div>
    <div id="sisconteudo" style="width: 900px; margin: 0 auto;">		
    	<div >    	
    	<?php 
    	
    	if(count($this->objProd)>0): 
    		$verqt = 0;
	    	foreach($this->objProd as $lista):
		    	if($lista->qtprod > $lista->qtpack):
		    		$verqt = 1;
		    	endif;
	    	endforeach;  
	    	  	
	    	if($verqt==1):
	    	?>
			<form action="<?=$this->baseUrl()?>/admin/publico/gerarpacklistfor" method="post" name="cad">
			<input type="hidden" value="<?=$listdet->idped?>" name="ped" />
			<input type="hidden" value="<?=$this->objForsel?>" name="idfor" />
			<div style="border-bottom: 1px solid; " >
				<table class="mytable" style="margin-top: 5px; width: 100%; margin-bottom: 10px" >
					<tr>
			            <th  class="th_canto" style="text-align: center;" width="20%">
			                <?=$this->translate->_("CODIGO")?>
			            </th>
			            <th  class="th_pedido" align="center" width="15%">
			                <?=$this->translate->_("COMPRA")?>
			            </th>
			            <th  class="th_pedido" align="center" width="15%">
			                <?=$this->translate->_("QT DISPONÍVEL")?>
			            </th>
			            <th  class="th_pedido" align="center" width="10%">
			                <?=$this->translate->_("QT")?>*
			            </th>
			            <th  class="th_pedido" align="center" width="10%">
			                <?=$this->translate->_("PKGS")?>*
			            </th>
			            <th  class="th_pedido" align="center" width="10%">
			                <?=$this->translate->_("G.W.KGS")?>
			            </th>
			            <th  class="th_pedido" align="center" width="10%">
			                <?=$this->translate->_("N.W.KGS")?>
			            </th>
			        </tr>					
					<?php 
					$cor = 0;
			    	foreach($this->objProd as $lista):
			    		if($lista->qtprod > $lista->qtpack):
			    	 		$cor++;
				            if(($cor%2)==0) $class = 'td_orc_par';
				            else $class = 'td_orc';		            
			               	?>
							<tr >
				                <td  class="<?=$class?>" align="left" style="padding: 3px">
				                   <?=$lista->CODIGO?>                  
				                </td>
				                <td  class="<?=$class?>" style="text-align: center; padding: 3px" >
				                    <?php 
				                	//--- Verifico as compras dos produtos -----------------------
				                	foreach ($this->objProdpk as $purchase):
				                		if($purchase->id_prod == $lista->idproduto):
						                	?>
						                	PK<?=substr("000000".$purchase->id_kang_compra, -6,6)?><br />
						                	<?php
						                endif; 
				                	endforeach;
				                	?>
				                </td>
				                <td  class="<?=$class?>" style="text-align: center; padding: 3px" >
				                    <?=$lista->qtprod-$lista->qtpack?>
				                </td>
				                <td  class="<?=$class?>" style="text-align: center; padding: 3px" >
				                   <input name="qt_<?=$lista->id_prod?>" type="text" size="5px" onkeydown="Mascara(this,Integer);" onkeypress="Mascara(this,Integer);" onkeyup="Mascara(this,Integer);">           
				                </td>
				                <td  class="<?=$class?>" style="text-align: center;" >
				                   <input name="pc_<?=$lista->id_prod?>" type="text" size="5px" onkeydown="Mascara(this,Kilo);" onkeypress="Mascara(this,Kilo);" onkeyup="Mascara(this,Kilo);" >
				                </td>
				                <td  class="<?=$class?>" style="text-align: center;" >
				                	<input name="gw_<?=$lista->id_prod?>" type="text" size="5px" onkeydown="Mascara(this,Kilo);" onkeypress="Mascara(this,Kilo);" onkeyup="Mascara(this,Kilo);" >
				                </td>
				                <td  class="<?=$class?>" style="text-align: center;" >
				                	<input name="nw_<?=$lista->id_prod?>" type="text" size="5px" onkeydown="Mascara(this,Kilo);" onkeypress="Mascara(this,Kilo);" onkeyup="Mascara(this,Kilo);" >
				                </td>                 
				            </tr>				            
							<?php	
						endif;				
					endforeach;
					?>					
				</table>
			</div>
			<div style="margin-top: 10px">
				<table  class="mytable" style="width: 100%">
					<tr>
			            <th class="th_canto" style="text-align: center;" width="30%">
			                &nbsp;
			            </th>
			            <th  class="th_pedido" align="center" width="10%">
			                <?=$this->translate->_("G.W.KGS")?>
			            </th>
			            <th  class="th_pedido" align="center" width="10%">
			                <?=$this->translate->_("N.W.KGS")?>
			            </th>
			            <th  class="th_pedido" align="center" width="10%">
			                <?=$this->translate->_("MEAS.M3")?>
			            </th>
			        </tr>
					<tr >
		                <td  class="<?=$class?>" style="padding: 3px; text-align: center; font-weight: bold;">
		                   Total
		                </td>
		                <td  class="<?=$class?>" style="text-align: center;" width="10%">
		                	<input name="gw" type="text" size="5px" onkeydown="Mascara(this,Kilo);" onkeypress="Mascara(this,Kilo);" onkeyup="Mascara(this,Kilo);" />
		                </td>
		                <td  class="<?=$class?>" style="text-align: center;" width="10%">
		                	<input name="nw" type="text" size="5px" onkeydown="Mascara(this,Kilo);" onkeypress="Mascara(this,Kilo);" onkeyup="Mascara(this,Kilo);" />
		                </td>                 
		                <td  class="<?=$class?>" style="text-align: center;" width="30%">
		                	C <input name="comprimento" type="text" size="5px" onkeydown="Mascara(this,Kilo);" onkeypress="Mascara(this,Kilo);" onkeyup="Mascara(this,Kilo);" />
		                	L <input name="largura" type="text" size="5px" onkeydown="Mascara(this,Kilo);" onkeypress="Mascara(this,Kilo);" onkeyup="Mascara(this,Kilo);" />
		                	A <input name="altura" type="text" size="5px" onkeydown="Mascara(this,Kilo);" onkeypress="Mascara(this,Kilo);" onkeyup="Mascara(this,Kilo);" />
		                </td>
		            </tr>
		         </table>
			</div>	
			<div style="margin-top: 10px">
				<input type="button" value="Gerar pacote" onclick="validaCampos()" /><br />
				<i>* Campos obrigatórios</i>
			</div>
		</form>
		<?php else: ?>
		<div style="text-align: center; font-weight: bold; margin-top: 30px">
			Sem produtos para geração de pallets
		</div>
		<?php endif; 
	endif;
	?> 
	
		<div >
			<?php 
	    	if(!empty($this->objPack)):
	    	
	    	?>
	    	<div style="border-bottom: 1px solid; font-weight: bold; margin-top: 20px; font-size: 14px">
	    	PALLETS
	    	</div>		
	    	<?php 
	    	
	    	
	    	$contp 		= 0;
	    	$totalpacks = count($this->objPack); 
	    	
	    	foreach ($this->objPack as $pack):
	    		$contp ++;
		    	
		    	$totalp = $totalc = $countpl = $verdup = $cor = 0;
		    	//--- conta o qt para o rowspan da tabela -----------------------
		    	foreach($this->objProdpl as $lista):
			    	if($pack->id == $lista->id_pack):
				    	$countpl++;
				    	//--- verifica se produto pode ser duplicado ------------------------
				    	foreach($this->objProd as $listaver):
				    		if($listaver->id_prod == $lista->id_prod):
						    	if(($listaver->qtprod-$listaver->qtpack) < $lista->qt):
						    		$verdup = 1;
						    	endif;
						    endif;
				    	endforeach;
			    	endif;
		    	endforeach;
	    	
	    	
	    		?>
	    		<table 	width="500px" class="mytable" style="margin-top: 10px;" >
	    			<tr>
						<th  class="th_canto" style="text-align: left;" colspan="5">
			                <?=$this->translate->_("PALLET Nº ")?> <?=$contp."/".$totalpacks?>     
			            </th>
						<th  class="th_pedido" align="center" >
			                <?php if($pack->sit=="1"): ?>
		                	<a href="#" onclick="if(confirm('Cancelar Pallet?')){ window.location='<?=$this->baseUrl()?>/admin/publico/removerpacklistfor/ped/<?=md5($listdet->idped)?>/pack/<?=md5($pack->id)?>/idfor/<?=$this->objForsel?>';};"><img src="<?=$this->baseUrl();?>/images/window-close.png" title="Remove" border="0" width="15"></a>
		                	<?php endif; ?>
		                	<?php 
							if($verdup==0):
							?>
							&nbsp;
							<a href="javascript:void(0)" onclick="if(confirm('Duplicatar o pallet?')){ window.location='<?=$this->baseUrl()?>/admin/publico/packcopiafor/ped/<?=md5($listdet->idped)?>/pack/<?=$pack->id?>/idfor/<?=$this->objForsel?>';}"><img src="<?=$this->baseUrl()?>/imagens/sistema/duplicar.png" width="15" border="0" title="Duplicate pallet" /></a>
							<?php 
							endif;
							?>
			            </th>
			        </tr>
					<tr>
						<th  class="th_canto" style="text-align: center;" width="20%">
			                <?=$this->translate->_("CODIGO")?>
			            </th>
			            <th  class="th_pedido" align="center" width="20%">
			                <?=$this->translate->_("QT")?>
			            </th>
			            <th  class="th_pedido" align="center" width="10%">
			                <?=$this->translate->_("PKGS")?>
			            </th>
			            <th  class="th_pedido" align="center" width="10%">
			                <?=$this->translate->_("G.W.KGS")?>
			            </th>
			            <th  class="th_pedido" align="center" width="10%">
			                <?=$this->translate->_("N.W.KGS")?>
			            </th>
			            <th  class="th_pedido" align="center" width="10%">
			                <?=$this->translate->_("MEAS.M3")?>
			            </th>
			        </tr>					
					<?php 
					
					foreach($this->objProdpl as $lista):
						if($pack->id == $lista->id_pack):
			            	$cor++;
				            if(($cor%2)==0) $class = 'td_orc_par';
				            else $class = 'td_orc';	
				            
			               	?>
							<tr >
								<td  class="<?=$class?>" align="left" style="padding: 3px">
				                   <?=$lista->CODIGO?>                  
				                </td>
				                <td  class="<?=$class?>" style="text-align: center; padding: 3px" >
				                    <?=$lista->qt?>
				                </td>
				                <td  class="<?=$class?>" style="text-align: center; padding: 3px" >
				                    <?=$lista->pkgs?>
				                </td>
	                   			<td  class="<?=$class?>" style="text-align: center; padding: 3px" >
				                    <?=$lista->peso_bruto?>
				                </td>
				                <td  class="<?=$class?>" style="text-align: center; padding: 3px" >
				                    <?=$lista->peso_liquido?>
				                </td>
				                <?php if($cor==1):?>
				                <td  class="<?=$class?>" rowspan="<?=$countpl+1?>" style="text-align: center; padding: 3px; font-weight: bold;" >
				                	 <?=number_format($pack->altura*$pack->comprimento*$pack->largura,3,",",".")?>
				                </td>
				                <?php endif; ?>
				            </tr>				            
							<?php 
							$totalp += $lista->qt;
							$totalc	+= $lista->pkgs;
						endif; 					
					endforeach;
					
					$cor++;
		            if(($cor%2)==0) $class = 'td_orc_par';
		            else $class = 'td_orc';	
					
					?>
					<tr >
		                <td class="<?=$class?>" align="left" style="padding: 3px; font-weight: bold;">
		                   Total                 
		                </td>
		                <td  class="<?=$class?>" style="text-align: center; padding: 3px;  font-weight: bold;">
		                    <?=$totalp?>
		                </td>
		                <td  class="<?=$class?>" style="text-align: center; padding: 3px;  font-weight: bold;">
		                    <?=$totalc?>
					    </td>
		                <td  class="<?=$class?>" style="text-align: center; padding: 3px;  font-weight: bold;">
		                    <?=$pack->peso_bruto?>
		                </td>
		                <td  class="<?=$class?>" style="text-align: center; padding: 3px;  font-weight: bold;">
		                    <?=$pack->peso_liquido?>
		                </td>	                
		            </tr>						
				</table>
	    		<?php 
	    	endforeach;
	    	endif;
	    	?>
		</div>		
	</div>
	</div>
</div>
<?php else: ?>	
	<div style="font-size: 16px; width: 900px; margin: 0 auto; text-align: center; margin-top: 100px">
	<?=$this->translate->_("Sem acesso ao sistema de geração de pallets")?>.<br /> 
	<?=$this->translate->_("Favor entrar em contato pelo e-mail")?> blirio@shucorp.com.
	</div>
<?php endif; ?>	
<script>
	
	function validaCampos(){
		var ver = 0;
		var ver2 = 0;
		var ver3 = 0;
		<?php 
		foreach($this->objProd as $lista):
		    if($lista->qtprod > $lista->qtpack):
    	 	?>
			if(((document.cad.qt_<?=$lista->id_prod?>.value=="") && (document.cad.pc_<?=$lista->id_prod?>.value!="")) || ((document.cad.qt_<?=$lista->id_prod?>.value!="") && (document.cad.pc_<?=$lista->id_prod?>.value==""))){
				ver = 1;
			}
			if((document.cad.qt_<?=$lista->id_prod?>.value!="") && (document.cad.pc_<?=$lista->id_prod?>.value!="")){
				ver2 = 1;	
			}

			if(document.cad.qt_<?=$lista->id_prod?>.value!=""){
				qt = parseInt(document.cad.qt_<?=$lista->id_prod?>.value);
				if(qt > <?=$lista->qtprod-$lista->qtpack?>){
					alert("<?=$this->translate->_("A quantidade do produto ".$lista->CODIGO." não pode ser superior a QT disponível!")?>!");
					ver3 = 1;
				}
			}
			<?php
			endif;			
		endforeach;		
		?>	

		if(ver == 1){
			alert("<?=$this->translate->_("Preencha todos os campos corretamente")?>!");
		}else if(ver2==0){
			alert("<?=$this->translate->_("Selecione ao menos um produto")?>!");
		}else if(document.cad.gw.value==""){
			alert("<?=$this->translate->_("O peso bruto não pode ficar em branco")?>!");
		}else if(document.cad.nw.value==""){
			alert("<?=$this->translate->_("O peso líquido não pode ficar em branco")?>!");
		}else if(document.cad.comprimento.value==""){
			alert("<?=$this->translate->_("O comprimento não pode ficar em branco")?>!");
		}else if(document.cad.largura.value==""){
			alert("<?=$this->translate->_("A largura não pode ficar em branco")?>!");
		}else if(document.cad.altura.value==""){
			alert("<?=$this->translate->_("A altura não pode ficar em branco")?>!");
		}else if((ver2 == 1)&&(ver3 == 0)){
			document.cad.submit();
		}		
	}
</script>


</body>
</html>