<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<title>Copa ZTL de Tenis de mesa</title>
<style type="">
a{
	text-decoration:none;
	color:#FFF;
}

a:hover{
	color:#333;
}

</style>

</head>

<body style="font: 18px 'Trebuchet MS', Verdana, Arial, Helvetica, sans-serif;">
<table width="1000"  cellspacing="0" cellpadding="0" align="center" >
  <tr>
    <td valign="top">
    <table width="1000" border="0" cellspacing="0" cellpadding="0" align="center">
      <tr>
        <td colspan="8"><img src="<?=$this->baseUrl()?>/images/pingpong/topo.jpg" width="1000" height="123" /></td>
      </tr>
      <tr>
        <td style="background-image:url(<?=$this->baseUrl()?>/images/pingpong/lateral.jpg); background-repeat: repeat-y; background-color:#E6E6E6" colspan="7">&nbsp;</td>
      <td style="background-image:url(<?=$this->baseUrl()?>/images/pingpong/lateral2.jpg); background-repeat:repeat-y;">&nbsp;</td></tr>
      
      <tr>
        <td width="12"  style="background-image:url(<?=$this->baseUrl()?>/images/pingpong/lateral.jpg); background-color:#E6E6E6; background-repeat:repeat-y">&nbsp;</td>
        <td colspan="6" style="background-color:#E6E6E6;" align="center"  >
        	<div id="jog">
			<table width="90%" align="center" cellspacing="0" cellpadding="0" >
			<?php
			$cont=$conttotal=0;
			$contt=1;
			$contpart = count($this->objHist);
			$color = "#dcffff";
			foreach ($this->objTennis as $listajog):
				if($cont>7):
					$contt++;
					$color = "#ffd1d1";	
				elseif($cont>3):
					$contt++;
					$color = "#ffe3d0";		
				endif;
				
				$conttotal++;
				
				$venc = 0;
				if($listajog->venca!=0):
					$venc = $listajog->venca;
				else:
					$venc = 0;
				endif;
				if($contpart!=0):
					$perc = ($venc*100)/$contpart;
				endif;	
				
				$qtdisputa = 0;
				foreach ($this->objQtdis as $qtdis):
					if($qtdis->idj == $listajog->idj) $qtdisputa = $qtdis->qtpart;
				endforeach;
				$percpart = 0;
				if($qtdisputa!=0):
					$percpart = ($venc*100)/$qtdisputa;
				endif;
				
				?>
				<tr >
					<td align="left" style="padding: 4px; background-color: <?=$color?>" width="15%" >
						<?=$listajog->nome?>
					</td>
					<td align="left" width="50%">
						<img src="<?=$this->baseUrl()?>/images/pingpong/perc.jpg" width="<?=$perc*10?>" height="20" />
					</td>
					<td style="text-align: right;">
					<?=$venc?> (<?=number_format($perc,2)?>%)
					</td>
					<td style="text-align: right;">
					<?=$qtdisputa?> (<?=number_format($percpart,2)?>%)
					</td>
				</tr>
				
			<?php
			$cont++; 
			endforeach;
			?>
						
			</table>
			<table width="80%" align="center" style="margin-top: 20px">
				<tr>				
					<td align="left">				
					Total partidas: <?=$contpart?>
					</td>
				</tr>
			</table>
			</div>
        
        </td>
        <td style="background-image:url(<?=$this->baseUrl()?>/images/pingpong/lateral2.jpg); background-repeat:repeat-y" width="16">&nbsp;</td>
      </tr>
    
      <tr>
        <td><img src="<?=$this->baseUrl()?>/images/pingpong/1.jpg" width="15" height="24" /></td>
        <td style="background-color:#E6E6E6;">&nbsp;</td>
        <td style="background-color:#E6E6E6;">&nbsp;</td>
        <td style="background-color:#E6E6E6;">&nbsp;</td>
        <td style="background-color:#E6E6E6;">&nbsp;</td>
        <td style="background-color:#E6E6E6;">&nbsp;</td>
        <td style="background-color:#E6E6E6;">&nbsp;</td>
        <td><img src="<?=$this->baseUrl()?>/images/pingpong/2.jpg" width="15" height="24" /></td>
      </tr>
      <tr>
        <td align="right" colspan="8" height="90px" style="background-image:url(<?=$this->baseUrl()?>/images/pingpong/rodape.jpg); background-repeat:repeat-y; font-size: 30px ; color: #FFF" >
      		<a href="index" >PARTIDAS</a> | <a href="consulta" >CONFRONTOS</a> &nbsp; &nbsp; 
        </td>
      </tr>      
    </table>
    </td>
  </tr>
</table>
</body>
</html>