

<!-- Content -->
    <div class="content">   
    	<!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a> </li>
                	<li><a href="<?php echo $this->baseUrl()?>/admin/correio/mailing">Boletim eletrônico</a></li>
                	<li class="lastB">Enviando boletim</li>           
                </ul>
            </div>
        </div>       
        
        <div class="title"><h5>Enviando boletim</h5></div>
        
        <div class="widget" style="border: 1px solid #d5d5d5;">
        
        </div>
    </div>