<script type="text/javascript" src="<?=$this->baseUrl()?>/public/sistema/js/wysiwyg/jquery.wysiwyg.js"></script>
<script type="text/javascript" src="<?=$this->baseUrl()?>/public/sistema/js/wysiwyg/wysiwyg.image.js"></script>
<script type="text/javascript" src="<?=$this->baseUrl()?>/public/sistema/js/wysiwyg/wysiwyg.link.js"></script>
<script type="text/javascript" src="<?=$this->baseUrl()?>/public/sistema/js/wysiwyg/wysiwyg.table.js"></script>


<script>

<?php 
if($this->erro == 1):
?>
jAlert("Mensagem não enviada! Tente novamente.","Erro!");
<?php 
endif;
?>

$(function() {
//===== WYSIWYG editor =====//

$('.wysiwyg').wysiwyg({
	iFrameClass: "wysiwyg-input",
	controls: {
		bold          : { visible : true },
		italic        : { visible : true },
		underline     : { visible : true },
		strikeThrough : { visible : false },
		
		justifyLeft   : { visible : true },
		justifyCenter : { visible : true },
		justifyRight  : { visible : true },
		justifyFull   : { visible : true },
		
		indent  : { visible : true },
		outdent : { visible : true },
		
		subscript   : { visible : false },
		superscript : { visible : false },
		
		undo : { visible : true },
		redo : { visible : true },
		
		insertOrderedList    : { visible : true },
		insertUnorderedList  : { visible : true },
		insertHorizontalRule : { visible : false },

		h1: {
		visible: true,
		className: 'h1',
		command: ($.browser.msie || $.browser.safari) ? 'formatBlock' : 'heading',
		arguments: ($.browser.msie || $.browser.safari) ? '<h1>' : 'h1',
		tags: ['h1'],
		tooltip: 'Header 1'
		},
		h2: {
		visible: true,
		className: 'h2',
		command: ($.browser.msie || $.browser.safari) ? 'formatBlock' : 'heading',
		arguments: ($.browser.msie || $.browser.safari) ? '<h2>' : 'h2',
		tags: ['h2'],
		tooltip: 'Header 2'
		},
		h3: {
		visible: true,
		className: 'h3',
		command: ($.browser.msie || $.browser.safari) ? 'formatBlock' : 'heading',
		arguments: ($.browser.msie || $.browser.safari) ? '<h3>' : 'h3',
		tags: ['h3'],
		tooltip: 'Header 3'
		},
		h4: {
		visible: true,
		className: 'h4',
		command: ($.browser.msie || $.browser.safari) ? 'formatBlock' : 'heading',
		arguments: ($.browser.msie || $.browser.safari) ? '<h4>' : 'h4',
		tags: ['h4'],
		tooltip: 'Header 4'
		},
		h5: {
		visible: true,
		className: 'h5',
		command: ($.browser.msie || $.browser.safari) ? 'formatBlock' : 'heading',
		arguments: ($.browser.msie || $.browser.safari) ? '<h5>' : 'h5',
		tags: ['h5'],
		tooltip: 'Header 5'
		},
		h6: {
		visible: true,
		className: 'h6',
		command: ($.browser.msie || $.browser.safari) ? 'formatBlock' : 'heading',
		arguments: ($.browser.msie || $.browser.safari) ? '<h6>' : 'h6',
		tags: ['h6'],
		tooltip: 'Header 6'
		},
		
		cut   : { visible : true },
		copy  : { visible : true },
		paste : { visible : true },
		html  : { visible: true },
		increaseFontSize : { visible : false },
		decreaseFontSize : { visible : false },
		},
	events: {
		click: function(event) {
			if ($("#click-inform:checked").length > 0) {
				event.preventDefault();
				alert("You have clicked jWysiwyg content!");
			}
		}
	}
});

//$('.wysiwyg').wysiwyg("insertHtml", "Sample code");

});
</script>




<!-- Content -->
    <div class="content">   
    	<!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="#">Home</a> </li>
                	<li><a href="<?php echo $this->baseUrl()?>/admin/correio/caixa">Correio eletrônico</a></li>
                	<li class="lastB">Novo correio</li>         
                </ul>
            </div>
        </div>       
        
        <div class="title"><h5>Novo Correio</h5></div>
        
        
        <!-- Form begins -->
        <form action="<?php echo $this->baseUrl()?>/admin/correio/enviaremail" class="mainForm" name="formcorreio" method="post" enctype="multipart/form-data">
        <!-- Input text fields -->
            <fieldset >
                <div class="widget first" >
	                <div class="rowElem" style="border-top: 1px solid #d5d5d5; margin-top: -10px">
	                	<label style="width: 10%">Para:</label>
	                	<div class="formRight" style="width: 85%">
	                		<?php if(count($this->objEmp)>0): ?>
	                			<input type="hidden" name="tipoenvio" value="1">
	                			<input type="hidden" name="emp" value="<?php echo $this->emp?>"> 
		                		<table style="border: 1px solid #ccc; width: 100%; ">
		                			<tr>
										<td style="padding: 5px; " colspan="3">
											<input type="checkbox" name="todos" id="todos" > <label>Todos</label>
										</td>
									</tr>	
								<?php
								$contreg = 0; 
								foreach ($this->objEmp as $listemp):
									$color = "";
									if(!filter_var(trim($listemp->EMAIL), FILTER_VALIDATE_EMAIL)):
										$color = "color: #f00";
									endif;								
									?>
									<tr>
										<td style="padding-left: 5px; <?php echo $color?>">
											<input type="checkbox" class="checktodos" name="cont_<?=$listemp->idcontato?>" > <label><?=$listemp->contato?></label>
										</td>
										<td style="vertical-align: middle; <?php echo $color?>">
											<?php echo $listemp->interesse?> 
										</td>										
										<td style="vertical-align: middle; <?php echo $color?>">
											<?php echo $listemp->EMAIL?> 
										</td>
									<?php 									
								endforeach;
								?>
								</table>	
	                		<?php else: ?>
	                			<input type="hidden" name="tipoenvio" value="0">
	                			<input type="text" name="destinatarios" class="rightDir"  title="Separe os destinatários com vírgula" />
	                		<?php endif; ?>
	                	</div><div class="fix"></div>
	                </div>
	                <div class="rowElem" >
	                	<label style="width: 10%">Assunto:</label><div class="formRight" style="width: 85%"><input type="text" name="assunto" class="rightDir" title="Assunto do e-mail" /></div><div class="fix"></div>
	                </div>
	                <div class="rowElem" >
	                	<label style="width: 10%; padding-bottom: 0px">Mensagem:</label>
	                	<div class="formRight" style="width: 97%; margin-top: -15px">
			                <div class="widget" style="border-top: 1px solid #d5d5d5;">    
		                    	<textarea class="wysiwyg" rows="5" cols="" name="mensagem"></textarea>                
		                	</div>
	                	</div>
	                	<div class="fix"></div>
	                </div>
	                <div>	
					<table id="archive" style="width: 100%">
						<tr>
							<td>
								<div class="rowElem">
			                        <label style="width: 45px">Anexo:</label> 
			                        <div class="formRight" >
			                            <input type="file" class="fileInput" id="fileInput" name="anexo1" onchange="addArchive(this)"/>
			                        </div>
			                        <div class="fix"></div>
			                    </div>			                   
							</td>
						</tr>
					</table>
					<input type="hidden" name="intarchive" id="intarchive" >
					<script type="text/javascript">
		        		var intarc = 1;
			        	function addArchive(anexo) {
			        		document.getElementById(anexo.name).value = $(anexo).val();
				        	
				        	intarc = intarc + 1;
			        		var tbCod = document.getElementById("archive").insertRow(-1);
			        		var y = tbCod.insertCell(0);

			        		y.innerHTML='<div class="rowElem"><label style="width: 45px">Anexo:</label><div class="formRight">'+
	                            '<input id="anexo'+intarc+'" style="display: inline; width: 300px;" class="file fileInput"><div style="display: inline; position: absolute; overflow: hidden;" class="feat"><input style="position: relative; height: 26px; width: 300px; display: inline; cursor: pointer; opacity: 0; margin-left: -168px;" class="fileInput" id="fileInput" name="anexo'+intarc+'" onchange="addArchive(this)" type="file"></div>'+
	                        	'</div><div class="fix"></div></div>';
			        		
			        		document.getElementById("intarchive").value = intarc;
			        		
			        	}
		        	</script> 
		        </div>
		                
	                <div class="rowElem" >
	                	<input type="submit" value="Enviar" class="greyishBtn submitForm" />
	                </div>
		                	                
	                <div class="fix"></div>
	                

                </div>
                
            
            <div class="fix"></div>
            
            </fieldset>
            
            
            
    	</form>
        
    <div class="fix"></div>
    
    </div>
    
    <script>
    	    	
    $("#todos").change(function(){
    	if(todos.checked){
    		$(".checktodos").attr("checked",true);
    	    $(".jqTransformCheckbox").addClass('jqTransformChecked');
    	}else{
    		$(".checktodos").attr("checked",false);
    	    $(".jqTransformCheckbox").removeClass('jqTransformChecked');
    	}
    })
   
    </script>