<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>ZTL Brasil - Rolamento Scania Série IV</title>
<style type="text/css">
<!--
body {
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
	background-color: #000;
	text-align:center;
}
.menu1{
	  font-family: Tahoma, Geneva, sans-serif,; font-size: 15px; color: #53595E; line-height:25px;
	  
}
}
.menu2{
	  font-family: Tahoma, Geneva, sans-serif,; font-size: 15px; color: #53595E; text-align:center;
	  
}
.text-padrao{ font-family: Tahoma, Geneva, sans-serif; font-size: 15px; 
}
}
.text-padrao2{ font-family: Tahoma,; font-size: 14px; font-size: 17px; color:#F00;
}

-->
</style>
</head>

<body> 
<table style="margin-top:20px" align="center" width="" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="50%"><img src="<?=$this->baseUrl()?>/images/hotsites/scaniaserie4/1.jpg" width="100%" height="589" /></td>
    <td width="960"><img src="<?=$this->baseUrl()?>/images/hotsites/scaniaserie4/hot_site_final.jpg" width="960" height="589" /></td>
    <td width="50%"><img src="<?=$this->baseUrl()?>/images/hotsites/scaniaserie4/2.jpg" width="100%" height="589" /></td>
  </tr>
</table>

</body>
</html>