<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>ZTL Rolamentos - www.ztlbrasil.com.br </title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link href="<?=$this->baseUrl()?>/public/sistema/imagens/ztl.ico" rel="shortcut icon" />
        <link href="../css/style.css" rel="stylesheet" type="text/css" />

<script src="../admin/javascript/alertas/jquery.js" type="text/javascript"></script>
<script src="../admin/javascript/alertas/jquery-ui.js" type="text/javascript"></script>
<script src="../admin/javascript/alertas/m2br.dialog.pack.js" type="text/javascript"></script>

<link rel="stylesheet" type="text/css" href="../admin/javascript/alertas/m2br.dialog.css" />

</head>

<body >


<!-- asdasd -->
<div id="corpoBorda">
 <div id="corpo" >
	
    <div id="topo">
      <div id="topoLogo">
            
            <a href="http://www.ztlbrasil.com.br"> <img src="../images/home_r1_c1.gif" border="0" /> </a>      </div>
      <div id="topoMenus">

      	
		
    	
  		<div id="menuTopo">
        	        	
        	<a href="empresa.php"> Empresa</a>  | 
            <a href="distribuidores.php"> Distribuidores</a> |  
            <a href="qualidade.php"> Qualidade</a> | 
           	<a href="contato.php"> Contato</a>    
     	</div>

        
      </div>
      
    </div>
	

	<script>	                	
		function abre(ln,jn,width,height,outros){
			window.open(ln,jn,"scrollbars=yes,resizable=yes,menubar=yes,status=yes,width="+width+",height="+height+","+outros);
		}
	</script>
	<style type="text/css">
<!--
.style1 {
	font-size: 9px;
	font-weight: bold;
}
.style2 {font-size: 10px}
-->
    </style>
	

	<div id="centro">
	<table border="0">
		<tr>
			<td valign="top">

		        
		            <div>
		                <div id="menuEsquerdo">
		                   <table>
		                       
		                        <tr>

		                        	<td><img src="../images/marcMenu.gif" /> <a href="/arquivosPDF/ZTL_Leve_9ED_WEB.pdf" target="_blank"> Cat&aacute;logo de Aplica&ccedil;&otilde;es </a></td>
		                        </tr>
		                        <tr>
		                        	<td><img src="../images/marcMenu.gif" /> Logo Oficial ZTL </td>
		                        </tr>
		                        <tr>

		                        	<td> &nbsp;&nbsp;&nbsp; <a href="/arquivosDownload/nova_logo_cdr.zip" target="_blank"> em Corel (.cdr) </a> </td>
		                        </tr>
		                        <tr>
		                        	<td> &nbsp;&nbsp;&nbsp; <a href="/arquivosDownload/nova_logo_jpg.zip" target="_blank"> em Jpeg (.jpg) </a> </td>

		                        </tr>
		                   </table>
		    
		                </div>
		                <div align="center">
<br />
		                    
		                <div align="center"><br><br>
		                </a><a border="0" href="http://blog.ztlrolamentos.com.br" target="_blank"><img border="0" src="../images/buton_blog.jpg"/></a><br>
		                <br>
	                  </div>
          				<div align="center">

          						<form action="addNewslatter.php" method="post">

               					  <img src="../images/news_top.jpg"/><br>
				                	<div id="acessoRestrito">
                                   	  <div align="center">
                                   	  Receba novidades e lan&ccedil;amentos da ZTL.
                                   	  
                                   	  
                                   	  
                                   	  </div>
				                		
				                		<br style="line-height:50%">
										Email:
										<input type="text" name="txtEmail" size="12" value="" id="txtEmail"/> <br><br style="line-height:50%">

										
										<input type="submit" id="submit" value="Cadastrar"/>
<br>
										<span style="font-size: 9px"><br style="line-height:50%">
				                	    </span></div>
			                	</form>




   						  <br>
		            </div>

              </div>
			<div align="center">
		                	
<?
	
	if($_SESSION['S_TIPO'] != ""){
		include("acessoRestrito/novo_menu.php");
	}else{
	
?>		                	
<!--<form id="Autenticacao" action="acessoRestrito/autenticacao.php" method="post">
-->
<form id="Autenticacao" action="../admin/auth/login" method="post">
<img src="../images/img_aba_acesso_restrito_pt_BR.gif"/><br>
<div id="acessoRestrito">
<div align="left"></div>   
Cpf / Cnpj: <input type="text"  name="cpf_cnpj" style="width: 50%" value="" id="Autenticacao_login_cpf_cnpj"/> <br><br style="line-height:50%">
Senha: <input type="password" name="senha" size="12" value="" id="Autenticacao_login_senha"/> <br><br style="line-height:50%">
<input type="submit" id="submit" value="Entrar"/><br><br style="line-height:50%">
</div>
</form> 

<?
}
?>
		                	
   	                        <a href="http://www.adobe.com/br/products/acrobat/readstep2.html" target="_blank" style="border:0"><br />
      <img border="0"src="../images/pdf_buton.jpg"/></a><br>
</div></td>
    		<td valign="top" align="center" width="100%">
        
        		
		 

		<div align="right">
		  <script type="text/javascript">
AC_FL_RunContent( 'codebase','http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,28,0','width','591','height','161','src','swf/banner','quality','high','pluginspage','http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash','movie','swf/banner' ); //end AC code
</script>

		  <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,28,0" width="591" height="161">
            <param name="movie" value="swf/banner.swf" />
            <param name="quality" value="high" />
            <embed src="../../swf/banner.swf" quality="high" pluginspage="http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" width="591" height="161"></embed>
          </object>
		</div>
	  <div>
	  	
	  	
	  		<table width="100%" align="center" style="margin-top: 0px" border="0" cellspacing="10" >  
              <tr>
                <td colspan="2" >
                <span style="color: #444; font: 15px Arial, Helvetica, sans-serif;">
                <img src="../../admin/images/banner_topo2.jpg" /> </span> 
               	</td>
              </tr>
              <tr>
              	<td width="3" align="left">
                	<img src="../../admin/images/Indicador.jpg" />
               	</td>
                <td align="left">
                	<a href="montagem"><b>ORIENTAÇÃO DE MONTAGEM DO ZTL-7, ZTL-8 e ZTL-9</b> </a>
               	</td>
              </tr>
            </table>
</div>
	  
    			
    		</td>

    	</tr>
	</table>
	</div> <!-- fim div centro -->
  
    <div id="rodape">
        <div id="botoes"> 
        	
        	
            
            <!--  <a href=""> Blog </a> -->
        </div>
    </div>
 </div><!-- div corpo -->
</div> <!-- div corpoBorda -->
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-3159130-1";
urchinTracker();
</script>
</body>
</html>
