<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/sistema/js/buscaajax/indexPainel.js"></script>
	
	<!-- Content -->
    <div class="content">    
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a></li>                        
                </ul>
            </div>
        </div>       
    
		<!-- Widgets -->
        <div class="widgets" id="painel">
           
        </div>
    
    <div class="fix"></div>
    
    </div>
    