<?php 
$usuario 	= Zend_Auth::getInstance()->getIdentity();
?>

<script src="<?=$this->baseUrl()?>/public/javascript/janelamodal.js"></script>
<script src="<?=$this->baseUrl()?>/public/javascript/jquery-1.4.min.js" type="text/javascript"></script>

<link type="text/css" rel="stylesheet" href="<?=$this->baseUrl()?>/public/css/modalestilo.css" ></link>

<script src="<?php echo $this->baseUrl(); ?>/public/javascript/buscaajax/buscaajaxamediaestoque.js"></script>


<table width="100%" border="0">
	<tr>
		<td width="70%" valign="top" >
			<table width="100%" border="0" >
				<tr>
					<td align="left" style="font-size: 13px; font-weight: bold; ">
					<img alt="Informações" src="<?php echo $this->baseUrl(); ?>/images/informacoes.jpg">
					</td>
				</tr>
				<tr>
					<td  valign="top" align="left">
					<table width="100%" align="center" border="0" cellpadding="0" cellspacing="0" style="margin-left: 22px">
						<tr>
							<td align="left" style="">
							<?php 
							
							//-- Atividades -------------------------------------------
							if($this->objAtiv==1):  ?>
								<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;<b>ATIVIDADES:</b><br>
								<?php
								$pend = 0;
								//--verifica se tem atividades pendentes------------------
								foreach ($this->objQuantp as $listqtp):
						        	if($listqtp->id_solicitado==$usuario->ID):
						        		$pend = $listqtp->qt;
						        	endif;
						       	endforeach;
								
								if($pend!=0): 
									?>
									&nbsp; &nbsp; 
									<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/painelatividades/tp/1/ids/<?php echo md5($usuario->ID);?>" >
									<U>Pendentes: <b><?php echo $pend;?></b></U>
									</a><br>									
									<?php 
								endif;
								//--verifica se tem atividades aguardando aprovacao------------------
								$countp=0;
				                foreach ($this->objMinhas as $listaminhas):
				                	if($listaminhas->status == 2) $countp++;
				                endforeach;	                
				                
				                if($countp!=0): 
									?>	
									&nbsp; &nbsp; 
									<a href="<?php echo $this->baseUrl(); ?>/admin/administracao/painelatividades/tp/2/mid/true" >
									<U>Aguardando sua aprovação: <b><?php echo $countp;	?></b></U>
									</a><br>
									<?php 
								endif;
								?><br /><?php 
							endif;
							
							//-- Logs -------------------------------------------
							if($this->objLogmail==1):  ?>
								<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;<b>FALE CONOSCO:</b><br>
								<?php
								if(!empty($this->objLogemail)): 
									foreach ($this->objLogemail as $listmail);
									?>
									&nbsp; &nbsp; <a href="#" onclick="if(document.getElementById('tb_mail').style.display=='block'){document.getElementById('tb_mail').style.display='none'}else{document.getElementById('tb_mail').style.display='block'};" ><U>Mensagens não lidas: <b><?php echo count($this->objLogemail);	?></b></U></a><br>
									<table width="80%" align="center" style="display: none" id="tb_mail">
									<?php 
									foreach ($this->objLogemail as $listmail):
										?>
										<tr>
											<td>
											<a href="http://www.ztlbrasil.com.br/public/legado/acessoRestrito/admin_fale_com_det.php?id=<?php echo $listmail->id_log_falecom; ?>" ><?php echo $listmail->nome; ?></a>
											</td>
										</tr>
										<?php 
									endforeach;
									?>
									</table>
									<?php 
								endif;
								?><br /><?php 
							endif;
							
							
							//-- Garantias -------------------------------------------
							if($this->objGarantias==1):  ?>
								<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;<b>GARANTIAS:</b><br>
								<?php
								if(!empty($this->objGaraut)): 
									foreach ($this->objGaraut as $listaut);
									?>
									&nbsp; &nbsp; <a href="#" onclick="if(document.getElementById('tb_aut').style.display=='block'){document.getElementById('tb_aut').style.display='none'}else{document.getElementById('tb_aut').style.display='block'};" ><U>Para autorização: <b><?php echo count($this->objGaraut);	?></b></U></a><br>
									<table width="80%" align="center" style="display: none" id="tb_aut">
									<?php 
									foreach ($this->objGaraut as $listaut):
										?>
										<tr>
											<td>
											<a href="<?php echo $this->baseUrl(); ?>/admin/venda/garantiasview/garantia/<?php echo md5($listaut->id); ?>" >G<?php echo substr("000000".$listaut->id,-6,6); ?></a>
											</td>
										</tr>
										<?php 
									endforeach;
									?>
									</table>
									<?php 
								endif;
								if(!empty($this->objGarana)):
									foreach ($this->objGarana as $listana);
									?>
									&nbsp; &nbsp; <a href="#" onclick="if(document.getElementById('tb_ana').style.display=='block'){document.getElementById('tb_ana').style.display='none'}else{document.getElementById('tb_ana').style.display='block'};" ><U>Para análise: <b><?php echo count($this->objGarana);	?></b></U></a><br>
									<table width="100%" cellpadding="2" cellspacing="0"  border="0" align="center" style="display: none; margin-left: 15px" id="tb_ana">
									<?php 
									foreach ($this->objGarana as $listana):
										?>
										<tr>											
											<td align="left" >
											<a href="<?php echo $this->baseUrl(); ?>/admin/venda/garantiasanalise/garantia/<?php echo md5($listana->idg); ?>" ><?=utf8_encode(substr($listana->EMPRESA,0,10)); ?></a>
											</td>
											<td align="left"  style="border-left: 1px solid;">
											<a href="<?php echo $this->baseUrl(); ?>/admin/venda/garantiasanalise/garantia/<?php echo md5($listana->idg); ?>" >G<?php echo substr("000000".$listana->idg,-6,6); ?></a>
											</td>
											<td align="center" style="border-left: 1px solid;">
											<a href="<?php echo $this->baseUrl(); ?>/admin/venda/garantiasanalise/garantia/<?php echo md5($listana->idg); ?>" ><?=$listana->qtt; ?></a>
											</td>
											<td align="right" style="border-left: 1px solid;">
											<a href="<?php echo $this->baseUrl(); ?>/admin/venda/garantiasanalise/garantia/<?php echo md5($listana->idg); ?>" ><?=substr($listana->data_chegada,8,2)."/".substr($listana->data_chegada,5,2)."/".substr($listana->data_chegada,0,4); ?></a>
											</td>
										</tr>
										<?php 
									endforeach;
							
									?>
									</table>
									<?php 
								endif;
								if(!empty($this->objGaanalci)):
									foreach ($this->objGaanalci as $listanacli);
									?>
									&nbsp; &nbsp; <a href="#" onclick="if(document.getElementById('tb_anacli').style.display=='block'){document.getElementById('tb_anacli').style.display='none'}else{document.getElementById('tb_anacli').style.display='block'};" ><U>Garantias análise concluida: <b><?php echo count($this->objGaanalci);	?></b></U></a><br>
									<table width="100%" cellpadding="1" cellspacing="0"  border="0" align="center" style="display: none; margin-left: 15px" id="tb_anacli">
									<?php 
									foreach ($this->objGaanalci as $listanacli):
										?>
										<tr>											
											<td align="left" >
											<a href="<?php echo $this->baseUrl(); ?>/admin/venda/garantiaspagcli/garantia/<?php echo md5($listanacli->idg); ?>" ><?=utf8_encode(substr($listanacli->EMPRESA,0,10)); ?></a>
											</td>
											<td align="left"  style="border-left: 1px solid;">
											<a href="<?php echo $this->baseUrl(); ?>/admin/venda/garantiaspagcli/garantia/<?php echo md5($listanacli->idg); ?>" >G<?php echo substr("000000".$listanacli->idg,-6,6); ?></a>
											</td>
											<td align="left" style="border-left: 1px solid;">
											<a href="<?php echo $this->baseUrl(); ?>/admin/venda/garantiaspagcli/garantia/<?php echo md5($listanacli->idg); ?>" ><?=$listanacli->nota_fiscal?></a>
											</td>
											<td align="right" style="border-left: 1px solid;">
											<a href="<?php echo $this->baseUrl(); ?>/admin/venda/garantiaspagcli/garantia/<?php echo md5($listanacli->idg); ?>" ><?=$listanacli->dtat?></a>
											</td>
										</tr>
										<?php 
									endforeach;
							
									?>
									</table>
									<?php 
								endif;
								?><br /><?php 
							endif;
							
							//-- Vendas -------------------------------------------
							if($this->objVendas==1):  ?>
								<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;<b>VENDAS:</b><br>
								<?php 
								if(!empty($this->objPedexp)):
									foreach ($this->objPedexp as $listpedexp);
									?>
									&nbsp; &nbsp; <a href="#" onclick="if(document.getElementById('tb_exp').style.display=='block'){document.getElementById('tb_exp').style.display='none'}else{document.getElementById('tb_exp').style.display='block'};" ><U>Para expedição: <b><?php echo count($this->objPedexp);	?></b></U></a><br>
									<table width="80%" align="center" style="display: none" id="tb_exp">
									<?php 
									foreach ($this->objPedexp as $listpedexp):
										if($this->nperfil==2):
											?>
											<tr>
												<td>
												<a href="http://www.ztlbrasil.com.br/public/legado/acessoRestrito/pedidos_orc.php?pend=true&ped=<?php echo $listpedexp->id; ?>" >Pedido <?php echo $listpedexp->id; ?></a>
												</td>
											</tr>
											<?php 
										else:
											?>
											<tr>
												<td>
												<a href="http://www.ztlbrasil.com.br/public/legado/acessoRestrito/pedidos_fix.php?ped=<?php echo $listpedexp->id; ?>" >Pedido <?php echo $listpedexp->id; ?></a>
												</td>
											</tr>
											<?php
										endif;
									endforeach;
								
									?>
									</table>
									<?php 
								endif;
								?><br /><?php 
							endif;	
							
							//-- Estoques -------------------------------------------
							if($this->objEstoque==1):  ?>
								
								<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;<b>ESTOQUE:</b><br>
								<?php 
								if(!empty($this->objEstoqzero)):
									foreach ($this->objEstoqzero as $listestz);
									?>
									&nbsp; &nbsp; <a href="#" onclick="if(document.getElementById('tb_est').style.display=='block'){document.getElementById('tb_est').style.display='none'}else{document.getElementById('tb_est').style.display='block'};" ><U>Produtos sem estoque: <b><?php echo count($this->objEstoqzero);	?></b></U></a><br>
									<table width="80%" align="center" style="display: none" id="tb_est">
									<?php 
									foreach ($this->objEstoqzero as $listestz):
										?>
										<tr>
											<td>
											<a href="<?php echo $this->baseUrl(); ?>/admin/compras/extratoprod/codproduto/<?php echo $listestz->CODIGO; ?>" >Produto código <b><?php echo $listestz->CODIGO; ?></b></a>
											</td>
										</tr>
										<?php 
									endforeach;
								
									?>
									</table>
									<?php 
								endif;
								if(!empty($this->objMedia)):
								?>
									<script type="text/javascript">
									MostraOpcaomediaestoque();
									</script>
									<div id="recHint">
									&nbsp; &nbsp; <img alt="Progresso" src="<?php echo $this->baseUrl(); ?>/images/progress.gif"> 
									</div>
								<?php 
								endif;
								?>
								<br /><?php 
							endif;
							?>
							</td>
						</tr>
					</table>
					</td>
				</tr>
			</table>
		
		</td>
		<td valign="top">
		<table width="100%">
				<tr>
					<td  align="left" style="font-size: 13px; font-weight: bold; ">
					<img alt="Informações" src="<?php echo $this->baseUrl(); ?>/images/ultimo_acesso.jpg">
					</td>
				</tr>
				<tr>
					<td valign="top">
						<table width="80%" align="center">
						<?php
						if(!empty($this->logins)): 
						foreach ($this->logins as $login):
							?>
							<tr>
								<td align="left" style="">
									<?php echo $login->data?><br>
									&nbsp; &nbsp; <i>IP: <?php echo $login->ip?></i>
								</td>
							 </tr>
							 <?php 	
						endforeach;
						endif;
						?>
						</table>										
					</td>
				</tr>
			</table>
		
		</td>
	</tr>
	<tr>
		<td colspan="2" align="left">
			<img alt="Novidades" src="<?php echo $this->baseUrl(); ?>/images/novidade.gif">
		</td>
	</tr>
	<tr>
		<td colspan="2">
		
		</td>
	</tr>
	<tr>
		<td colspan="2" align="left">
			<img alt="Videos" src="<?=$this->baseUrl()?>/images/videos.jpg" style="margin-left: -8px">
		</td>
	</tr>
	<tr>
		<td colspan="2">
		<div style="text-align: left; padding-left: 30px">
		<?php
		if(($usuario->tb_perfil_id == 1) ||
			($usuario->tb_perfil_id == 3) ||
			($usuario->tb_perfil_id == 4) ||
			($usuario->tb_perfil_id == 6) ||
			($usuario->tb_perfil_id == 11) ||
			($usuario->tb_perfil_id == 16) ||
			($usuario->tb_perfil_id == 28) ||
			($usuario->tb_perfil_id == 30)):
		?>
		<img src="<?=$this->baseUrl()?>/public/images/introducao.jpg" width="130px" style="border: 2px solid #8a8a8a; cursor: hand; cursor: pointer;" onclick="exibeModal('#jVideo')"><br />
		<b> &nbsp; &nbsp;Mercados alternativos</b>
		<?php endif; ?>
		</div>
		</td>
	</tr>
</table>

<div class="window" id="jVideo" style="width: 705px; height: 450px" >
    <span class="titulojanela" >Mercados alternativos</span>
    <a style="margin-left: 435px; color: red; font-weight: bold; font-size: 18px" href="javascript:void(0)" onclick="$('#mascara').hide(); $('.window').hide(); document.getElementById('video1').pause();" > x </a> 
    <!-- <a style="margin-left: 375px;" class="botaocancela" href="javascript:void(0)" > Fechar </a> -->
    <br />
    <span class="subtitulojanela">Video 1 (10/10/2012): Orientação para elevar as vendas</span>
    <div style="margin-top: 30px;">
    	<video width="700" controls="controls" style="border: 1px solid; " id="video1">
    		<source src="<?=$this->baseUrl()?>/public/sistema/upload/videos/1/introducao.webm" type="video/webm" />  
    		<source src="<?=$this->baseUrl()?>/public/sistema/upload/videos/1/introducao.mp4" type="video/mp4" />
    		<div>  
				Infelizmente Seu Navegador Não suporta Vídeos com Tecnologia HTML5. <br />Clique abaixo para baixar navegadores atualizados.
				<br /><br />
				<div style="width: 100px; text-align: center;" >
					<div style="float: left;">
					<a href="http://www.google.com/intl/pt-BR/chrome/" target="_blank"><img src="<?=$this->baseUrl()?>/public/images/Chrome-32.png" border="0"><br />Chrome</a>
					</div>
					<div style="float: right;">
					<a href="http://br.mozdev.org/firefox/download" target="_blank"><img src="<?=$this->baseUrl()?>/public/images/Firefox-32.png" border="0"><br />Firefox</a>
					</div>				
				</div>
			</div>
		</video>	
    </div>     
</div>

<!-- mascara para cobrir o site -->
<div id="mascara"></div>


<script type="text/javascript">
<!--
$(document).ready(function(){

	$("#mascara").click( function(){

		document.getElementById('video1').pause();
		
	    $(this).hide();
	    $(".window").hide();
	});
});

//Capturar teclas pressionadas -------------------------------
var teclaspressionadas = 0;
document.onkeyup = function(e){
   teclaspressionadas = teclaspressionadas+e.which;   

   if(teclaspressionadas == 466){  
	   win4.showCenter();
   } 
}
//-->
</script>
