<div id="siscorpo">
	<div id="sisnavegacao">
		<a href="<?=$this->baseUrl(); ?>/admin/painel">HOME</a>&nbsp; 
		<img src="<?=$this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
		<b><a href="<?=$this->baseUrl(); ?>/admin/painel/videos"><?=$this->translate->_("VIDEOS")?></a></b>
	</div>
	<div id="sistitulo">VIDEOS</div>
    <div id="sisconteudo">  
    <div style="text-align: left; ">
		<img src="<?=$this->baseUrl()?>/public/images/introducao.jpg" width="130px" style="border: 2px solid #8a8a8a; cursor: hand; cursor: pointer;" onclick="exibeModal('#jVideo')"><br />
		<b> &nbsp; &nbsp;Mercados alternativos</b>
		</div>
    </div>
 </div>