<!-- Content -->
    <div class="content">  

    <!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a> </li>
                	<li ><a href="<?php echo $this->baseUrl(); ?>/admin/compras/estoquegrupo/fil/comp">Estoque</a></li>
                	<li ><a href="<?php echo $this->baseUrl(); ?>/admin/nfe/nfe">NF-e</a></li>
                	<li class="lastB">NF-e Avulsas</li>         
                </ul>
            </div>
        </div>       
        
        <div class="title"><h5>NF-e Avulsas</h5></div>
        
        <div class="widgets" >
        	<!-- Busca -->
        	<div class="left" style="margin-top: 5px; margin-bottom: 5px" >   
	        	<?php if($this->objIns==true):?>
		    	<input type="button" class="basicBtn" onclick="window.location='<?=$this->baseUrl(); ?>/admin/nfe/nfenova'" value="Nova NF-e" />
		    	<?php endif;?>  
            </div>	        
        </div>

         <!-- Static table -->
        <?php
		if (count($this->objList) > 0):			
		?>       
        <div class="widget first">
 			<table style="width: 100%" class="tableStatic">
            	<thead>
                	<tr>
                        <td width="">NF-ee</td>
                        <td width="25%">Cliente</td>
                        <td width="15%">Data</td>
                        <td width="15%">CFOP</td>
                        <td width="">Situação</td>
                        <td width="10%">Opções</td>
                    </tr>
                </thead>
                <tbody>
	            <?php 
				foreach($this->objList as $lista):
		    	?>
				
				<tr >
	                <td style="text-align: center;" >
	                   <?="NFe".substr("000000".$lista->id,-6,6);?>
	                </td>
	                <td align="left" > 
	                   <?=($lista->empresa)?>                  
	                </td>
	                <td style="text-align: center;" >
	                   <?=substr($lista->data,8,2)."/".substr($lista->data,5,2)."/".substr($lista->data,0,4)?>                  
	                </td>
	                <td style="text-align: center;" >
	                   <?=($lista->cfop)?>                  
	                </td>
	                <td style="text-align: center;" >
	                   <? if(!empty($lista->id_nfe)) echo "EMITIDO"; else echo "CADASTRADO"?>                     
	                </td>
	                <td style="text-align: center;" >
	                	<?php if(!empty($lista->id_nfe)): ?>
                		<a href="<?=$this->baseUrl(); ?>/admin/nfe/visualizarnfe/nfe/<?=md5($lista->id_nfe)?>/tipo/avulsa"><img src="<?=$this->baseUrl(); ?>/public/sistema/imagens/icons/middlenav/magnify.png" width="16" border="0" title="Visualizar"></a>
	                	<?php else: //elseif($lista->movestoque == 1): ?>
	                		<a href="<?=$this->baseUrl(); ?>/admin/nfe/nfenovaprodout/nfe/<?=md5($lista->id)?>"><img src="<?=$this->baseUrl(); ?>/public/sistema/imagens/icons/middlenav/magnify.png" width="16" border="0" title="Visualizar"></a>
	                		<a href="#" onclick="removeCadastro('<?=$lista->id?>');" ><img src="<?=$this->baseUrl(); ?>/public/sistema/imagens/icons/middlenav/close.png" width="17" border="0" title="Remover"></a>
	                	<?php endif; /*else: 
	                		<a href="<?=$this->baseUrl(); ?>/admin/nfe/nfenovaprodout/nfe/<?=md5($lista->id)?>"><img src="<?=$this->baseUrl(); ?>/public/sistema/imagens/icons/middlenav/magnify.png" width="16" border="0" title="Visualizar"></a>
	                	 endif; */ ?>
	                	                 	
	                </td>                
	            </tr>
	            <?php  endforeach; ?>        
			</table>
		</div>	
		<div style="margin-top: 20px">
			<?php 
            if ( count($this->objList) > 0) :
            	echo $this->objList;
            endif;
            ?>
        </div>
			 <?php 
			else :
			?>
		<div style="text-align: center; margin-top: 30px">Nenhuma NFe cadastrada</div>
		<?php 
		endif;
		?>
	</div>
        
  	<script>

		function removeCadastro(id){	
			jConfirm('Tem certeza que deseja remover esta NF-e avulsa?', 'Confirme', function(r) {
				if(r==true){
					window.location='<?=$this->baseUrl()?>/admin/nfe/removenfeavulsa/nfe/'+id;
				}
			});
		}
	
		<?php if($this->tp == 'erro'){ ?>
		jAlert('Erro ao cadastrar parceiro. Entre em contato com o administrador!','Erro!');
		<?php } ?>

	</script>