<?php 
	foreach ($this->objNfe as $listNfe);		
?>
<script src="<?=$this->baseUrl()?>/public/javascript/nfe/nfecorrecao.js"></script>

<!-- Content -->
    <div class="content">  

    <!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a> </li>
                	<li ><a href="<?php echo $this->baseUrl(); ?>/admin/compras/estoquegrupo/fil/comp">Estoque</a></li>
                	<li ><a href="<?php echo $this->baseUrl(); ?>/admin/nfe/nfe">NF-e</a></li>
                	<li ><a href="<?=$this->baseUrl()?>/admin/nfe/visualizarnfe/nfe/<?=md5($listNfe->id)?>"><?="NFe".substr("000000".$listNfe->id,-6,6);?></a></li>         
                	<li class="lastB">CCe</li>
                </ul>
            </div>
        </div>       

        
        <div class="title"><h5>Nova CC-e</h5></div>

        <div class="widget first" >
            <div class="head" style="margin-top: -10px"><h5 class="iUser">Correção:</h5></div>
            <div class="body">
        		<form name="prepedido" id="prepedido" action="<?=$this->baseUrl()?>/admin/nfe/gravacorrecao" method="post" class="mainForm">
					<textarea rows="4" cols="100" name="correcao" id="correcao" style="width: 50%"></textarea>
					
					<div id="divnfe" class="widget" style="border: 1px solid #d5d5d5; padding: 10px; display: none">
				      	<div id="divbarra" >
						   <div id="barraprogresso"></div>
						</div>
						
						<div class="widgets">
				            <div id="resultadoprogresso" style="font-style: italic; width: 45%" class="left">
								Salvando dados...
							</div>
							<div id="etapaprogresso" class="right" style="width: 45%; text-align: right;">
								1/4
							</div>			
						</div>
						<div class="fix"></div>
			      	</div>
					
					
					<br /><input id="gerarNfe" type="button" value="Gerar CCe" class="greenBtn" style="margin-top: 10px" onclick="gravarDados('<?php echo $listNfe->id?>');">
				</form>
			</div>		
		</div>
	</div>	

