<div id="rodape">
	<div id="meiorodape">
		<table width="975" border="0" cellspacing="0" cellpadding="0">
	      <tr>
	        <td width="450" height="189">&nbsp;</td>
	        <td width="189">
	        <table width="169"  border="0" cellpadding="0" cellspacing="0" style="height: 122px">
	          <tr>
	            <td height="26"><span class="fonte"><strong> <?=$this->translate->_("Sobre a Ztl")?></strong></span></td>
	          </tr>
	          <tr>
	            <td height="10"><span class="fonte"><img src="<?=$this->baseUrl()?>/public/imagens/site/principal/indicador.jpg" alt="" width="7" height="10" /><a href="<?=$this->baseUrl()?>/quemsomos/oquefazemos"><?=$this->translate->_("O que Fazemos")?></a></span></td>
	          </tr>
	          <tr>
	            <td height="10"><span class="fonte"><img src="<?=$this->baseUrl()?>/public/imagens/site/principal/indicador.jpg" alt="" width="7" height="10" /><a href="<?=$this->baseUrl()?>/contato/localizacao"><?=$this->translate->_("Como nos encontrar")?></a></span></td>
	          </tr>
	          <tr>
	            <td height="10"><span class="fonte"><img src="<?=$this->baseUrl()?>/public/imagens/site/principal/indicador.jpg" alt="" width="7" height="10" /><a href="<?=$this->baseUrl()?>/contato/representantes"><?=$this->translate->_("Representantes")?></a></span></td>
	          </tr>
	          <tr>
	            <td height="10"><span class="fonte"><img src="<?=$this->baseUrl()?>/public/imagens/site/principal/indicador.jpg" alt="" width="7" height="10" /><a href="<?=$this->baseUrl()?>/contato/faleconosco"><?=$this->translate->_("Fale Conosco")?></a></span></td>
	          </tr>
	          <tr>
	            <td height="10"><span class="fonte"><img src="<?=$this->baseUrl()?>/public/imagens/site/principal/indicador.jpg" alt="" width="7" height="10" /><a href="<?=$this->baseUrl()?>/quemsomos/equipeztl"><?=$this->translate->_("Equipe ZTL")?></a></span></td>
	          </tr>
	          <tr>
	            <td height="10">&nbsp;</td>
	          </tr>
	        </table></td>
	        <td width="180"><table width="169"  border="0" cellpadding="0" cellspacing="0" style="height: 122px">
	          <tr>
	            <td height="26"><span class="fonte"><strong> <?=$this->translate->_("Produtos")?></strong></span></td>
	          </tr>
	          <tr>
	            <td height="10"><span class="fonte"> <img src="<?=$this->baseUrl()?>/public/imagens/site/principal/indicador.jpg" alt="" width="7" height="10" /><a href="<?=$this->baseUrl()?>/catalogo"><?=$this->translate->_("Catálogo online")?></a></span></td>
	          </tr>
	          <tr>
	            <td height="10"><span class="fonte"><img src="<?=$this->baseUrl()?>/public/imagens/site/principal/indicador.jpg" alt="" width="7" height="10" /><a href="<?=$this->baseUrl()?>/produtos"><?=$this->translate->_("Linha de produtos")?></a></span></td>
	          </tr>
	          <tr>
	            <td height="10">&nbsp;</td>
	          </tr>
	          <tr>
	            <td height="10">&nbsp;</td>
	          </tr>
	          <tr>
	            <td height="10">&nbsp;</td>
	          </tr>
	          <tr>
	            <td height="10">&nbsp;</td>
	          </tr>
	        </table></td>
	        <td width="180"><table width="169"  border="0" cellpadding="0" cellspacing="0" style="height: 122px">
	          <tr>
	            <td height="26"><span class="fonte"><strong> <?=$this->translate->_("Multimídia")?></strong></span></td>
	          </tr>
	          <tr>
	            <td height="10"><span class="fonte"> <img src="<?=$this->baseUrl()?>/public/imagens/site/principal/indicador.jpg" alt="" width="7" height="10" /><a href="<?=$this->baseUrl()?>/multimidia/videos"><?=$this->translate->_("Vídeos")?></a></span></td>
	          </tr>
	          <tr>
	            <td height="10"><span class="fonte"><img src="<?=$this->baseUrl()?>/public/imagens/site/principal/indicador.jpg" alt="" width="7" height="10" /><a href="<?=$this->baseUrl()?>/multimidia/noticias"><?=$this->translate->_("Notícias")?></a></span></td>
	          </tr>
	          <tr>
	             <td height="10"><span class="fonte"><img src="<?=$this->baseUrl()?>/public/imagens/site/principal/indicador.jpg" alt="" width="7" height="10" /><a href="<?=$this->baseUrl()?>/admin/hotsites/garantias" target="_blank"><?=$this->translate->_("Garantia")?></a></span></td>
	          </tr>
	          <tr>
	            <td height="10">&nbsp;</td>
	          </tr>
	          <tr>
	            <td height="10">&nbsp;</td>
	          </tr>
	          <tr>
	            <td height="10">&nbsp;</td>
	          </tr>
	        </table></td>
	        <td width="250">
	        <table width="169"  border="0" cellpadding="0" cellspacing="0" style="height: 122px">
	          <tr>
	            <td height="26"><span class="fonte"><strong><?=$this->translate->_("Downloads")?></strong></span></td>
	          </tr>
	          <tr>
	            <td height="10"><span class="fonte"> <img src="<?=$this->baseUrl()?>/public/imagens/site/principal/indicador.jpg" alt="Catalogo" width="7" height="10" /><a href="<?=$this->baseUrl()?>/public/downloads/ZTL_Leve_9ED_WEB.pdf"><?=$this->translate->_("Catálogo (pdf)")?></a></span></td>
	          </tr>
	          <tr>
	            <td height="10"><span class="fonte"><img src="<?=$this->baseUrl()?>/public/imagens/site/principal/indicador.jpg" alt="Manual logo" width="7" height="10" /><a href="<?=$this->baseUrl()?>/public/downloads/logo.zip"><?=$this->translate->_("Manual da Logo")?></a></span></td>
	          </tr>
	          <tr>
	            <td height="10"><span class="fonte"><img src="<?=$this->baseUrl()?>/public/imagens/site/principal/indicador.jpg" alt="Manual logo" width="7" height="10" /><a href="<?=$this->baseUrl()?>/montagem"><?=$this->translate->_("Dicas de montagem")?></a></span></td>
	          </tr>
	          <tr>
	            <td height="10">&nbsp;</td>
	          </tr>
	          <tr>
	            <td height="10">&nbsp;</td>
	          </tr>
	          <tr>
	            <td height="19">&nbsp;</td>
	          </tr>
	        </table></td>
	      </tr>
	      <tr>
	        <td height="33" colspan="5" class="direitos"><?=$this->translate->_("Todos os direitos reservados - ZTL do Brasil Importação Exportação &amp; Comércio Ltda")?> - 
	        	(61) 3433-7777
	        </td>
	      </tr>
	    </table>
	    <div id="redesociais" >
	    	<a href="http://www.facebook.com/profile.php?id=100001270602067" target="_blank">
	    		<img src="<?=$this->baseUrl()?>/public/imagens/site/principal/facebook.png" alt="Facebook" border="0" />
	    	</a>
	    	<a href="https://twitter.com/ztlbrasil" target="_blank">
	    		<img src="<?=$this->baseUrl()?>/public/imagens/site/principal/twiter.png" alt="twitter" border="0" />
	    	</a>
	    	<a href="http://www.youtube.com.br/ztlbrasil" target="_blank">
	    		<img src="<?=$this->baseUrl()?>/public/imagens/site/principal/you_tube.png" alt="youtube" border="0" />
	    	</a>
	    </div>
	</div>
</div>
		
</body>
</html>