<?php
//--- Menu ------------------------------------------
echo $this->translate->_("Administração");
echo $this->translate->_("Cadastro");
echo $this->translate->_("Venda");
echo $this->translate->_("ZTL Compra");
echo $this->translate->_("Outros");
echo $this->translate->_("Área do Cliente");
echo $this->translate->_("Shunkang");
echo $this->translate->_("Shuntai");

//--- SubMenu ---------------------------------------
echo $this->translate->_("Registro de Acesso");
echo $this->translate->_("Registro de Mensagens");
echo $this->translate->_("Funcionários");
echo $this->translate->_("Extrato de Estoque");
echo $this->translate->_("Novo Pedido");
echo $this->translate->_("Listar Pedidos");
echo $this->translate->_("Referência Cruzada");
echo $this->translate->_("IRV");
echo $this->translate->_("Contatos");
echo $this->translate->_("Parceiros");
echo $this->translate->_("Produtos");
echo $this->translate->_("Relatório de Produtos");
echo $this->translate->_("Lista de Produtos");
echo $this->translate->_("Fabricantes");
echo $this->translate->_("Pedidos");
echo $this->translate->_("Relatório de Vendas");
echo $this->translate->_("Metas de Compra");
echo $this->translate->_("Controle de Visitas");
echo $this->translate->_("Correio Eletrônico");
echo $this->translate->_("Hoteis");
echo $this->translate->_("Mailing");
echo $this->translate->_("Etiquetas");
echo $this->translate->_("Lista de Preços");
echo $this->translate->_("Lançamentos");
echo $this->translate->_("Pendências");
echo $this->translate->_("Alterar Senha");
echo $this->translate->_("Garantias");
echo $this->translate->_("Comparativo");
echo $this->translate->_("Veiculos");
echo $this->translate->_("Análise");
echo $this->translate->_("Catálogo");
echo $this->translate->_("Catálogo Completo");
echo $this->translate->_("Lista de Faixa de Códigos");
echo $this->translate->_("Vendas");
echo $this->translate->_("Lista de preço resumida");
echo $this->translate->_("Novos Contatos");
echo $this->translate->_("ZTL Inventário");
echo $this->translate->_("Kang Inventário");
echo $this->translate->_("Migração de Contatos");
echo $this->translate->_("Pré Pedidos");
echo $this->translate->_("Localizar Produtos");
echo $this->translate->_("Compras");
echo $this->translate->_("Transportadoras");
echo $this->translate->_("Relatório de Pendências");
echo $this->translate->_("Rascunhos");
echo $this->translate->_("Contêiners");
echo $this->translate->_("Atividades");
echo $this->translate->_("Financeiro");
echo $this->translate->_("Perfis");
echo $this->translate->_("Financeiro");
