<?php 

foreach ($this->objProd as $list);

if(!empty($list)):
	echo $list->ID;
	echo "|";
	echo $list->CODIGO;
	echo "|";
	echo str_replace(",",".",$this->vl);
	echo "|";
	echo $list->DESCRICAO;
	echo "|";
	echo $list->id_cliente_shuntai;
	echo "|";
	echo number_format(str_replace(",",".",$this->vl),3,',','.');
	echo "|";
	echo number_format(str_replace(",",".",$this->vl)*$this->qt,3,',','.');
	echo "|";
	echo $list->ID_GRUPO;
else:
	echo "erro1";
endif;
?>
