<html>
<head>
	<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl()?>/css/pedidos_imp.css" />
</head>

<body  >

<?php
//onload="window.print();"
foreach ($this->objEnt as $lisObs);
                	
?><br>
<table border="0"  width="800" class="borda_titulo" align="center">
<tr>
	<td align="left" >
	<font style="font-weight: bold; font-size: 18px;">
	ENTRADA N&ordm; E<?php echo substr("000000".$lisObs->id,-6,6)?>
	</font>
	</td>
	<td align="right" >
	<font style="font-weight: bold; font-size: 18px;">
	Data: <?php echo $lisObs->data?>
	</font>
	</td>
</tr>
</table>

<table  class="mytable" width="800" cellspacing="0" style="margin-top: 8px"  align="center">
<tr>                
	<td class="th_canto_orc" width="10%" align="center"><b>ID</b></td>
    <td class="th_orc" width="20%" align='center'><b>C&oacute;digo</b></td>
	<td class="th_orc" width="50%"" align='center'><b>Descri&ccedil;&atilde;o</b></td>
	<td class="th_orc" width="10%" align='center'><b>QT</b></td>
    <td class="th_orc" width="10%" align='center'><b>PRE&Ccedil;O</b></td>
</tr>
        <?php 
        
        foreach ($this->objList as $listProd){
        	$cor++;
        	if(($cor%2)==0) $class = 'td_orc_par';
            else $class = 'td_orc';
        	?>
        	<tr >
                <td class="<?=$class?>" align="center"><?php echo $cor?></td>
                <td class="<?=$class?>" align="left"><?php echo $listProd->CODIGO?></td>
                <td class="<?=$class?>" align="left"><?php echo htmlentities($listProd->DESCRICAO)?></td>
                <td class="<?=$class?>" align="right"><?php echo $listProd->qt?></td>
                <td class="<?=$class?>" align="right"><?php echo number_format($listProd->preco,3,",",".")?></td>
            </tr>
        		
        	<?php
        	}
        	?>
        	
     
 </table>
 
 </body>
 
</html>