<script src="<?php echo $this->baseUrl(); ?>/public/javascript/buscaajax/buscaajaxverproduto.js"></script>    
<!-- Calendarios -->
<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/javascript/calendario/dhtmlgoodies_calendar.css?random=20051112" media="screen"></LINK>
<SCRIPT type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/javascript/calendario/dhtmlgoodies_calendar.js?random=20060118"></script>
<style type="text/css">
	<!--	  
	  a.dcontexto1{
	  position:relative; 
	  font:12px arial, verdana, helvetica, sans-serif; 
	  padding:0;
	  color:#039;
	  text-decoration:none;
	  z-index:24;
	  }
	  a.dcontexto1:hover{
	  background:transparent;
	  z-index:25; 
	  }
	  a.dcontexto1 span{display: none}
	  a.dcontexto1:hover span{ 
	  display:block;
	  position:absolute;
	  width:150px; 
	  top:1em;
	  text-align:justify;
	  left:0;
	  font: 12px arial, verdana, helvetica, sans-serif; 
	  padding:5px 10px;
	  background-color: #FFF;
	  border: 1px solid #000;
	  color:#000;
	  }
	  
	  a.dcontexto2{	
	  position:relative; 
	  font:12px arial, verdana, helvetica, sans-serif; 
	  padding:0;
	  color:#039;
	  text-decoration:none;
	  z-index:24;
	  }
	  a.dcontexto2:hover{
	  background:transparent;
	  z-index:25; 
	  }
	  a.dcontexto2 span{display: none}
	  a.dcontexto2:hover span{ 
	  display:block;
	  position:absolute;
	  width:280px; 
	  top:1em;
	  text-align:justify;
	  left:0;
	  font: 12px arial, verdana, helvetica, sans-serif; 
	  padding:5px 10px;
	  background-color: #FFF;
	  border: 1px solid #000;
	  color:#000;
	  }
	  -->
</style>
<table width="100%" cellpadding="0" cellspacing="0" >
<tr>
	<td align="left">
		<table width="100%" style="margin-bottom: 4px" cellpadding="0" cellspacing="0" >
			<tr>
				<td align="left">
					<a href="<?=$this->baseUrl(); ?>/admin/painel"><?=$this->translate->_("HOME")?></a>&nbsp; 
					<img src="<?=$this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
					<a href="<?php echo $this->baseUrl(); ?>/admin/compras/estoquegrupo"><?=$this->translate->_("ESTOQUE")?></a>&nbsp;
					<img src="<?=$this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp; 
					<a href="<?=$this->baseUrl(); ?>/admin/compras/entradaest"><?=$this->translate->_("ENTRADA DE PRODUTOS")?></a>&nbsp;
					<img src="<?=$this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp; 
					<b><a href="<?=$this->baseUrl(); ?>/admin/compras/entradaestoq"><?=$this->translate->_("NOVA ENTRADA")?></a></b>
				</td>
			</tr>
		</table> 
	</td>
</tr>
<tr>
	<td align="left">
		<table border="0"  width="100%" class="borda_titulo">
			<tr>
				<td align="left" >ENTRADA DE PRODUTO</td>
			</tr>
		</table>
    </td>
</tr>
<tr>
	<td align="left">
	
	<form action="<?=$this->baseUrl()?>/admin/compras/importapednac" enctype="multipart/form-data" method="post" >
		<table width="100%" cellspacing="4" style="margin-top: 6px; border: 1px solid;" >
			<tr>
				<td align="left">
					<a href="javascript:void(0);" onclick="document.getElementById('import').style.display='block'">Importar arquivo</a>
				</td>
			</tr>
			<tr>
				<td align="left" style="display: none;" id="import">
					<input type="file" name="arquivo" size="20" style="border: 1px solid;">
					<input type="submit" value="Enviar">
				</td>
			</tr>
		</table>		
	</form>
	<?php if($this->objErro != 1): ?>
    <form action="<?=$this->baseUrl()?>/admin/compras/entradaestoqregnac" method="post">
    <table width="100%" border="0" cellspacing="0" cellpadding="0" >
    <tr>
	<td align="left">
    
    <table align="left" class="mytable" width="100%" cellspacing="0" id="txtHint" style="margin-top: 6px">
        <tr>
            <th  class="th_canto" align="center" width="20%" >
                C&Oacute;DIGO
            </th>
            <th  class="th_canto" align="center" width="20%" >
                PED
            </th>
            <th  class="th_orc" align="center" width="10%">
                QT PED
            </th>
            <th  class="th_orc" align="center" width="10%">
                QT ENT
            </th>
            <th  class="th_orc" align="center" width="10%">
                NCM
            </th>
           
            <th  class="th_orc" align="center" width="15%">
                Pre&ccedil;o
            </th>
            <th  class="th_orc" align="center" width="20%">
                total
            </th>
            
        </tr>  
        <?php 
        if(!empty($this->objProdutos)):        	                	
        	$cor=0;
        	$idverqt="";
        	$qtenvi	= $this->objQt;
        	$auxqt=0;
        	foreach ($this->objProdutos as $listaprod):
        		$cor++;
	            if(($cor%2)==0) $class = 'td_orc_par';
	            else $class = 'td_orc';
	            $idprodutos .= $listaprod->ID_PRODUTO.";";
	            
	            //--- Exibir produtos iguais de pedidos diferentes sem qt ---------------------------
	        	$qtprod = 0;
	        	$cont = $contqt = 1;
	        	foreach ($this->objProddet as $list):
	        		if(($list->ID_PRODUTO == $listaprod->ID_PRODUTO) and ($listaprod->ID_PEDIDO_COMPRA!=$list->ID_PEDIDO_COMPRA)):
	        			$cont++;
	        			$contqt++;	        				        				        		
	        		endif;	        	
	        	endforeach;	 
	        	        	
	            ?>
				<tr >
					<td  class="<?=$class?>" align="center" rowspan="<?=$cont?>" >
	                   <? 
	                   echo $listaprod->CODIGO;
	                   ?>
	                </td>
	                <td  class="<?=$class?>" align="center" >
	                   <a target="_blank" href="<?=$this->baseUrl()?>/admin/compras/pedidoscompraprod/ped/<?=md5($listaprod->ID_PEDIDO_COMPRA)?>" >
	                   	<?=$listaprod->ID_PEDIDO_COMPRA?>
	                	</a>
	                </td>
	                <td  class="<?=$class?>" align="center" >
	                   <?=$listaprod->QUANTIDADE?>
	                </td>
	                <td  class="<?=$class?>" align="center" style="font-weight: bold;">
	                <?php 
	                	$qt=0;
	                	
					   	foreach ($this->objImp as $listnfe):
							foreach ($listnfe->infNFe as $listinfo):
								foreach ($listinfo->det as $listprod):
									foreach ($listprod->prod as $produtos):
										if($produtos->cProd==$listaprod->CODIGO):
											$qt += $produtos->qCom;
										endif;
					   				endforeach;
					   			endforeach;
					   		endforeach;
					   	endforeach;
					   				
					   	$qtent=0;
					   	if($contqt>1):
					   		if($listaprod->QUANTIDADE<=$qt):
					   			$qtent = $listaprod->QUANTIDADE;
					   			$qt -= $listaprod->QUANTIDADE;
					   			$contqt--; 
					   		else:
					   			$qtent = $qt;
					   			$qt = 0;
					   			$contqt--;
					   		endif;
					   		?>
					   		<input <?php if($qtent>$listaprod->QUANTIDADE): $verqt = 1; ?>style="border: 1px solid #f00;"<?php endif;?> type="text" size="5" name="qt_<?=$listaprod->ident?>" value="<?=$qtent?>">	
					   		<?php 					   		
					   	else:
					   		$qtent = $qt;
					   		if($qtent>$listaprod->QUANTIDADE): $verqt = 1; 
						   		?>
						   		<font color="#F00"><?=$qt?></font>
						   		<?php
						   	else:
						   	 	echo $qt;						   		
					   		endif;
					   		?>
					   		<input type="hidden" name="qt_<?=$listaprod->ident?>" value="<?=$qtent?>">	
					   		<?php
					   	endif;						   	
	                ?>
	                	
	                </td>
	                <td  class="<?=$class?>" align="right" rowspan="<?=$cont?>" >
	                   <a href="#" class="dcontexto1" ><?=$listaprod->ncmcad;?>
	                   <span >	 
	                      	<table width="100%" border="0"  class="mytable">
								<tr>
									<td class="th_orc_min">II</td>
									<td class="th_orc_min">IPI</td>
									<td class="th_orc_min">PIS</td>
									<td class="th_orc_min">COFINS</td>
								</tr>
								<tr>
									<td class="td_orc_par_min" align="center"> <?=number_format($listaprod->ii)?>%</td>
									<td class="td_orc_par_min" align="center"><?=number_format($listaprod->ipicad)?>%</td>
									<td class="td_orc_par_min" align="center"><?=number_format($listaprod->pis)?>%</td>
									<td class="td_orc_par_min" align="center"><?=number_format($listaprod->cofins)?>%</td>
								</tr>								
							</table>
		               </span>
		               </a>                  
	                </td>
	               
	                <td  class="<?=$class?>" align="right" >
	                   <?=number_format($listaprod->preco,2,",",".");?>                    
	                </td>
	                <td  class="<?=$class?>" align="right" >
	                   <? 
	                   if(!empty($qtent)):
	                   		echo number_format($listaprod->preco*$qtent,2,",","."); 
	                   endif;	                   
	                   ?>
	                </td>
	                               
	            </tr>
	        	<?php 
	        	$idverqt = $listaprod->ID_PRODUTO;	        	
	        	
	        	//--- Exibir produtos iguais de pedidos diferentes sem qt ---------------------------
	        	foreach ($this->objProddet as $list):
        			if(($list->ID_PRODUTO == $listaprod->ID_PRODUTO) and ($listaprod->ID_PEDIDO_COMPRA!=$list->ID_PEDIDO_COMPRA)):
        				?>
	        			<tr >
							<td  class="<?=$class?>" align="center" >
			                    <a target="_blank" href="<?=$this->baseUrl()?>/admin/compras/pedidoscompraprod/ped/<?=md5($list->ID_PEDIDO_COMPRA)?>" >
			                   	<?=$list->ID_PEDIDO_COMPRA?>
			                	</a>
			                </td>
			                <td  class="<?=$class?>" align="center" >
			                   <?=$list->QUANTIDADE?>
			                </td>
			                <td  class="<?=$class?>" align="center"  style="font-weight: bold;" >
			                <?php 
			                	
			                	$qtent=0;
			                	if($contqt>1):
							   		if($listaprod->QUANTIDADE<=$qt):
							   			$qtent = $listaprod->QUANTIDADE;
							   			$qt -= $listaprod->QUANTIDADE;
							   			$contqt--; 
							   		else:
							   			$qtent = $qt;
							   			$qt = 0;
							   			$contqt--;
							   		endif;
							   	else:
							   		$qtent = $qt;
							   	endif;			                
			                ?>
			                  <input type="text" size="5" name="qt_<?=$list->ident?>" value="<?=$qtent?>">
			                </td>
			                <td  class="<?=$class?>" align="right" >
			                   <?=number_format($listaprod->preco,2,",",".");?>                    
			                </td>
			                <td class="<?=$class?>" align="right" >
			                   <? 
			                   	if(!empty($qtent)):
			                   		echo number_format($listaprod->preco*$qtent,2,",","."); 
			                   	endif;	                   
			                   ?>
			                </td>
			            </tr>
	        			<?php 
	        		endif;		        	
	        	endforeach;
        	endforeach;
        endif;
        ?>           
       
     </table>
     
	<input type="hidden" name="arrId" id="arrId" value="<?=$idprodutos?>" >
	<br />
	<?php if($verqt==1) ?><br /><font color="#F00">* Quantidade de entrega superior a pedida</font>
	</td>
	</tr>
	<tr>
		<td align="left">
	     	<input type="submit" value="Próximo" style="margin-top: 5px" >	     	
     	</td>	     	
	</tr>
	</table>
	</form>
	<?php else: ?>
	
	<table align="left" class="mytable" width="100%" cellspacing="0" id="txtHint" style="margin-top: 6px">
        <tr>
            <th  class="th_canto" align="center" width="" >
                CODIGO
            </th>
            <th  class="th_canto" align="center" width="" >
                QT
            </th>                      
            <th  class="th_canto" align="center" width="" >
                NCM
            </th>
            <th  class="th_canto" align="center" width="" >
                CST
            </th>
            <th  class="th_canto" align="center" width="" >
                CFOP
            </th>
            <th  class="th_canto" align="center" width="" >
                VALOR
            </th>
            <th  class="th_canto" align="center" width="" >
                TOTAL
            </th>
            
            <th  class="th_canto" align="center" width="" >
                ICMS
            </th>
            <th  class="th_canto" align="center" width="" >
                IPI
            </th>
            
        </tr>  
        <?php 
        $ptotal = 0;
		$class = "";
          /*if(!empty($this->objProd)):        	                	
        	$cor=0;
        	foreach ($this->objProd as $listaprod):*/
        	
	           
         foreach ($this->objImp as $listnfe):
		 foreach ($listnfe->infNFe as $listinfo):         
         foreach ($listinfo->det as $listprod):
         	if($class=='td_orc') $class = 'td_orc_par';
	        else $class = 'td_orc';
	        
         	foreach ($listprod->prod as $produtos);
         		$vercad = '#ff0000';
				if(!empty($this->objProdutos)):        	                	
        			foreach ($this->objProdutos as $listaprod):
        				if($listaprod->CODIGO==$produtos->cProd):
        					$vercad = "";
        				endif;
        			endforeach;
        		endif;         	

        		?>
				<tr >
					<td  class="<?=$class?>" align="center" valign="top" style="color: <?=$vercad?>">
	                	<?=$produtos->cProd?>
	                </td>
	                <td  class="<?=$class?>" align="center"  style="color: <?=$vercad?>">
	                	<?=number_format(floatval($produtos->qCom))?>
	                </td>
	                <td  class="<?=$class?>" align="center" style="color: <?=$vercad?>">
	                	<?=$produtos->NCM?>
	                </td>
	               	<td  class="<?=$class?>" align="center" style="color: <?=$vercad?>">
	                	<?
	                	foreach ($listprod->imposto as $produtosimp):
	                		foreach ($produtosimp->ICMS as $icms):
	                			foreach ($icms->ICMS10 as $icms00):	
	                				echo $icms00->orig.$icms00->CST;
	                			endforeach;
	                		endforeach;
	                	endforeach;
	                	?>	
	                </td>
	                <td  class="<?=$class?>" align="center" style="color: <?=$vercad?>">
	                	<?=$produtos->CFOP?>
	                </td>
	                <td  class="<?=$class?>" align="center" style="color: <?=$vercad?>">
	                	<?=number_format(floatval($produtos->vUnCom),2,",",".")?>
	                </td>
	                <td  class="<?=$class?>" align="center" style="color: <?=$vercad?>">
	                	<?=number_format(floatval($produtos->vUnCom)*$produtos->qCom,2,",",".")?>
	                	<?php $total += floatval($produtos->vUnCom)*$produtos->qCom?>
	                </td>
	                <td  class="<?=$class?>" align="center" style="color: <?=$vercad?>">
	                	<?
	                	foreach ($listprod->imposto as $produtosimp):
	                		foreach ($produtosimp->ICMS as $icms):
	                			foreach ($icms->ICMS10 as $icms00):	
	                				echo $icms00->vICMS;
	                				$aliqicms = $icms00->pICMS; 
	                			endforeach;
	                		endforeach;
	                	endforeach;
	                	?>
	                </td>  
	                <td  class="<?=$class?>" align="center" style="color: <?=$vercad?>">
	                	<?
	                	foreach ($listprod->imposto as $produtosimp):
	                		foreach ($produtosimp->IPI as $ipi):
	                			foreach ($ipi->IPITrib as $ipitrib):	
	                				echo $ipitrib->vIPI;
	                				$aliqipi = $ipitrib->pIPI; 
	                			endforeach;
	                		endforeach;
	                	endforeach;
	                	?>
	                </td>                            
	            </tr>
	        	<?php	 
		endforeach;
		endforeach;
		endforeach;
	            
        ?>           
       
     </table>
     <table align="left" width="100%" cellspacing="0" style="margin-top: 6px">
        <tr>
            <td  align="left" >
		    	<font color="#ff0000">* Produtos sem pedidos! Favor verificar.</font>
		    </td>
		</tr>
	</table>
	<?php endif;?>
	</td>
	</tr>
	
</table>    
     