<?php 
foreach ($this->objEntrada as $listent);
?>
<div id="siscorpo">
	<div id="sisnavegacao">
		<a href="<?=$this->baseUrl(); ?>/admin/painel"><?=$this->translate->_("HOME")?></a>&nbsp; 
		<img src="<?=$this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
		<a href="<?php echo $this->baseUrl(); ?>/admin/compras/estoquegrupo"><?=$this->translate->_("ESTOQUE")?></a>&nbsp;
		<img src="<?=$this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp; 
		<a href="<?=$this->baseUrl(); ?>/admin/compras/entradaest"><?=$this->translate->_("ENTRADA DE PRODUTOS")?></a>&nbsp;
		<img src="<?=$this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp; 
		<b><a href="<?=$this->baseUrl(); ?>/admin/compras/entradaprod/entrada/<?=md5($listent->id)?>">E<?=substr("000000".$listent->id, -6,6);?></a></b>
	</div>
	<div id="sistitulo">ENTRADA DE PRODUTO E<?=substr("000000".$listent->id, -6,6);?></div>
	<div id="sisconteudo">
		<div> 
			<table class="borda" style="width: 100%; border-spacing: 7px; margin-top: 5px">
	            <tr>
	                <td width="12%">Fornecedor:</td>
	                <td ><b><?=$listent->fornecedor?></b></td>
	                <td>Raz&atilde;o Social:</td>
	                <td><b><?=$listent->RAZAO_SOCIAL?></b></td>
	            </tr>
	            <tr>
	                <td>CPF/CNPJ:</td>
	                <td width="35%"><b><?=$listent->CPF_CNPJ?></b></td>
	                <td width="15%">RG/INSC:</td>
	                <td ><b><?=$listent->RG_INSC?></b></td>
	            </tr>
	            
	        </table>
	    </div>
	    <div>
			<table class="mytable" style="margin-top: 5px; width: 100%">
		        <tr>
		            <th  class="th_canto" style="text-align: center;" width="20%" >
		                C&Oacute;DIGO
		            </th>
		            <th  class="th_orc" style="text-align: center;" width="40%">
		                DESCRIÇÃO
		            </th>
		            <th  class="th_orc" style="text-align: center;" width="10%">
		                QT ENT
		            </th>
		            <th  class="th_orc" style="text-align: center;" width="15%">
		                Pre&ccedil;o 
		            </th>
		            <th  class="th_orc" style="text-align: center;" width="20%">
		                total
		            </th>
		        </tr>  
		        <?php 
		        if(!empty($this->objProdutos)):
		        	$qtprod = 0;
		        	$idprod = -1;
		        	
		        	$cor=0;
		        	$idverqt="";
		        	$auxqt=0;
		        	$total_pecas = 0;
		        	
		        	//-- percentual frete ------------------
		        	foreach ($this->objProdutos as $listaprod):
		        		$qtentreg = $qtpedid = 0;
			            foreach ($this->objProddet as $list):
			        		if(($list->ID_PRODUTO == $listaprod->ID_PRODUTO) and (!empty($list->qt))):
			        			$qtpedid  += $list->QUANTIDADE;
			        			$qtentreg += $list->qt;
			        		endif;
			        	endforeach;
			            
		        		$total_pedido += $listaprod->preco*$qtentreg;
		        	endforeach;
		        	
		        	$aduaneiro = $total_pedido+$listent->frete+$listent->capatazia;
		        	
		        	$qtentreg = $qtpedid = $total_pedido = $totalcofins = $totalpis = $totalii = 0;
		        	foreach ($this->objProdutos as $listaprod):
		        		
			            $qtentreg = $qtpedid = 0;
			            foreach ($this->objProddet as $list):
			        		if(($list->ID_PRODUTO == $listaprod->ID_PRODUTO) and (!empty($list->qt))):
			        			$pedidos.= '<a href="'.$this->baseUrl().'/admin/compras/pedidoscompraprod/ped/'.md5($list->ID_PEDIDO_COMPRA).'" target="_blank"><b>'.$list->ID_PEDIDO_COMPRA.'</b></a>/';
			        			
			        			$qtpedid  += $list->QUANTIDADE;
			        			$qtentreg += $list->qt;
			        		endif;
			        	endforeach;
			        
		        	endforeach;
		        	
		        	$qtentreg = $qtpedid = $total_pedido = $totalicms = $vlicms = 0;
		        	foreach ($this->objProdutos as $listaprod):
		        		$cor++;
			            if(($cor%2)==0) $class = 'td_orc_par';
			            else $class = 'td_orc';
			            $idprodutos .= $listaprod->ID_PRODUTO.";";
			            
			            //--- somar produtos iguais de pedidos diferentes ---------------------------
			            $pedidos = "";
			            $qtentreg = $qtpedid = 0;
			            foreach ($this->objProddet as $list):
			        		if(($list->ID_PRODUTO == $listaprod->ID_PRODUTO) and (!empty($list->qt))):
			        			$pedidos.= '<a href="'.$this->baseUrl().'/admin/compras/pedidoscompraprod/ped/'.md5($list->ID_PEDIDO_COMPRA).'" target="_blank"><b>'.$list->ID_PEDIDO_COMPRA.'</b></a>/';
			        			
			        			$qtpedid  += $list->QUANTIDADE;
			        			$qtentreg += $list->qt;
			        		endif;
			        	endforeach;
			            
			            ?>          
			            
						<tr >
							<td  class="<?=$class?>" style="text-align: center;"  >
								<a href="<?=$this->baseUrl();?>/cadastro/produtosvis/produto/<?=md5($listaprod->ID_PRODUTO)?>" target="_blank">
								<?=$listaprod->CODIGO?>
								</a>                  
			                </td>
			                <td  class="<?=$class?>" style="text-align: left;"  >
								<?=$listaprod->DESCRICAO?>
			                </td>
			                <td  class="<?=$class?>" style="font-weight: bold; text-align: center;">
			                   <a href="#" class="dcontexto" ><?=$qtentreg; $qttotal += $qtentreg;?>
			                   <span >	 
			                      	<table width="100%" border="0" >
										<tr>
											<td style="text-align: center;"><? if(!empty($pedidos)): echo substr($pedidos, 0,-1); else: echo $listaprod->ID_PEDIDO_COMPRA; endif;?></td>
										</tr>								
									</table>
				               </span>
				               </a>   
			                </td>	   
			                <td  class="<?=$class?>" style="text-align: right;" >
			                	<?=number_format($listaprod->preco,2,",",".")?>                    
			                </td>
			                <td  class="<?=$class?>" style="text-align: right;" >
			                   <?
			                   $totalprod = $listaprod->preco*$qtentreg;
			                   echo number_format($totalprod,2,",",".");
			                   $vtotal += $totalprod; 	                   
			                   ?>
			                </td>	                                              
			            </tr>
			        	<?php  
						
		        	endforeach;
		        endif;
		        
		        ?>        
		        <tr>		    
					<td align="left" colspan="5" class="td" valign="top" style="padding: 5px">		
						<table >
			    		<tr>
			    			<td align="left" style="width: 80px">
				    			Nota:<br />		     			
			    				<b><?=$listent->fornecimento?></b>
			    			</td>
			    			<td style="text-align: left; width: 120px">
				    			Data entrada:<br />
			    				<b><?=$listent->data?></b>
			    			</td>
			    			<td style="text-align: left;">
				    			Anexo:<br />
				    			<? if(!empty($listent->anexo)):?>
			    				<a href="<?=$this->baseUrl()?>/public/compras/anexoentradas/<?=$listent->id.".".$listent->anexo?>"><b>Arquivo.<?=$listent->anexo?></b></a>
			    				<?php endif; ?>
			    			</td>
			    		</tr>	    		
			    	</table>	
					</td>
				</tr>				     
		    	<tr>		    
					<td align="left" colspan="3" class="td_total" valign="top">								
						Observa&ccedil;&atilde;o<br>
						<b><?=$listent->obs?></b>						
					</td>
					<td align="left" colspan="2" class="td_total2" valign="top">
						Total de pe&ccedil;as<br>
						<span style="font-size: 14px; font-weight: bold; text-align: right;"><?=$qttotal?></span><br>
		                Valor Total<br>
		                <span style="font-size:14px; font-weight:bold; color:#0010e1;"><?=number_format($vtotal,2,',','.')?></span><br>                                 
					</td>
				</tr>		      
		     </table>
		</div>
		<?php if($listent->status==1): ?>
    	<div style="margin-top: 10px">
    		<input value="Inserir no estoque" type="button" onclick="if(confirm('Entrar como produtos no estoque?')){window.location='<?=$this->baseUrl()?>/admin/compras/entradaestoqueprod/entrada/<?=md5($listent->id)?>'}">
    	</div>
    	<?php endif;?>