	<script src="<?=$this->baseUrl()?>/public/sistema/js/buscaajax/comprasEstoqueresumo.js" type="text/javascript"></script>
 

	<!-- Content -->
    <div class="content">   
	<!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a> </li>
                	<li class="lastB"><a href="<?php echo $this->baseUrl(); ?>/admin/compras/estoqueresumo">Estoque</a></li>         
                </ul>
            </div>
        </div>       

        <div class="title"><h5>Estoque de produtos</h5></div>
        
        <div class="widgets" >
        	
	        <div class="widget" style="border-top: 1px solid #d5d5d5; padding: 0px 10px 10px 20px" >
				<div class="left" style="width: 30%">
					<p>Valor do estoque:</p>
					<p id="valorestoque" style="font-size: 20px"><img src="<?php echo $this->baseUrl()?>/public/sistema/imagens/loaders/loader6.gif" alt="Carregando"></p>
					<p>Quantidade:</p>
					<p id="quantidade" style="font-size: 20px"><img src="<?php echo $this->baseUrl()?>/public/sistema/imagens/loaders/loader6.gif" alt="Carregando"></p>
					<p>Compras:</p>
					<p id="compras" style="font-size: 20px"><img src="<?php echo $this->baseUrl()?>/public/sistema/imagens/loaders/loader6.gif" alt="Carregando"></p>
					
				</div>
				<div class="right" style="width: 65%">
					<div class="widget" id="tabelaHistorico" style="display: none">
						<table style="width: 100%" class="tableStatic" id="resumo">
		            	<thead>
		                	<tr>
		                        <td width="">Data</td>
		                        <td width="">Valor do estoque</td>
		                        <td width="">Quantidade</td>
		                        <td width="">Compra</td>                        
		                    </tr>
		                </thead>
		                <tbody></tbody>
		                </table>
		                <div id="carregando" style="padding: 5px"><img src="<?php echo $this->baseUrl()?>/public/sistema/imagens/loaders/loader6.gif" alt="Carregando"> <i>Aguarde, isto pode demorar alguns minutos...</i></div>
					</div>
					<div id="btnBusca" >
						<a href="#" title="" style="margin-top: 5px;"  class="btnIconLeft mr10" onclick="buscaResumo();"><img src="<?php echo $this->baseUrl()?>/public/sistema/imagens/icons/dark/add.png" alt="" class="icon" /><span>Mais</span></a>
					</div>
				</div>
				
				<div class="clear"></div>
			</div>
	        
		</div>
		
   </div>
   
   <script>
   $(document).ready(function() {
	   buscaResumototal();
	   //buscaResumo();
   });
	
   </script>