<?php 

if($this->objTipo==1):
	header("Content-type: application/vnd.oasis.opendocument.spreadsheet");
	header("Content-Disposition: attachment; filename=Estoque.ods");
else:
	header("Content-type: application/msexcel");
	header("Content-Disposition: attachment; filename=Estoque.xls");
endif;
?>
<table width="100%" cellpadding="0" cellspacing="0" >
<tr>
	<td align="left" >ESTOQUE DE PRODUTOS</td>    
</tr>
<tr>
	<td align="left">
	<div style="margin: 5px 0px 8px">
	<?php 
	if(!empty($this->objFil)):
		echo ($this->objFil);
	endif;
	?>	
	</div>
	</td>
</tr>
<tr>
	<td align="left">	 			
		<table >
			<tr >		             	
		    	<td align='center'><b>C&Oacute;DIGO</b></td>
		        <td align='center'><b>DESCRI&Ccedil;&Atilde;O</b></td>
		        <td align='center'><b>CUSTO</b></td>
		        <td align='center'><b>ESTOQUE</b></td>		        	                
		    </tr>
	        <?php 	        
		        foreach($this->objProdutos as $listProd):
		        	if($listProd->tipo=="COMPRA") $tipo = "COMPRA N&ordm; ".$listProd->id_atualizacao;
	            	?>
        			<tr >
		                <td align="left"><?php echo $listProd->CODIGO?></td>
		                <td align="left"><?php echo htmlentities($listProd->DESCRICAO)?></td>
		                <td align="left"><?php echo number_format($listProd->custoproduto,2,",",".");?></td>
		                <td align="center"><?php if(!empty($listProd->qt_atual)){ echo $listProd->qt_atual;}else echo 0;?></td>			                
		            </tr>        				
		        	<?php  
		        endforeach;			
			?>
	    </table>
	 </td>
</tr>
</table>
