<?php 
if($this->objTipo==1):
	header("Content-type: application/vnd.oasis.opendocument.spreadsheet");
	header("Content-Disposition: attachment; filename=Extrato_".$this->objCod.".ods");
else:
	header("Content-type: application/msexcel");
	header("Content-Disposition: attachment; filename=Extrato_".$this->objCod.".xls");
endif;
?>
<table border="0"  width="100%" class="borda_titulo">
<tr>
	<td align="left" >EXTRATO DE MOVIMENTA&Ccedil;&Atilde;O <?=strtoupper($this->objCod)?></td>
</tr> 
<tr>
	<td align="left">	
      <?php 
      
      if (count($this->objList) <= 0) :
			echo "<br><b>Produto sem movimentação!</b>";
	  else:
	  ?>
      		
		<table width="100%"  align="left" class="mytable" id="myTable">
			<tr bgcolor="">
		    	<td class="th_canto" width="30%" align='center'><b>TIPO</b></td>
		        <td class="th_pedido" width="18%"" align='center'><b>DATA</b></td>
		        <td class="th_pedido" width="10%" align='center'><b>QT</b></td>
		        <td class="th_pedido" width="15%" align='center'><b>ESTOQUE</b></td>
		        <td class="th_pedido" width="22%" align='center'><b>USU&Aacute;RIO</b></td>
		     </tr>
			        <?php 
			        	
				        if ( count($this->objList) > 0) :
		    			foreach($this->objList as $listProd):				        	
		        			?>
		        			<tr >
				                <td align="left"><?php 
				                if(strripos($listProd->tipo, "FABRICA")!==false):
				                	?>FABRICAÇÃO N&ordm; F<?php echo substr("000000".$listProd->id_atualizacao,-6,6); 
				                elseif(strripos($listProd->tipo, "VENDA CANCELA")!==false):
				                	?>VENDA CANCELADA N&ordm; <?php echo $listProd->id_atualizacao;				                	
				                elseif(strripos($listProd->tipo, "VENDA")!==false):
				                	?>VENDA N&ordm; <?php echo $listProd->id_atualizacao;
				                elseif(strripos($listProd->tipo, "SIAC")!==false):
				                	echo utf8_encode($listProd->tipo)." N&ordm; ".$listProd->id_atualizacao;
				                elseif(strripos($listProd->tipo, "AJUSTE CANCELADO")!==false):
				                	?>AJUSTE CANCELADO A<?php echo substr("000000".$listProd->id_atualizacao,-6,6); 
				                elseif(strripos($listProd->tipo, "AJUSTE")!==false):
				                	?>AJUSTE A<?php echo substr("000000".$listProd->id_atualizacao,-6,6); 
				                elseif(strripos($listProd->tipo, "COMPRA")!==false):
				                	?>ENTRADA E<?php echo substr("000000".$listProd->id_atualizacao,-6,6); 
				                elseif(strripos($listProd->tipo, "GARANTIA CANCELA")!==false):
				                	?>GARANTIA CANCELADA G<?php echo substr("000000".$listProd->id_atualizacao,-6,6);
				               elseif(strripos($listProd->tipo, "GARANTIA")!==false):
				                	?>GARANTIA G<?php echo substr("000000".$listProd->id_atualizacao,-6,6);
				                elseif(strripos($listProd->tipo, "NFe Avulsa")!==false):
				                	?>NFe Avulsa NFe<?php echo substr("000000".$listProd->id_atualizacao,-6,6);
				                endif;
				                ?> 
				                </td>
				                <td align="center"><?php echo $listProd->dt_at?></td>
				                <td align="center"><?php echo $listProd->qt_atualizacao?></td>
				                <td align="center"><?php echo $listProd->qt_atual?></td>
				                <td align="center"><?php echo htmlentities($listProd->nome)?></td>
				            </tr>
		        				
				        	<?php  
				        endforeach;
					endif;   
					?>
	        </table>
	        <?php 
	        endif;
	        ?>
	   </td>
</tr>

</table>
 
