
<body  onload="document.prepedido.codigo.focus();">
<script src="<?php echo $this->baseUrl(); ?>/public/javascript/buscaajax/buscaajaxfabrica.js"></script>    
<script type="text/javascript">

function deleteRow(i,id){
    document.getElementById('txtHint').deleteRow(i);
    var arrId = document.getElementById('arrId').value;
	document.getElementById('arrId').value = arrId.replace(id+";","");

}

</script>

<!-- Content -->
    <div class="content">   
	<!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a> </li>
                	<li ><a href="<?php echo $this->baseUrl(); ?>/admin/compras/estoqueresumo">Estoque</a></li>
                	<li ><a href="<?php echo $this->baseUrl(); ?>/admin/compras/fabrica">Fábrica</a></li>
                	<li class="lastB">Nova montagem</li>         
                </ul>
            </div>
        </div>       
        
        <div class="title"><h5>Fábrica</h5></div>
        
        <div class="widgets" >
				
			<form action="<?php echo $this->baseUrl(); ?>/admin/compras/gerakit" method="post" name="prepedido" id="prepedido" class="mainForm">
		    <input type="hidden" name="permissao" id="permissao" value="<?php echo $this->objNeg?>">
		    <input type="hidden" name="arrId" id="arrId">
		        
		    <div class="widget">
 			<table style="width: 100%" class="tableStatic" id="txtHint">
            	<thead>
                	<tr>
                        <td width="15%">Código</td>
                        <td width="15%">Qt</td>
                        <td width="">Descrição</td>
                        <td width="15%">&nbsp;</td>
                    </tr>
                </thead>
                <tbody>
                	<tr>
		            <td  class="td" align="center"  >
		                <input type="text"  size="7" name="codigo" id="codigo" style="width: 70px" onkeydown="if (event.keyCode == '13'){ return false; }; document.getElementById('resultado').innerHTML = '';">
		            </td>
		            <td  align="center" >
		            	<input type="text" size="5" name="qt" id="qt" style="width: 50px" onkeydown="if (event.keyCode == '13'){ return false; }; " onclick="document.getElementById('resultado').innerHTML = '';" onblur="buscaprod();">	
		           	</td>	
		            <td  class="td" align="left" colspan="2" >
		            	 <div id="resultado" style="color:#FF0000; font-weight: bold;"></div>
		            </td>
		            
		        </tr>
		        </tbody>
		     </table>
		     </div>
		     <script>
		                  
		                  function buscaprod(){
		                	  var cod = document.getElementById('codigo').value;
		                	  var qt  = document.getElementById('qt').value;
		                	  
		                	  if(cod==''){
		                    	  document.getElementById('resultado').innerHTML = 'Digite o c&oacute;digo!';
		                    	  
		                	  }else if(qt==''){
		                		  document.getElementById('resultado').innerHTML = 'Digite a quantidade!';
		                		  
		                	  }else{
		                		  MostraOpcao(cod,qt);
		                		  document.getElementById('codigo').value = "";
		                    	  document.getElementById('qt').value = "";
		                    	
		                	  }
		                  }
						 
			</script>
		     
		     <div style="margin-top: 10px">
		     	Observa&ccedil;&atilde;o:<br>
		        <textarea rows="3"  cols="50" style="width: 350px; margin-bottom: 10px" name="obs"></textarea><br>        
		     	<input type="submit" value="Salvar" class="greenBtn">
			 </div>
		     
		     
			</form>
     </div>
</div>