 <link href="<?php echo $this->baseUrl(); ?>/css/pedidos_imp.css" rel="stylesheet" type="text/css" />
            <table align="center" border="0"  width="800" style="background-color:#ebebeb;	border-bottom:1px solid #cbcbcb; border-top:1px solid #cbcbcb;" >
            <tr>
               <td align="left" >LISTA DE PRODUTOS PEDIDOS</td>
                <td align="right">
                &nbsp;
                </td>
            </tr>
            </table>
      <br>
			<table  align="center" width="800"  align="left" class="mytable" id="myTable">
		            <tr >
		             	
		                <td style="border: 1px solid #ebebeb; background: #ebebeb;" class="th_canto" width="10%" align="center"><b>ORDEM</b></td>
		                <td style="border: 1px solid #ebebeb; background: #ebebeb;" width="22%" align='center'><b>C&Oacute;DIGO</b></td>
		                <td style="border: 1px solid #ebebeb; background: #ebebeb;" class="th_pedido" width="18%"" align='center'><b>PEDIDO</b></td>
		                <td style="border: 1px solid #ebebeb; background: #ebebeb;" class="th_pedido" width="15%" align='center'><b>QT PED</b></td>
		                <td style="border: 1px solid #ebebeb; background: #ebebeb;" class="th_pedido"  width="20%" align='center'><b>PREV EMBARQUE</b></td>
		                
		            </tr>
			        <?php 
			        
			        if($this->objPage>0) $cor = ($this->objPage-1)*35;
			        	
			        	
				        if ( count($this->objProdutos) > 0) :
		    			foreach($this->objProdutos as $listProd):
				        
		        			$cor++;
		        			if(($cor%2)==0) $class = 'tdpar';
			            	else $class = 'td';
			            	
			            	if($listProd->QT_ENT > $listProd->QUANTIDADE) $qt = $listProd->QUANTIDADE;
			            	else $qt =  $listProd->QUANTIDADE - $listProd->QT_ENT;
		        			?>
		        			<tr >
				                <td class="<?=$class?>" align="center"><?php echo $cor?></td>
				                <td class="<?=$class?>" align="left"><?php echo $listProd->CODIGO?></td>
				                <td class="<?=$class?>" align="center"><?php echo substr("000000".$listProd->ped,-6,6)?></td>
				                <td class="<?=$class?>" align="center"><?php echo $qt?></td>
				                <td class="<?=$class?>" align="center"><?php echo $listProd->dt_entrega?></td>
				            </tr>
		        				
				        	<?php  
				        endforeach;
					endif;   
					?>
	        </table>
	    