<script src="<?=$this->baseUrl()?>/public/javascript/buscaajax/buscaajaxgrupofor.js" type="text/javascript"></script>
<script src="<?=$this->baseUrl()?>/public/javascript/buscaajax/buscaajaxsubgrupo.js" type="text/javascript"></script> 

<table width="100%" style="margin-bottom: 4px" cellpadding="0" cellspacing="0" >
	<tr>
		<td align="left">
			<a href="<?php echo $this->baseUrl(); ?>/admin/painel"><?=$this->translate->_("HOME")?></a>&nbsp; 
			<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
			<a href="<?php echo $this->baseUrl(); ?>/admin/compras/pedidoscompra"><?=$this->translate->_("PEDIDOS DE COMPRA")?></a>&nbsp;
			<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
			<b><a href="<?php echo $this->baseUrl(); ?>/admin/compras/relatoriovendas"><?=$this->translate->_("NOVO PEDIDO")?></a></b>
		</td>
	</tr>
</table>

<table width="100%" class="borda_titulo">
	<tr>
		<td align="left"><?=$this->translate->_("NOVO PEDIDO")?></td>
	</tr>
</table>
<table width="100%" cellpadding="0" cellspacing="0" style="margin-top: 5px">
<tr>
	<td>
		<form action="<?php echo $this->baseUrl(); ?>/admin/compras/relatoriovendascurva" method="post" name="busca" id="busca">
		<table width="100%" border="0" style="margin-bottom: 8px; display: block; border: 1px solid #000; padding: 8px; " id="tabela">
	    <tr>
	    	<td align="left" colspan="3"  width="400">
		    	Fornecedor:<br>
				<select name="buscafor" id="buscafor" style="width: 200px" onchange="Buscagruposfornecedor(this.value);">
					<option value="0"><?=$this->translate->_("Todos")?></option>
					<?php foreach ($this->objFor as $listfor): ?>
						<option <?php if($this->objFsel==$listfor->ID) echo 'selected="selected"'?>  value="<?=$listfor->ID?>"><?=$listfor->EMPRESA?></option>
					<?php endforeach; ?>
				</select>								
	    	</td>
		</tr>
		<tr>
	    	<td align="left" width="200">
				Grupos de Venda:<br>
				<select name="grupovenda" id="grupovenda" onchange="Mostrasubgrupos(this.value,3);" style="width: 180px; text-transform: uppercase;">
					<option value="0">SELECIONE</option>
					<?php foreach ($this->objGrupov as $listG): ?>
					<option value="<?php echo $listG->id?>"><?php echo $listG->descricao?></option>
					<?php endforeach;?>					
				</select>									
			</td>
			<td align="left" colspan="2">
			<div id="subgrupo" align="left">
			</div>
			</td>	
		</tr>		
		<tr>
	    	<td align="left"  >
	    		Grupos de Compra<br>
				<select name="buscagrupo" id="buscagrupo" style="width: 180px; text-transform: uppercase;">
					<option value="0"><?=$this->translate->_("SELECIONE")?></option>
					<?php foreach ($this->objGrupo as $list): ?>
						<option value="<?php echo $list->id?>" 
						<?php if($this->objGselec==$list->id) echo 'selected="selected"';?>  ><?php echo substr($list->purchasing,0,20)?></option>
					<?php endforeach; ?>
				</select>
				
			</td>
			<td align="left" >&nbsp;
			</td>
	    	<td align="left" >
	    		Período<br>
	    		<select name="periodo" id="periodo" >
	    			<?php 
	    			if((empty($this->objQtmes))|| ($this->objQtmes==6)) $sel6 = 'selected="selected"';
	    			elseif($this->objQtmes==1) $sel1 = 'selected="selected"';
	    			elseif($this->objQtmes==2) $sel2 = 'selected="selected"';
	    			elseif($this->objQtmes==3) $sel3 = 'selected="selected"';
	    			elseif($this->objQtmes==4) $sel4 = 'selected="selected"';
	    			?>
	    		
					<option value="1" <?=$sel1?>>1 Mês</option>
					<option value="2" <?=$sel2?>>2 Meses</option>
					<option value="3" <?=$sel3?>>3 Meses</option>
					<option value="4" <?=$sel4?>>4 Meses</option>
					<option value="6" <?=$sel6?>>6 Meses</option>
				</select>
				<input type="submit"  value="<?=$this->translate->_("Pesquisar")?>" >
				
	    	</td>
	    	   	
		</tr>
	    		
		</table> 	
	 
	</form>
	</td>
</tr>
<tr>
	<td align="left">        
        <?php           
		if (count($this->objList) > 0) :
		?>
		<table align="left" class="mytable"  width="554" cellspacing="0">
	    	<tr>
	            <th  class="th_canto_orc" align="center" width="15%">
	                <?=$this->translate->_("CÓDIGO")?>
	            </th>
	            <?php 
	            for($i=$this->objQtmes;$i>0;$i--):
	            ?>
	            <th  class="th_orc" align="center" width="10%">
	                <?=date('m/Y', mktime(0, 0, 0, date("m") - $i, 1, date("Y")));?>
	            </th>
	            <?php endfor; ?>
	            <th  class="th_orc" align="center" width="10%">
	                <?=$this->translate->_("TOTAL")?>
	            </th>
	        </tr>		       
		<?php 
			
		$cor=0;
		$idprod = "";
    	foreach($this->objProd as $lista):		    		
	    	$cor++;
            if(($cor%2)==0) $class = 'td_orc_par';
            else $class = 'td_orc';
            ?>
			<tr >
                <td  class="<?=$class?>" align="center" >
                   <a href="<?=$this->baseUrl();?>/admin/cadastro/produtoscad/produto/<?=md5($lista->idproduto)?>" target="_blank">
					<?=$lista->CODIGO?>
					</a>
                </td>
	            <?php
	            $totalqtprod = 0;
	            for($i=$this->objQtmes;$i>0;$i--):
	            ?>
	            <td  class="<?=$class?>"  style="text-align: center;">
                   	<?php
                   	$qtvenda = 0;
					foreach ($this->objList as $vendas):
                   	   	$mes = date('m', mktime(0, 0, 0, date("m") - $i, 1, date("Y")));
                   	   	if($lista->ID == $vendas->idproduto):
							if($mes==$vendas->mes):
						   		$qtvenda = $vendas->qtvenda; 
						   	endif;
					   	endif;
					endforeach;						
					echo $qtvenda;
					$totalqtprod += $qtvenda;
				   	?>		               
                </td>
	            <?php 
	            endfor; 	            
            ?>
            	<td  class="<?=$class?>" style="text-align: center;">
                	<?=$totalqtprod?>
                </td>
            </tr>	            
			<?php  
		endforeach;
		?>
		</table>
		<?php 
		else:
			if(!empty($this->objFsel)):
			?>
			Nenhum produto encontrado!
			<?php 
				endif;
         	endif;

         	?>
		</td>
	</tr>
 </table>
		
	