<!-- Calendarios -->
<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/javascript/calendario/dhtmlgoodies_calendar.css?random=20051112" media="screen"></LINK>
<SCRIPT type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/javascript/calendario/dhtmlgoodies_calendar.js?random=20060118"></script>

<table width="100%" cellpadding="0" cellspacing="0">
<tr>
	<td>
	<table width="100%" style="margin-bottom: 4px" cellpadding="0" cellspacing="0" >
		<tr>
			<td align="left">
				<a href="<?php echo $this->baseUrl(); ?>/admin/painel"><?=$this->translate->_("HOME")?></a>&nbsp; 
				<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
				<a href="<?php echo $this->baseUrl(); ?>/admin/compras/pedidoscompra"><?=$this->translate->_("PEDIDOS DE COMPRA")?></a>&nbsp;
				<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
				<b><a href="<?php echo $this->baseUrl(); ?>/admin/compras/relatoriovendas"><?=$this->translate->_("NOVO PEDIDO")?></a></b>
			</td>
		</tr>
	</table>
	</td>
</tr>
<tr>
	<td>
	<table width="100%" class="borda_titulo">
		<tr>
			<td align="left"><?=$this->translate->_("NOVO PEDIDO")?></td>
		</tr>
	</table>
	</td>
</tr>
<tr>
	<td>
	<form action="<?=$this->baseUrl()?>/admin/compras/gerarpedido" name="pedido" method="post" >
	<?php 
	$verblock = 0;
	foreach ($this->objFor as $listcli):
	?>
		<table width="100%"  align="left" class="mytable" id="myTable" style="margin: 5px 0px 5px">
			<tr bgcolor="" >             	
                <td class="th_canto" width="10%" align="left" colspan="7"><b><?=$listcli->EMPRESA;?></b></td>
            </tr>
            <tr bgcolor="">             	
                <td class="th_canto" width="10%" align="center"><b>ID</b></td>
                <td class="th_pedido" width="20%" align='center'><b>C&oacute;digo</b></td>
                <td class="th_pedido" width="50%"" align='center'><b>Descri&ccedil;&atilde;o</b></td>
                <td class="th_pedido" width="10%" align='center'><b>QT</b></td>
                <td class="th_pedido" width="10%" align='center'><b>Moeda</b></td>
                <td class="th_pedido" width="10%" align='center'><b>PRE&Ccedil;O</b></td>
                <td class="th_pedido" width="10%" align='center'><b>Total</b></td>
            </tr>
	        <?php 	
	        	$cor=0;
	        	$qttotal = $vltotal = 0;
	        	$vermoeda = $vervl = "";	        
		        foreach ($this->objProdutos as $listprod):
		        	if($listprod->ID_CLIENTE_FORNECEDOR==$listcli->ID):
			        	$cor++;
	        			if(($cor%2)==0) $class = 'tdpar';
		            	else $class = 'td';
		            	
		            	if($listcli->moeda!=$listprod->MOEDA):
		            		$vermoeda = '<span style="color: #FF0000">*</span>';
		            		$verblock = 1;
		            	endif;
		            	
		            	if($listprod->CUSTO_VALOR=='0'):
		            		$vervl	= '<span style="color: #FF0000">**</span>';;
		            		$verblock = 1;
		            	endif;
		            	
		            	
	        			?>
	        			<tr >
			            <td class="<?=$class?>" align="center">
			            <?=$cor?>
			            <input type="hidden" name="prod_<?=$listprod->ID?>" value="<?=$this->objDados['prod_'.$listprod->ID]?>">
			            </td>
		                <td class="<?=$class?>" align="left">
		                 <a href="<?=$this->baseUrl();?>/admin/cadastro/produtosvis/produto/<?=md5($listprod->ID)?>" target="_blank">
						<?php echo $listprod->CODIGO?>
						</a> 
			            </td>
		                <td class="<?=$class?>" align="left"><?=($listprod->DESCRICAO)?></td>
		                <td class="<?=$class?>" align="center"><?=$this->objDados['prod_'.$listprod->ID]?></td>
		                <td class="<?=$class?>" align="center"><?=$listprod->MOEDA.$vermoeda?></td>
		                <td class="<?=$class?>" align="center"><?=number_format($listprod->CUSTO_VALOR,3,",",".").$vervl?></td>
		                <td class="<?=$class?>" align="center"><?=number_format(($this->objDados['prod_'.$listprod->ID]*$listprod->CUSTO_VALOR),3,",",".")?></td>
			            </tr>        				
		        	<?php
		        	$qttotal	+= $this->objDados['prod_'.$listprod->ID];
		        	$vltotal	+= $this->objDados['prod_'.$listprod->ID]*$listprod->CUSTO_VALOR;
		        	endif;
	        	endforeach;
        	?>
        	<tr >
	            <td class="tdpar" align="left" colspan="7">
	            Data entrega:
	              <input size="10" name="data_entrega_<?=$listcli->ID?>" class="borda_text" maxlength="10" onclick="displayCalendar(this,'dd/mm/yyyy',this)" type="text" onKeyDown="Mascara(this,Data);" onKeyPress="Mascara(this,Data);" onKeyUp="Mascara(this,Data);">
	              &nbsp;  &nbsp;  &nbsp; 
                Aceita entrega parcial? 
	                <select name="acc_<?=$listcli->ID?>" class="borda_input">
		            <option value="YES">SIM</option>
					<option value="NO" selected="selected">NÃO</option>	            
					</select> 
                </td>
	            </tr>
			 <tr>		    
				<td colspan="5" class="td_total" align="left">					
					Observações<br>
					<textarea rows="3" cols="60" name="obs_<?=$listcli->ID?>" class="borda_text"></textarea>					
				</td>
				<td colspan="2" class="td_total2" align="left" valign="top">
					<br>
					Total de peças<br>
					 <span style="font-size: 14px; font-weight: bold; text-align: right;"><?=$qttotal?></span><br>
                    Valor Total:<br>
                    <span style="font-size: 14px; font-weight: bold; color: rgb(0, 16, 225);"><?=number_format($vltotal,3,",",".")?></span><br>                    
				</td>
			</tr>        	
        </table>
        	
        <table align="left" width="100%" cellpadding="0" cellspacing="0">
        	<tr>
        		<td align="left" style="color: #FF0000">
        		<?php 
        		if($vervl!=""):
        			echo "**Produto sem valor cadastrado!<br />";
        		endif;
        		if($vermoeda!=""):
        			echo "*Moeda do produto diferente da moeda do fornecedor!<br />";
        		endif;
        		        		
        		?>
        		</td>
        	</tr>
        </table>
                
    <?php
    $for	.= $listcli->ID.";"; 
    endforeach;    
    ?>
    <input type="hidden" name="fornecedores" value="<?=$for?>">	
    </form>         
	</td>
</tr>
<tr>
	<td align="left">
	<br />
	<input <?php if($verblock==1): ?> disabled="disabled" <?php endif;?> type="button" value="Gerar Pedidos" onclick="verificaFormgerar();" />	
	
	<script type="text/javascript">
		function verificaFormgerar(){
			var verific = 1;
			<?php 
			foreach($this->objFor as $lista):
				?>
				if(document.pedido.data_entrega_<?=$lista->ID?>.value==""){
					verific = 0;							
				}
				<?php 
			endforeach;
			?>
	
			if(verific==0){
				alert('A data de entregua não pode ficar em branco!');
				return false;
			}else{
				document.pedido.submit();
			}
			return false;
		}
	</script>
	</td>
</tr>
</table>

