<script src="<?=$this->baseUrl()?>/public/sistema/js/buscaajax/buscaGenerica.js" type="text/javascript"></script>
<script src="<?=$this->baseUrl()?>/public/sistema/js/printElement/jquery.printElement.js"></script>

<script type="text/javascript">
	$(document).ready(function() {
    	$("#simplePrint").click(function(){
			$('#resultado').printElement();
		});
	});
</script>

<!-- Content -->
	<div class="content">   

<!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a> </li>
                	<li ><a href="<?=$this->baseUrl()?>/admin/relatorios">Relatórios</a></li>         
                	<li class="lastB">DRE</li>
                </ul>
            </div>
        </div>       

        <div class="title"><h5>Demostração do Resultado do Exercício</h5>
	        <div style="float: right; padding: 10px">
				<a href="#" id="simplePrint"><img src="<?=$this->baseUrl()?>/public/sistema/imagens/icons/middlenav/printerwhite.png" title="Imprimir" border="0" width="18"></a>
			</div>
        </div>
        
        <div class="widgets" >
			<div class="widget" style="margin-top: 0px; margin-top: 5px; padding: 10px; border-top: 1px solid #d5d5d5;" >
			<form action="<?=$this->baseUrl()?>/admin/relatorios/financeirodre" method="post" name="busca" id="busca" class="mainForm">
				<div style="width: 85px;  float: left;">			
			    	Dt ini:<br>
			    	<input type="text" size="8" name="dataini" id="dataini" class="data datepicker">
			    </div>
				<div style="width: 150px; float: left;">
					Dt fim:<br>
					<input type="text" size="8" name="datafim" id="datafim" class="data datepicker">
					<input type="button" value="Gerar" class="blueBtn" style="margin-left: 5px" onclick="geraRelatorio();">
				</div> 
			</form>
			<div class="clear"></div>
			</div>
			
			<div class="widget first" style=" border: 1px solid #d5d5d5; padding: 20px; display: none" id="resultado"></div>
			
		</div>		
	</div>
	
	<script>
	function geraRelatorio(){
		$('#resultado').css({display:'block'});
		$('#resultado').html('<img src="<?php echo $this->baseUrl()?>/public/sistema/imagens/loaders/loader6.gif" alt="Carregando"> <i>Aguarde, gerando relatório...</i>');
		var dtini = $('#dataini').val();
		var dtfim = $('#datafim').val();

		dtini = dtini.replace('/','-');
		dtini = dtini.replace('/','-');
		dtfim = dtfim.replace('/','-');
		dtfim = dtfim.replace('/','-');
		
		buscaGenerica('<?php echo $this->baseUrl()?>/admin/relatorios/buscafinanceirodre/dtini/'+dtini+'/dtfim/'+dtfim,'resultado');
	}
	</script>