<script src="<?=$this->baseUrl()?>/public/sistema/js/buscaajax/kangHistoricoprecos.js"></script>

<!-- Content -->
	<div class="content">   

<!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a> </li>
                	<li class="lastB"><?=$this->translate->_("Histórico de preços")?></li>
                </ul>
            </div>
        </div>       
        
        <div class="title"><h5><?=$this->translate->_("Histórico de preços")?></h5>
            <div style="float: right; padding: 10px">
				<a href="javascript:" id="btnImprimir" ><img title="Imprimir" src="<?=$this->baseUrl(); ?>/public/sistema/imagens/icons/middlenav/printerwhite.png" border="0" width="18" /> </a>
			</div>        
        </div>
    		 
		<!-- Busca ------------------------------------------------------ -->
		<div class="widgets" >
			<div class="first" style=" margin-bottom: 5px; border: 1px solid #d5d5d5; padding: 10px" >  
				<form method="post" name="busca" id="busca" class="mainForm">
					<div >
						<table style="width: 100%">
							<tr>
						    	<td align="left" valign="top" class="tdbusca" >
					    			<div class="styled-select" style="width: 250px">
						    			<select name="buscacli" id="buscacli" style="width: 272px">
						    				<option value="0"><?=$this->translate->_("Fornecedor")?></option>
											<?php foreach ($this->objFornec as $listcli): ?>
												<option value="<?php echo $listcli->ID?>"><?php echo $listcli->EMPRESA ?></option>
											<?php endforeach; ?>
										</select>
					    			</div>
								</td>
					    		<td class="tdbusca">
					    			<input type="text" name="codigo" placeholder="<?=$this->translate->_("Código do produto")?>" style="width: 100px"/>
					    		</td>
								<td class="tdbusca" style="width: 50%">
									<input type="button" class="blueBtn btnpesq" value="<?=$this->translate->_("Pesquisar")?>" id="btnbusca">
								</td>
							</tr>								
						</table>
					</div>
				</form>
			</div>
		</div>
		
		<div class="clear"></div>
		
		<div style="display: none; " id="resultado">
			<div style="padding: 10px; border: 1px solid #d5d5d5;">
				<img src="<?php echo $this->baseUrl?>/public/sistema/imagens/loaders/loader6.gif"> <i>Aguarde...</i>
			</div>
		</div>	
 		
	</div>
	
	<script>
	function confirmRemove(id){
		jConfirm('Você deseja remover este pedido?', 'Confirme', function(r) {
			if(r==true){
				
			}
		});
	}

	</script>