<script src="<?=$this->baseUrl()?>/public/sistema/js/buscaajax/relatoriosInconsistencia.js"></script>

<!-- Content -->
	<div class="content">   

<!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a> </li>
                	<li ><a href="<?=$this->baseUrl()?>/admin/relatorios">Relatórios</a></li>         
                	<li class="lastB">Inconsistências</li>
                </ul>
            </div>
        </div>       

        <div class="title"><h5>Inconsistências</h5></div>
        
        <div class="widgets" >
            <div class="widget">
	        	<div class="head"><h5 class="iHelp">Financeiro</h5></div>
	            <div id="financeiro" style="padding: 20px">
	            	<img src="<?php echo $this->baseUrl()?>/public/sistema/imagens/loaders/loader6.gif" alt="Carregando"> <i>Aguarde, verificando erros nos lançamentos do financeiro...</i>
	            </div>
	        </div>
	        
	        <div class="widget">
	        	<div class="head"><h5 class="iFrames">Estoque</h5></div>
	            <div id="estoque" style="padding: 20px">
	            	<img src="<?php echo $this->baseUrl()?>/public/sistema/imagens/loaders/loader6.gif" alt="Carregando"> <i>Aguarde, verificando erros no estoque...</i>
	            </div>
	        </div>
     	</div>
     </div>
	
<script type="text/javascript">
	
	$(window).load(function() {
		buscainconsistencias(1);
	});
		
</script>