<script src="<?=$this->baseUrl()?>/public/javascript/buscaajax/buscaajaxgrupofor.js" type="text/javascript"></script>
<script src="<?=$this->baseUrl()?>/public/javascript/buscaajax/buscaajaxsubgrupo.js" type="text/javascript"></script> 

	<!-- Content -->
    <div class="content">   
	<!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a> </li>
                	<li class="lastB"><a href="<?php echo $this->baseUrl(); ?>/admin/relatorios">Relatórios</a></li>
                	<li class="lastB"><a href="<?php echo $this->baseUrl(); ?>/admin/relatorios/produtosestoque/fil/comp">Situação do estoque</a></li>         
                </ul>
            </div>
        </div>       

        <div class="title"><h5>Situação do estoque</h5>
        	<?php if($this->objNivel == 2){ ?>
        	<div style="float: right; padding: 10px">
				<a href="<?=$this->baseUrl()?>/admin/relatorios/produtosestoqueexp/tipo/2"><img title="Exportar para MS Excel" src="<?=$this->baseUrl(); ?>/public/sistema/imagens/icons/middlenav/excelDocwhite.png" border="0" width="18" /> </a>
			</div>
			<?php } ?>        
        </div>
        
		<div class="widgets" >
        	<!-- Busca -->
        	<div class="first" style="margin-top: 5px; margin-bottom: 5px; " >            
	            <form action="<?php echo $this->baseUrl(); ?>/admin/relatorios/produtosestoque" method="post" name="busca" id="busca" class="mainForm" >
	            <?php if($this->objNivel == 2){ ?>
					<table style="border: 1px solid #d5d5d5; width: 600px">
				    <tr>
				    	<td align="left"  style="padding: 5px">
					    	Código<br />
							<input type="text" size="25" name="codproduto" style="width: 150px" value="<?php echo $this->objPesq['codproduto']?>">											
				    	</td>   
				    	<td>&nbsp;</td>
				    	<td style="padding: 5px">
				    		&nbsp;
				    	</td>				    		
					</tr>
					<tr>
				    	<td align="left" width="200" style="padding: 5px">
							Grupos de Venda:<br>
							<div class="styled-select" style="width: 180px">
							<select name="grupovenda" id="grupovenda" onchange="Mostrasubgrupos(this.value,3);" style="width: 202px; text-transform: uppercase;">
								<option value="0">SELECIONE</option>
								<?php foreach ($this->objGrupov as $listG): ?>
								<option value="<?php echo $listG->id?>" ><?php echo $listG->descricao?></option>
								<?php endforeach;?>					
							</select>								
							</div>	
						</td>
						<td align="left" colspan="2">
						<div id="subgrupo" align="left">
						</div>
						</td>	
						<td style="text-align: right; padding: 5px"><br />
				    		<input type="submit"  value="<?=$this->translate->_("Pesquisar")?>" class="blueBtn" >				
				    	</td>	
					</tr>		
					    		
					</table>	
					<?php } ?> 
				</form>
			</div>
		</div>
		
		<div style="margin: 5px 0px 8px">
		<?php 
		if(!empty($this->objFil)):
			echo ($this->objFil);
		endif;
		?>	
		</div>
		
		<div class="widget first">
 			<table style="width: 100%" class="tableStatic">
            	<thead>
                	<tr>
                        <td width="">Código</td>
                        <td width="30%">Grupo</td>
                        <td width="10%">Estoque</td>
                        <td width="">Vendas (36 Meses)</td>
                        <td width="">Pendências (12 Meses)</td>
                        <td width="15%">Preço</td>
                        <td width="10%">Custo</td>                        
                    </tr>
                </thead>
                <tbody>
           		<?php 			        
			        $cor=0;
	    			foreach($this->objProdutos as $listProd){		        
	        			?>
	        			<tr >
			                <td align="left"><a href="<?=$this->baseUrl();?>/admin/cadastro/produtoscad/produto/<?php echo md5($listProd->idprod)?>" target="_blank"><?php echo $listProd->CODIGO?></a></td>
			                <td align="left"><?php echo $listProd->descgrupo?></td>
			                <td style="text-align: center;"><?php if(!empty($listProd->qt_atual)){ echo $listProd->qt_atual;}else echo 0;?></td>
			                <td style="text-align: center;"><?php echo $listProd->venda?></td>
			                <td style="text-align: center;"><?php if(!empty($listProd->pendencia)) echo $listProd->pendencia; else echo 0?></td>
			                <td style="text-align: center;"><?php if(!empty($listProd->PRECO_UNITARIO)) echo number_format($listProd->PRECO_UNITARIO,2,",","."); else echo "0,00"?></td>
			                <td style="text-align: center;"><?php if(!empty($listProd->custoproduto)) echo number_format($listProd->custoproduto,2,",","."); else echo "0,00"?></td>			                  
			            </tr>
	        				
			        	<?php  
			        }
				?>
				</tbody>
	        </table>
	   </div>
	   <div style="margin-top: 10px"> &nbsp;  
        	<?php 
		    if ( count($this->objProdutos) > 0) :
		    	echo $this->objProdutos;
		    endif;
            ?>
       </div>
   </div>