<script type="text/javascript" src="<?=$this->baseUrl()?>/public/sistema/js/buscaajax/relatoriosVendacusto.js"></script>

<!-- Content -->
	<div class="content">   

<!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a> </li>
                	<li class=""><a href="<?php echo $this->baseUrl(); ?>/admin/relatorios">Relatórios</a></li>
                	<li class="lastB">Custo de vendas</li>         
                </ul>
            </div>
        </div>       
        
        <div class="title"><h5>Custo de vendas</h5>
        	<div style="float: right; padding: 10px; display: none">
				<a href="#" id="btnPrinter"><img src="<?=$this->baseUrl()?>/public/sistema/imagens/icons/middlenav/printerwhite.png" title="Imprimir" border="0" width="18"></a>
			</div>
        </div>
	
		<div class="widgets" >
			<div style="text-align: right;">
				<a href="javascript:void(0)" id="buscaPlcontas" >Plano de contas</a>
			</div>
        	<!-- Busca ------------------------------------------------------ -->
			<div class="widget" style="border: 1px solid #d5d5d5; padding: 10px" >  
				<form method="post" name="busca" id="busca" class="mainForm">
					<table style="width: 40%">
					    <tr>
							<td class="tdbusca" style="vertical-align: middle;">
								<div style="float: left; margin-right: 5px"> 
									<input placeholder="Data inicio" type="text" style="width: 80px" name="dtini" id="dtini" class="data datepicker">
								</div>
								<div style="float: left;">
									<input placeholder="Data final" type="text" style="width: 80px"  name="dtfim" id="dtfim" class="data datepicker">
								</div>
							</td>
							<td style="text-align: right; vertical-align: middle;" class="tdbusca">
								<input type="button" id="btnbuscacusto" class="blueBtn btnpesq" value="Pesquisar">
							</td>
						</tr>								
					</table>
				</form>
			</div>
						
			<div id="resultado" class="resultado">
				<div style="border: 1px solid #d5d5d5; padding: 15px">
					<img src="<?php echo $this->baseUrl?>/public/sistema/imagens/loaders/loader6.gif"> <i>Aguarde...</i>
				</div>
			</div>			
		</div>
	</div>