<script type="text/javascript" src="<?=$this->baseUrl();?>/public/javascript/janelasmodal/javascripts/prototype.js"> </script>
<script type="text/javascript" src="<?=$this->baseUrl();?>/public/javascript/janelasmodal/javascripts/window.js"> </script>
<script type="text/javascript" src="<?=$this->baseUrl();?>/public/javascript/janelasmodal/javascripts/effects.js"> </script> 

<link href="<?=$this->baseUrl();?>/public/javascript/janelasmodal/themes/default.css" rel="stylesheet" type="text/css" >	
<link href="<?=$this->baseUrl();?>/public/javascript/janelasmodal/themes/alphacube.css" rel="stylesheet" type="text/css" >	

<div id="content" >
	<img src="<?=$this->baseUrl();?>/images/progress.gif">
</div>

<script>
	win4 = new Window('4', {className: "alphacube",  width:480, height:350, title: "Lista de produtos entregues"}); 
	win4.setContent("content"); 	
</script>	

<div id="siscorpo">
	<div id="sisnavegacao">
		<a href="<?=$this->baseUrl()?>/admin/painel"><?=$this->translate->_("HOME")?></a>&nbsp; 
		<img src="<?=$this->baseUrl()?>/images/seta.png" width="5" height="7" />&nbsp;
		<a href="<?=$this->baseUrl()?>/admin/kang/pedidos"><?=$this->translate->_("PEDIDOS DE VENDAS")?></a>&nbsp;
		<img src="<?=$this->baseUrl()?>/images/seta.png" width="5" height="7" />&nbsp;
		<a href="<?=$this->baseUrl()?>/admin/kang/vendas"><?=$this->translate->_("VENDAS")?></a>&nbsp;
		<img src="<?=$this->baseUrl()?>/images/seta.png" width="5" height="7" />&nbsp;
		<b><a href="<?=$this->baseUrl()?>/admin/kang/pedidoscompraent"><?=$this->translate->_("PRODUTOS PARA EMBARQUE")?></a></b>&nbsp;
		<div style="float: right;">
			<b><a href="<?=$this->baseUrl()?>/admin/kang/listapacotes"><?=$this->translate->_("LISTA DE PACOTES")?></a></b>&nbsp;
		</div>
	</div>
	<div id="sistitulo"><?=$this->translate->_("LISTA DE PACOTES")?></div>
    <div id="sisconteudo">
		<div>
    		<?php
    		
    		foreach ($this->objFor as $fornecedores):
				?>
				<div style="border-bottom: 1px solid; font-size: 13px; font-weight: bold; position: relative; margin-top: 10px"><?=strtoupper($fornecedores->EMPRESA)." (".strtoupper($fornecedores->nome).")";?></div>
				<table 	width="100%" class="mytable" style="margin-top: 5px" >
					<tr>
			            <th  class="th_canto" style="text-align: center;" width="15%">
			                <?=$this->translate->_("CODIGO")?>
			            </th>
			            <th  class="th_pedido" align="center" width="15%">
			                <?=$this->translate->_("QT DISPONÍVEL")?>
			            </th>
			            <th  class="th_pedido" align="center" width="55%">
			                <?=$this->translate->_("DESCRIÇÃO")?>
			            </th>
			            <th  class="th_pedido" align="center" width="15%">
			                <?=$this->translate->_("DATA ENTREGA")?>
			            </th>
			        </tr>					
					<?php 
					$cor = 0;
			    	foreach($this->objProd as $lista):
			    	 	if($fornecedores->idfor == $lista->id_for):
			            	$cor++;
				            if(($cor%2)==0) $class = 'td_orc_par';
				            else $class = 'td_orc';		            
			               	?>
							<tr >
				                <td  class="<?=$class?>" align="left" >
				                   <?=$lista->CODIGO?>                  
				                </td>
				                <td  class="<?=$class?>" style="text-align: center;" >
				                    <?=$lista->qtent?>
				                </td>
				                <td  class="<?=$class?>" style="text-align: left;">
				                   <?=$lista->DESCRICAO?>    
				                </td>
				                <td  class="<?=$class?>" style="text-align: center;" >
				                   <?=$lista->dtent?> 
				                </td>           
				            </tr>				            
							<?php 
						endif; 
					endforeach;
					?>					
				</table>
				<?php 		
			endforeach;
			?>	
    	</div>
    </div>
</div>