<script src="<?php echo $this->baseUrl(); ?>/public/sistema/js/buscaajax/kangCompras.js"></script>

<?php 
if($this->flashMessages()){ 
	$mes = explode("|", $this->flashMessages());
	?><script>jAlert("<?php echo $mes[1]?>","<?php echo $mes[0]?>");</script><?php
}?>


	<div class="content">
       <!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a> </li>
                	<li ><a href="<?php echo $this->baseUrl(); ?>/admin/kang/pedidoscompra">Compras</a> </li>
                	<li ><a href="<?php echo $this->baseUrl(); ?>/admin/kang/regracomprasgrupos">Grupos de regras</a> </li>
                	<li class="lastB">Regras de compra</li>         
                </ul>
            </div>
        </div>       
        
        <div class="title"><h5>Regras de compra</h5></div>

        <div class="widgets" >
        	
    		<div class="widget " style="padding: 10px; border: 1px solid #d5d5d5;" >
    			<form method="post" class="mainForm" action="<?=$this->baseUrl()?>/admin/kang/gravarregracompra" >
    				<input type="hidden" name="id" >
    				<input type="hidden" name="grupo" value="<?php echo $this->params['grupo']?>">
    				<input type="text" name="ingles" style="width: 80%; margin-bottom: 5px" placeholder="English" >
    				<input type="text" name="chines" style="width: 80%; margin-bottom: 5px" placeholder="中国的"><br />
    				<input type="submit" value="Salvar" class="greenBtn" >    				  
    			</form>
    		</div>
        
            <?php 
    		if ( count($this->objObs) > 0) {
    		?>
    		<div class="widget">
    	 		<table style="width: 100%" class="tableStatic">
    	        	<thead>
    	            	<tr>
    	                	<td width="10%"><?=$this->translate->_("Id")?></td>
    	                    <td ><?=$this->translate->_("Descrição")?></td>
    	                    <td width="10%"><?=$this->translate->_("Opções")?></td>
    	                </tr>
    	          	</thead>
    	      		<tbody>
    			
    				<?php 
    				$cont = 0;
    				foreach($this->objObs as $lista):
    				    $cont++;
    					?>					
    					<tr >
    		                <td  style="text-align: center;" >
    		                   <?php echo $cont?>
    		                </td>
    		                <td  align="left" >
    		                	<?=$lista->desc_ing."<br>".$lista->desc_chines?>
    		                	<input type="hidden" name="ingles_<?php echo $lista->id?>" value="<?=$lista->desc_ing?>">
    		                	<input type="hidden" name="chines_<?php echo $lista->id?>" value="<?=$lista->desc_chines?>">
    		                </td>
    		                <td  style="text-align: center;" >
    		                    <a href="javascript:void(0)" rel="<?php echo $lista->id?>" class="editarRegra"><img src="<?=$this->baseUrl()?>/public/sistema/imagens/icons/middlenav/pencil.png" title="Edit" border="0" width="14"></a>&nbsp;
        		                <a href="javascript:void(0)" rel="<?php echo $lista->id?>" class="removeRegra" ><img src="<?=$this->baseUrl()?>/public/sistema/imagens/icons/middlenav/close.png" title="Remove" border="0" width="14"></a>        		                
    				        </td>		                
    		            </tr>		            
    				<?php  endforeach; ?>
                	</tbody>        
    			</table>
    			
    			</div>
    	   <?php } ?>
		</div>
	    
	</div>
        
			
             
<div style="display: none">
<!-- Essa caixa quarda textos para ser traduzidos. 
Isso devido ao Gettext nao buscar dentro das tags javascript
 --> 
<?=$this->translate->_("Regra salva com sucesso!")?>
<?=$this->translate->_("Remover regra!")?>
<?=$this->translate->_("Remover")?>
</div>