<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>SHUNCORP - www.shuncorp.com </title><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><meta name="keywords" content="rolamentos, cubo de roda, rolamento, embreagem, embreagens, ponta de eixo, pontas de eixo, bomba dagua, bombas dagua, roda, scania, homocinetica, homocineticas, transmissoes" /></head>
<body>
<a href="http://www.shuncorp.com" target="_blank"><font size="6" color="#1b999a" face="Arial, Helvetica, sans-serif">Shunkang</font></a><br /><br />
<font size="2" color="#333333" face="Arial, Helvetica, sans-serif">
Hello, <strong>'.$fornecedores->NOME_CONTATO.' ('.$fornecedores->EMPRESA.' - '.$fornecedores->nome.'),</strong></font><br /><br />
<font size="3" color="#333333" face="Arial, Helvetica, sans-serif">
现在你按照慈溪顺康进出口有限公司的合同编号（例如：'.substr($pks, 0,-1).')来完成箱单.
</font><br />
<font size="2" color="#333333" face="Arial, Helvetica, sans-serif">
Now you can make the PACKING LIST of our purchase (s) '.substr($pks, 0,-1).' Cixi ShunKang. 
</font><br /><br />
<font size="3" color="#333333" face="Arial, Helvetica, sans-serif">
直接点击下面的链接，来做这个箱单： 
</font> <br />
<font size="2" color="#333333" face="Arial, Helvetica, sans-serif">
Click on link below to make this PACKING LIST: 
</font> <br />
<a href="http://www.ztlbrasil.com.br/admin/publico/gerarpallet/ped/'.md5($id).'/fornmd/'.md5($fornecedores->id_for).'" title="www.ztlbrasil.com.br" target="_blank"> <font size="3" color="#1b999a" face="Arial, Helvetica, sans-serif">
<strong>http://www.ztlbrasil.com.br/admin/publico/gerarpallet/ped/'.md5($id).'/fornmd/'.md5($fornecedores->id_for).'</strong> </font> </a> <br /><br />
<font size="3" color="#333333" face="Arial, Helvetica, sans-serif"> 
切记，你有责任完成这些正确的箱单，当我们货物出口到客户那里后，你将自动收到邮件和你们公司的货运唛头。 
</font><br />
<font size="2" color="#333333" face="Arial, Helvetica, sans-serif"> 
Remember that this information is under your responsibility. As we finish the total export shipment for our client you will receive automatic email with YOUR COMPANY shipping marks. 
</font><br /><br />
<font size="3" color="#333333" face="Arial, Helvetica, sans-serif"> 
如果有什么问题，请联系： 郭燕召  邮箱：shuntaiguo@gmail.com  联系电话：0574-63315331 手机： 13780042250 
</font><br />
<font size="2" color="#333333" face="Arial, Helvetica, sans-serif">
For questions, please contact Mr. Yan Zhao Guo: shuntaiguo@gmail.com / 0574-63315331 / 13780042250
</font><br /><br />
<font size="3" color="#333333" face="Arial, Helvetica, sans-serif">
感谢你的支持！
</font><br />
<font size="2" color="#333333" face="Arial, Helvetica, sans-serif">
Sincerely;
</font><br /><br />
<font size="3" color="#333333" face="Arial, Helvetica, sans-serif">
慈溪顺康进出口有限公司 - 采购部。</font><br />
<font size="2" color="#333333" face="Arial, Helvetica, sans-serif">
Cixi ShunKang - Purchasing Department</font>
</body></html>