
<!-- Content -->
	<div class="content">   

<!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a> </li>
                	<li ><a href="<?=$this->baseUrl()?>/admin/kang/pedidos"><?=$this->translate->_("Pedidos de venda")?></a></li>
                	<li class="lastB"><?=$this->translate->_("Vendas")?></li>
                </ul>
            </div>
        </div>       
        
        <div class="title"><h5><?=$this->translate->_("Vendas")?></h5></div>

        <div class="widgets" >
        	<!-- Busca -->
        	<div class="left" style="margin-top: 5px; margin-bottom: 5px" >    
				<?php if($this->objIns==true):?>
				<input onclick="window.location='<?=$this->baseUrl()?>/admin/kang/gerarvenda'" class="basicBtn" type="button" value="<?=$this->translate->_("Novo Venda")?>" >
				<?php endif;?>
			</div>
		</div>

			 
			 <script>
			function mostrarPesquisa(){
			    nTr = document.getElementById("tabela");
			    if(nTr.style.display == "none"){
			        nTr.style.display = "block"
			    }else{
			        nTr.style.display = "none";
			    }
			}
			
			function tipoPesquisa(valor){
			
				if(valor==1){
					document.getElementById("buscid").style.display = "block";
					document.getElementById("data").style.display = "none";
					document.getElementById("busccliente").style.display = "none";
					document.getElementById("dataini").value = "";
					document.getElementById("datafin").value = "";
					document.getElementById("buscacli").value = "";
				}else if(valor==2){
					document.getElementById("data").style.display = "block";
					document.getElementById("buscid").style.display = "none";
					document.getElementById("busccliente").style.display = "none";
					document.getElementById("buscaid").value = "";
					document.getElementById("buscacli").value = "";
				}else if(valor==3){
					document.getElementById("busccliente").style.display = "block";
					document.getElementById("buscid").style.display = "none";
					document.getElementById("data").style.display = "none";
					document.getElementById("buscaid").value = "";
				}
			    
			}
			</script>
			
		<div class="widgets" >
			<div class="first" style="margin-top: 5px; margin-bottom: 5px; " >
			<form action="<?=$this->baseUrl()?>/admin/kang/vendas" method="post" name="busca" id="busca" class="mainForm">
			<table style="margin-bottom: 8px; border: 1px solid #d5d5d5; width: 100%" >
			    <tr>
			    	<td align="left" style="padding: 10px; width: 20%">
				    	<div class="styled-select" style="width: 170px">
					    	<select name="tipo" onchange="tipoPesquisa(this.value);" style="width: 192px">
								<option value="2"><?=$this->translate->_("Por período")?></option>
								<option value="1"><?=$this->translate->_("Por ID")?></option>
								<option value="3"><?=$this->translate->_("Por Cliente")?></option>
							</select>
						</div>
			    	</td>			    	
			    	<td align="left" style="padding: 10px; width: 25%">
				    	<div style="display: none;" id="busccliente">
				    		<div class="styled-select" style="width: 220px">
							<select name="buscacli" id="buscacli" style="width: 242px">
								<?php foreach ($this->objFornec as $listcli): ?>
									<option value="<?php echo $listcli->ID?>"><?php echo $listcli->EMPRESA ?></option>
								<?php endforeach; ?>
							</select>
							</div>
						</div>
						<div style="display: none;" id="buscid">
							<input type="text" size="10" name="buscaid" id="buscaid" style="width: 80px">
						</div>
						<div style="display: block" id="data">
							<input type="text" size="10" name="dataini" id="dataini" class="data datepicker">
							&agrave; <input type="text" size="10" name="datafin" id="datafin" class="data datepicker">							
						</div>						
			    	</td>
			    	<td  style="padding: 10px;"><input type="submit" value="Pesquisar" class="blueBtn"></td>
				</tr>
			</table>  
			</form>
			</div>
		</div>
		
		<?php 
		if ( count($this->objList) > 0) :	
		?>
		<div class="widget">
	 		<table style="width: 100%" class="tableStatic">
	        	<thead>
	            	<tr>
	                	<td ><?=$this->translate->_("Id")?></td>
	                    <td ><?=$this->translate->_("Data")?></td>
	                    <td ><?=$this->translate->_("Plano Cliente")?></td>
	                    <td ><?=$this->translate->_("Situação")?></td>
	                    <td width="10%"><?=$this->translate->_("Opções")?></td>
	                </tr>
	          	</thead>
	      		<tbody>
			
				<?php 
				foreach($this->objList as $lista):
			    	
					?>					
					<tr >
		                <td  style="text-align: center;" >
		                   <?="S".substr("000000".$lista->idped,-6,6)?>
		                </td>
		                <td  style="text-align: center;" >
		                	<?=$lista->dtvenda?>
		                </td>
		                <td  align="left" >
		                	<?=($lista->EMPRESA)?>
		                </td>
		                <td  style="text-align: center;" > 
		                   <?php 
		                   if($lista->sitcominvoice==4) echo '<span style="color: rgb(0, 144, 0);">'.($lista->status).'</span>';
		                   elseif($lista->sitcominvoice==0) echo '<span style="color: #f00;">'.($lista->status).'</span>';
		                   else echo utf8_encode($lista->status);
		                   ?>                  
		                </td>
		                <td  style="text-align: center;" >
		                <a href="<?=$this->baseUrl()?>/admin/kang/vendasdet/ped/<?=md5($lista->idped)?>"><img src="<?=$this->baseUrl()?>/public/sistema/imagens/icons/middlenav/magnify.png" title="Visualizar" border="0" width="16"></a>&nbsp;
		                <?php  
		                if($lista->sitcominvoice!=0):
			                if(($lista->sitcominvoice!=4)): ?>
				                <?php if($this->objEdi==true):?>
				                	<a href="#" onclick="confirmRemove('<?=md5($lista->idped)?>');"><img src="<?=$this->baseUrl()?>/public/sistema/imagens/icons/middlenav/close.png" title="Remove" border="0" width="16"></a>&nbsp;
				                <?php endif;  ?>
			                <?php else: ?>
			                	<a href="<?=$this->baseUrl()?>/admin/kang/gerarxmlvenda/idcom/<?=md5($lista->idped)?>"><img src="<?=$this->baseUrl();?>/public/sistema/imagens/icons/middlenav/ppDoc.png" title="Exportar" border="0" width="16"></a>&nbsp;
			                <?php endif; ?> 
			                <?php
		                endif;
		                
		                if($lista->financeiro==true and $lista->sitcominvoice!=0):
	                		?><a href="javascript:void(0);" onclick="confirmFinalizafinanceiro('<?=md5($lista->idped)?>');" ><img src="<?=$this->baseUrl()?>/public/sistema/imagens/icons/middlenav/money.png" width="16" border="0" title="Financial close"></a><?php 
	                	endif;
	                	?>
		                </td>		                
		            </tr>		            
				<?php  endforeach; ?>
            	</tbody>        
			</table>
			
		</div>
		<div style="margin-top: 20px">
			<?php 
			if ( count($this->objList) > 0) :
				echo $this->objList;
			endif;
		    ?>
		</div>
		<?php 
		else :
		?>
		<div class="widget" style="border-top: 1px solid #d5d5d5; padding: 10px; text-align: center">
 			Nenhuma venda encontrado!
		</div>	
		<?php 
		endif;
		?>
	</div>	
		    
	<script>
	function confirmFinalizafinanceiro(id){
		jConfirm('Finalizar o financeiro desta venda?', 'Confirme', function(r) {
			if(r==true){
				window.location='<?=$this->baseUrl()?>/admin/kang/baixarfinanceiroinvoice/invoice/'+id;	
			}
		});
	}

	function confirmRemove(id){
		jConfirm('Você deseja remover esta venda?', 'Confirme', function(r) {
			if(r==true){
				window.location='<?=$this->baseUrl()?>/admin/kang/removevenda/invoice/'+id;	
			}
		});
	}
	
	</script>