<!-- Janelas popups modal 
<script type="text/javascript" src="<?=$this->baseUrl();?>/public/javascript/janelasmodal/javascripts/prototype.js"> </script>
<script type="text/javascript" src="<?=$this->baseUrl();?>/public/javascript/janelasmodal/javascripts/window.js"> </script>

<link href="<?=$this->baseUrl();?>/public/javascript/janelasmodal/themes/default.css" rel="stylesheet" type="text/css" >	
<link href="<?=$this->baseUrl();?>/public/javascript/janelasmodal/themes/alphacube.css" rel="stylesheet" type="text/css" >	

<div id="content" >
	
<img width="975px" src="<?=$this->baseUrl()?>/imagens/sistema/mapas/<?=$estado->uf?>.jpg" style="border-style:none; " onmousedown="coordenadas(event)">	
	
</div>
-->

<? foreach ($this->objUf as $estado); ?>
<div id="siscorpo">
	<div id="sisnavegacao">
		<a href="<?=$this->baseUrl()?>/admin/painel"><?=$this->translate->_("HOME")?></a>&nbsp; 
		<img src="<?=$this->baseUrl()?>/images/seta.png" width="5" height="7" />&nbsp;
		<a href="<?=$this->baseUrl()?>/admin/cadastro/parceiroslista"><?=$this->translate->_("PARCEIROS")?></a>&nbsp; 
		<img src="<?=$this->baseUrl()?>/images/seta.png" width="5" height="7" />&nbsp;
		<a href="<?=$this->baseUrl()?>/admin/cadastro/paises"><?=$this->translate->_("PAÍSES")?></a>&nbsp;			
		<img src="<?=$this->baseUrl()?>/images/seta.png" width="5" height="7" />&nbsp;
		<a href="<?=$this->baseUrl()?>/admin/cadastro/estados/idpais/<?=md5($estado->id_paises)?>"><?=$this->translate->_("ESTADOS")?></a>&nbsp;
		<img src="<?=$this->baseUrl()?>/images/seta.png" width="5" height="7" />&nbsp;
		<a href="<?=$this->baseUrl()?>/admin/cadastro/cidades/uf/<?=$estado->uf?>"><b><?=$this->translate->_("CIDADES")?></b></a>&nbsp;
	</div>
	<div id="sistitulo">CIDADES</div>
    <div id="sisconteudo">  
		
		<!--<script>
			win4 = new Window('4', {className: "alphacube",  width:975, height:700, title: "Selecione"}); 
			win4.setContent("content"); 
		
			function coordenadas(event){
				document.cadastra.x.value = event.layerX;
				document.cadastra.y.value = event.layerY;	
				Windows.close("4", event);	
			}
			
		</script>			
		-->
		
		<div>
		<form action="<?=$this->baseUrl()?>/admin/cadastro/cadastracidades" name="cadastra" method="post">
		<table cellpadding="3" cellspacing="0" width="50%" style="margin: 5px 0px">
			<tr>
				<td align="left" width="37%" >		
					<input type="hidden" name="idestado" value="<?=$estado->id?>">
					<input type="hidden" name="uf" value="<?=$estado->uf?>">
					<input type="hidden" name="idcidade" >
					<?=$this->translate->_("Cidade")?>:<br />
					<input type="text" name="cidade" size="30px" >
				</td>
				
				<td align="left" width="12%" >		
					<?=$this->translate->_("Código")?>:<br />
					<input type="text" name="codigo" size="7px" >
				</td>
				<td align="left" >
					<br /><input type="submit" value="<?=$this->translate->_("Salvar")?>">
					<script type="text/javascript">
					function editarPais(id, nome, cod){
						document.cadastra.cidade.value = nome;
						document.cadastra.idcidade.value = id;
						document.cadastra.codigo.value = cod;
					}
					</script>
				
				</td>
				<!--<td align="right" width="30%">
					<a id="add" href="javascript:void(0);" onclick="win4.showCenter();">
					<b>MAPA</b>
					</a>
				</td>		
			--></tr>
		</table>
		</form>  
		</div>
		<div style="text-align: center; width: 100%; ">
	        <?php 			
        	if(count($this->objList) > 0) :			
			?>
			<table align="left" class="mytable"  width="100%" cellspacing="0" cellpadding="0">
		         <tr>
		            <th  class="th_canto_orc" style="text-align: center;" width="15%">
		                <?=$this->translate->_("ID")?>
		            </th>
		            <th  class="th_orc" style="text-align: center;" width="50%">
		                <?=$this->translate->_("ESTADO")?>
		            </th>
		            <th  class="th_orc" style="text-align: center;" >
		                <?=$this->translate->_("Código")?>
		            </th>
		            <th  class="th_orc" style="text-align: center;" width="15%">
		                <?=$this->translate->_("OPÇÕES")?>
		            </th>
		        </tr>		       
			<?php 
			$cor=0;
	    	foreach($this->objList as $lista):
	    	$cor++;
            if(($cor%2)==0) $class = 'td_orc_par';
            else $class = 'td_orc';
			?>
			
			<tr >
                <td  class="<?=$class?>" style="text-align: center;" >
                   <?=substr("000".$cor,-3,3)?>
                </td>
                <td  class="<?=$class?>" align="left" style="text-transform: uppercase;">
                   <?=$lista->nome?>
                </td>
                <td  class="<?=$class?>" style="text-align: center;">
                   <?=$lista->codigo?>
                </td>
                <td  class="<?=$class?>" style="text-align: center;" >
                	<a href="#" onclick="editarPais('<?=$lista->id?>','<?=$lista->nome?>','<?=$lista->codigo?>');" >
                	<img src="<?=$this->baseUrl(); ?>/images/edit_orc.gif" width="15" height="15" border="0" title="Editar" ></a>
                </td>                
            </tr>            
			<?php  endforeach;
			?>        
			</table>
			<?php 
			else :
			?>
			<br>
			<?=$this->translate->_("Nenhuma Cidade Cadastrada")?>			
			<?php 
			endif;
			?>
		</div>
	</div>
</div>