<?php 
$usuario = Zend_Auth::getInstance()->getIdentity();
?>

	<style>
         .deactive {
	       pointer-events: none;
	       cursor: default;
	     } 
        </style>
        
<!-- Content -->
	<div class="content">   

<!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a> </li>
                	<li class="lastB">Contatos</li>         
                </ul>
            </div>
        </div>       

        <div class="title"><h5>Contatos</h5></div>
        
        <div class="widgets" >
			<div class="widget" style="border-top: 1px solid #d5d5d5;">
				<div class="left" style="width: 50%">
					<div style="margin: 10px 30px 10px 30px; width: 100%">
						<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;<b>Contatos</b><br>
						&nbsp; &nbsp; 
						<a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/contatosemp" >
						Todos os contatos
						</a><br>
						<!-- &nbsp; &nbsp; 
						<a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/contatosempquar/fil/todos" >
						Quarentena
						</a><br> -->
						&nbsp; &nbsp; 
						<a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/contatosinteracoes" >
						Interações
						</a><br>						
					</div>	
					<?php if($usuario->id == 5 || $usuario->id == 613){ ?>			
					<div style="margin: 10px 30px 10px 30px; width: 100%">
						<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;<b>Listas de contatos</b><br>
						&nbsp; &nbsp; 
						<a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/contatosrelsalvos">
						Gerenciar listas
						</a><br>
						<?php foreach($this->objLista as $lista){ ?>
						&nbsp; &nbsp; 
						<a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/abrircontatosrel/idcampanha/<?php echo md5($lista->id)?>">
						<?php echo $lista->nome?>
						</a><br>
						<?php } ?>						
					</div>	
					<?php } ?>				
				</div>
				
				<div class="right" style="width: 30%; margin: 20px">
					<table style="width: 100%; font-size: 14px; border: 1px solid #ccc;">
						<?php 
						/* if(count($this->objEmpn)>0){ 
							foreach ($this->objEmpn as $contatos);
						    ?>
						<tr style="background-color: #ccc">
							<td style="padding: 10px">Não definido</td>
							<td style="text-align: right; padding: 10px"><?php echo $contatos->qt?></td>
						</tr>
						<?php } */ ?>
						<?php 
						if(count($this->objEmpp)>0){ 
							foreach ($this->objEmpp as $contatos);
						    ?>
						<tr >
							<td style="padding: 10px">Parceiros</td>
							<td style="text-align: right; padding: 10px"><?php echo $contatos->qt?></td>
						</tr>
						<?php } 
						
						if(count($this->objEmpm)>0){ 
							foreach ($this->objEmpm as $contatos);
						    ?>
						<tr style="background-color: #ccc">
							<td style="padding: 10px">Mercado</td>
							<td style="text-align: right; padding: 10px"><?php echo $contatos->qt?></td>
						</tr>
						<?php } 
						
						if(count($this->objEmpa)>0){ 
							foreach ($this->objEmpa as $contatos);
						    ?>
						<tr >
							<td style="padding: 10px">Alvos</td>
							<td style="text-align: right; padding: 10px"><?php echo $contatos->qt?></td>
						</tr>
						<?php } ?>
								
						<tr style="background-color: #ccc">
							<td style="padding: 10px">Contatos</td>
							<td style="text-align: right; padding:10px">
							<?php 
							if(count($this->objCont)>0):								
								foreach ($this->objCont as $contatos);
								echo $contatos->qt;
							endif;
							?></td>
						</tr>
					</table> 
				</div>
				
				<div class="clear"></div>
			</div>
		</div>
	</div>