<table width="100%" cellpadding="0" cellspacing="0" >
	<tr>
		<td align="left">				
		<table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom: 5px" >
			<tr>
				<td align="left">
					<a href="<?php echo $this->baseUrl(); ?>/admin/painel"><?=$this->translate->_("HOME")?></a>&nbsp;
					<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
					<a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/contatos">CONTATOS</a>&nbsp;	 
					<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
					<a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/contatosemp/fil/todos"><?=$this->translate->_("EMPRESAS")?></a>&nbsp;
					<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
					<a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/contatoscampanha"><b><?=$this->translate->_("CAMPANHA EMBREAGEM")?></b></a>										
				</td>
			</tr>
		</table>
 		</td>
	</tr>
	<tr>
		<td>
			<table width="100%" class="borda_titulo" >
				<tr>
			    	<td width="left">
			    	CAMPANHA EMBREAGEM
					</td>
			    </tr>
			</table>
		</td>
	</tr>
	<tr>
		<td style="padding-top: 10px">
		<div style="width: 45%;  border: 1px solid #000; padding: 5px; margin-bottom: 5px" id="tabela">
			<form name="pesquisa" action="" method="post" >
			    Regi&atilde;o:	<br >	
				<select name="buscaregioes" onchange="submit();">
			  	<option value='0'>Selecione</option>
			  	<?php foreach ($this->objRegioes as $listR): ?>
					<option value='<?=$listR->idreg?>'><?php echo ($listR->NOME." ".$listR->EMPRESA)?></option>
				<?php endforeach; ?>
				</select>
			</form>
		</div>
		</td>
	</tr>
	<tr>
		<td style="padding-top: 10px">  
			      
           	<?php
			if(count($this->objList) > 0) :
				$count = 0;
				foreach ($this->objList as $contatos):
				$count ++;
				?>
					<table style="border: 1px solid; width: 100%; margin-bottom: 15px">
						<tr>
							<td style="font-weight: bold;">
								Ordem: <?=$count?> &nbsp; &nbsp; &nbsp; 
								<a target="_blank" href="<?=$this->baseUrl()?>/admin/cadastro/contatoscad/tp/<?=$contatos->TIPO?>/empresa/<?=md5($contatos->ID_EMP)?>/contato/<?=md5($contatos->idcontato)?>">
								ID: <b><?=$contatos->idcontato?></b>
								
								</a>
							</td>
							<td colspan="2">Nome: <b><?=$contatos->contato?></b></td>
						</tr>
						<tr>
							<td>Empresa: <b>
								<? if($contatos->TIPO == 0): echo $contatos->matriz; else: echo $contatos->filial; endif;?>
							</b></td>
							<td>Email: <b><?=$contatos->EMAIL?></b></td>
							<td>CEP: <b><?=$contatos->CEP?></b></td>
						</tr>
						<tr>
							<td>Logradouro: <b><?=$contatos->ENDERECO?></b></td>
							<td>Bairro: <b><?=$contatos->BAIRRO?></b></td>
							<td>Cidade: <b><?=$contatos->nomecidade?></b></td>
						</tr>
						<tr>
							<td>UF: <b><?=$contatos->estadoc?></b></td>
							<td>Tipo Cliente: <b><?=$contatos->grupointeresse?></b></td>
							<td>Tipo Campanha: <b><? if($contatos->campanha == 1) echo "Básica"; else echo "Completa"; ?></b></td>
						</tr>
					</table>
				<?php 
				endforeach;
			else :
				?>
				<br><center>Nenhum contato encontrado</center>			
				<?php 
			endif;
			?>
		</td>
	</tr>
</table>			
	