	<script src="<?php echo $this->baseUrl(); ?>/public/sistema/js/buscaajax/cadastroContatosemp.js"></script>
	<script src="<?php echo $this->baseUrl(); ?>/public/sistema/js/buscaajax/cadastroContatosquar.js"></script>
	<script src="<?php echo $this->baseUrl(); ?>/public/sistema/js/buscaajax/cadastroBuscauf.js"></script>

	<div class="content">
	<!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="#">Home</a> </li>
                	<li><a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/contatos">Contatos</a></li>
                	<li><a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/contatosemp/fil/todos">Empresas</a></li>
                	<li class="lastB"><a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/contatosempquar/fil/todos">Quarentena</a></li>
                </ul>
            </div>
        </div>       
        
        <div class="title"><h5>Quarentena</h5></div>
            
        <div class="widgets" style="margin-top: 5px">
 			<form name="pesquisa" action="<?php echo $this->baseUrl(); ?>/admin/cadastro/contatosempquar" method="post" class="mainForm" >
				Nome ou ID<br />
				<input type="text" name="buscaquarentena" size="30" style="margin-bottom: 4px; width: 260px" >
				<input type="submit" value="Buscar" class="basicBtn"/>
			</form>
		</div>	
		
	   	<?php
        if(count($this->objEmp) > 0) :			
			?>
			<div class="widget" >
	 			<table style="width: 100%" class="tableStatic" id="listcontatos">
	            	<thead>
	                	<tr>
	                        <td width="15%">Id</td>
	                        <td width="">Nome</td>
	                        <td width="15%">Opções</td>
	                    </tr>
	                </thead>
	                <tbody>
	               
					<?php 
					foreach($this->objEmp as $lista):
						if($lista->id_contatos):
							?> 
							<tr>
				                <td   style="text-align: center;" >
				                   C<?=$lista->id_contatos?>
				                </td>
				                <td   align="left" >
				                	<span style=" text-transform: uppercase;"><?=($lista->nomecontato)?></span>
				                </td>
				                <td   style="text-align: center;" >
				                	<a href="javascript:void(0)" onclick="buscaContatoemp('<?=$lista->id_contatos?>','0','<?php echo $lista->ID_EMP?>');"><img src="<?=$this->baseUrl()?>/public/sistema/imagens/icons/middlenav/magnify.png" width="16" title="Visualizar"></a> &nbsp;
				                	<a href="#" onclick="confirmeExcluircontato('<?=$lista->id_contatos?>')" ><img src="<?=$this->baseUrl(); ?>/public/sistema/imagens/icons/middlenav/close.png" width="15" border="0" title="Remover"></a>
				                </td>
				            </tr>  
							<?php							 
						elseif($lista->id_contatosempfilial):
							?>
							<tr>
				                <td   style="text-align: center;" >
				                   F<?=$lista->id_contatosempfilial?>
				                </td>
				                <td   align="left" >
				                	<span style=" text-transform: uppercase; <?php if($lista->verificafildom == 0): ?> color: #f00; <?php endif; ?> "> <?=($lista->empfilial)?></span>
				                	<br>
				                   	<span style="font-size: 75%">
				                   	<?php if($lista->vfcontato == 0): ?> 
				                   	<a href="javascript:void(0);" onclick="buscaContatosfiliais('<?=$lista->id_contatosempfilial?>')" >
				                   		<span style="color: #f00;">Contatos</span>
				                   	</a>	  
				                   	<?php endif; ?> 
				                   	</span>
				                </td>
				                <td   style="text-align: center;" >
				                	<a href="javascript:void(0)" onclick="buscaFilial('<?=$lista->id_contatosempfilial?>','<?php echo $lista->id_matriz?>');"><img src="<?=$this->baseUrl()?>/public/sistema/imagens/icons/middlenav/magnify.png" width="16" title="Editar"></a>
				                	<a href="#" onclick="confirmeExcluirfilial('<?=md5($lista->id_contatosempfilial)?>')" ><img src="<?=$this->baseUrl(); ?>/public/sistema/imagens/icons/middlenav/close.png" width="15" border="0" title="Remover"></a>
				                </td>
				            </tr> 
				            <tr style="display: none;" id="F<?=$lista->id_contatosempfilial?>" ><td><img src="<?php echo $this->baseUrl?>/public/sistema/imagens/loaders/loader6.gif"> Gerando relatório. Aguarde...</td></tr> 
							<?php
						else:
							?>
							<tr>
				                <td   style="text-align: center;" >
				                   M<?=$lista->id_contatosemp?>
				                </td>
				                <td   align="left" >
				                	<span style=" text-transform: uppercase; <?php if($lista->verificadom == 0): ?> color: #f00; <?php endif; ?> "> <?=($lista->empmatriz)?></span>
				                	<br>
				                   	<span style="font-size: 75%">
				                   	<?php if($lista->vmfilial == 0): ?> 
				                   	<a href="javascript:void(0);" onclick="buscaFiliais('<?=$lista->id_contatosemp?>');" >
				                   		<span style="color: #f00; ">Filiais</span>
				                   	</a>&nbsp;  &nbsp;  &nbsp;
				                   	<?php endif; ?> 
				                   	<?php if($lista->vmcontato == 0): ?> 
				                   	<a href="javascript:void(0);" onclick="buscaContatosmatriz('<?=$lista->id_contatosemp?>');" >
				                   		<span style="color: #f00;">Contatos</span>
				                   	</a>	  
				                   	<?php endif; ?> 
				                   	</span>
				                </td>
				                <td   style="text-align: center;" >
				                	<a target="_blank" href="<?php echo $this->baseUrl(); ?>/admin/cadastro/contatosempcad/empresa/<?=md5($lista->id_contatosemp)?>"><img src="<?=$this->baseUrl()?>/public/sistema/imagens/icons/middlenav/magnify.png" width="16" title="Editar"></a>
				                	<a href="#" onclick="confirmeExcluirempresa('<?=md5($lista->id_contatosemp)?>');" ><img src="<?=$this->baseUrl(); ?>/public/sistema/imagens/icons/middlenav/close.png" width="15" border="0" title="Remover"></a>
				                </td>
				            </tr>
				            <tr style="display: none;" id="M<?=$lista->id_contatosemp?>" ></tr>  
							<?php
						endif;
					endforeach;
					?>
					</tbody>      
				</table>
			</div>
			
			<script type="text/javascript">

			
			function mostrarContatos(id,idlinha){
				document.getElementById(idlinha).style.display = "table-row";	
				nTr = document.getElementById(id);
			    if(nTr!=null){
				    if(nTr.style.display == "none"){
				        nTr.style.display = "table";
				    }else{
				        nTr.style.display = "none";
				    }
			    }					
			}
			
			function mostrarContfiliais(idlinha){
				nTr = document.getElementById(idlinha)	
				if(nTr!=null){
				    if(nTr.style.display == "none"){
				        nTr.style.display = "table-row";
				    }else{
				        nTr.style.display = "none";
				    }
			    }			
			}
				
			</script>
			
			
			<div style="margin-top: 20px">
				<?php 
				if ( count($this->objEmp) > 0) :
	            	echo $this->objEmp;
	            endif;
			    ?>
			</div>
			
	        <?php 
			else :
				?>
				<div style="text-align: center; margin-top: 30px">Nenhuma contato encontrado</div>
				<?php 
			endif;
		?>
	</div>

	
<script>
		
	function buscaContatoemp(contato,emptp,empresa){
		buscaContato(contato,emptp,empresa);
	}

	function confirmeExcluirempresa(emp){
		jConfirm('Tem certeza que deseja excluir a empresa?', 'Confirme', function(r) {
			if(r==true){
				window.location='<?=$this->baseUrl()?>/admin/cadastro/removematriz/empresa/'+emp;
			}
		});
    }

	function confirmeExcluircontato(contato){
		jConfirm('Tem certeza que deseja excluir este contato?', 'Confirme', function(r) {
			if(r==true){
				window.location='<?=$this->baseUrl()?>/admin/cadastro/removecontato/contato/'+contato;
			}
		});
    }

	function confirmeExcluirfilial(filial){
		jConfirm('Tem certeza que deseja excluir a filial?', 'Confirme', function(r) {
			if(r==true){
				window.location='<?=$this->baseUrl()?>/admin/cadastro/removeempfilial/empresa/'+filial;
			}
		});
    }

	
</script>