<?php 
foreach ($this->objUf as $uf); 
?>
<div id="siscorpo">
	<div id="sisnavegacao">
		<a href="<?=$this->baseUrl(); ?>/admin/painel"><?=$this->translate->_("HOME")?></a>&nbsp; 
		<img src="<?=$this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
		<a href="<?=$this->baseUrl(); ?>/admin/cadastro/despesasfiscais"><?=$this->translate->_("TRIBUTOS")?></a>&nbsp;
		<img src="<?=$this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp; 
		<b><a href="<?=$this->baseUrl(); ?>/admin/cadastro/despesasfiscaisuf/iduf/<?=md5($uf->id)?>"><?=strtoupper($uf->nome)?></a></b>
	</div>
	<div id="sistitulo"><?=$uf->nome?></div>
    <div id="sisconteudo">  
    	<div>
    		<input type="button" value="Novo Perfil Fiscal" onclick="window.location='<?=$this->baseUrl()?>/admin/cadastro/despesasfiscaiscad/iduf/<?=md5($uf->id)?>';">
    	</div>
    	<div style="margin-top: 5px">
	    <?php 					
		if ( count($this->objList) > 0) :					
			?>
			<table align="left" class="mytable" width="100%" cellspacing="0" cellpadding="0" >
		        <tr>
		            <th  class="th_canto_orc" align="center" width="10%">
		                <?=$this->translate->_("ID")?>
		            </th>
		            <th  class="th_orc" align="center"  >
		                <?=$this->translate->_("DESCRIÇÃO ")?>
		            </th>
		            <th  class="th_orc" align="center" width="15%">
		            	<?=$this->translate->_("SITUAÇÃO ")?>
		            </th>
		            <th  class="th_orc" align="center" width="15%">
		                <?=$this->translate->_("OPÇÕES")?>
		            </th>
		       </tr>	
			
			<?php 
			$cor=0;
	    	foreach($this->objList as $lista):
	    	$cor++;
            if(($cor%2)==0) $class = 'td_orc_par';
            else $class = 'td_orc';
			?>
			
			<tr >
                <td  class="<?=$class?>" style="text-align: center;" >
                   <?=$cor?>
                </td>
                <td  class="<?=$class?>" >
                	<?=$lista->descricao?>
                </td>
                <td  class="<?=$class?>" style="text-align: center;" >
                	<? if($lista->sit==1) echo "ATIVO"; else echo "INATIVO"?>
                </td>
                <td  class="<?=$class?>" style="text-align: center;" > 
                	<a href="<?=$this->baseUrl()?>/admin/cadastro/despesasfiscaiscad/desp/<?=md5($lista->id)?>" ><img src="<?=$this->baseUrl();?>/images/visualizar_orc.gif" width="15" border="0" title="Visualizar"></a>&nbsp;&nbsp;
                	<?php if(($this->objEdi==true) and ($lista->sit==1)):?>
                	<a href="#" onclick="if(confirm('Inativar Pefil fiscal?')){ window.location='<?=$this->baseUrl()?>/admin/cadastro/despesasfiscaisrem/desp/<?=md5($lista->id)?>/iduf/<?=md5($uf->id)?>';};"><img src="<?=$this->baseUrl();?>/images/window-close.png" title="Inativar" border="0" width="15"></a>
                	<?php endif; ?>
                </td>		                
            </tr>		            
			<?php  
			endforeach;	
			?>
		</table>
		<?php 							
			else :
			?>
			<center><?=$this->translate->_("Nenhum perfil fiscal cadastrado")?></center>
			<?php 
			endif;
		?>
		</div>    			
	</div>
</div>
	