<?php 
foreach ($this->objUf as $uf); 
foreach ($this->objDesp as $despesas);
?>
<div id="siscorpo">
	<div id="sisnavegacao">
		<a href="<?=$this->baseUrl(); ?>/admin/painel">HOME</a>&nbsp; 
		<img src="<?=$this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
		<a href="<?=$this->baseUrl(); ?>/admin/cadastro/despesasfiscais">TRIBUTOS</a>&nbsp;
		<img src="<?=$this->baseUrl()?>/images/seta.png" width="5" height="7" />&nbsp; 
		<a href="<?=$this->baseUrl()?>/admin/cadastro/despesasfiscaisuf/iduf/<?=md5($uf->id)?>"><?=strtoupper($uf->nome)?></a>&nbsp;
		<img src="<?=$this->baseUrl()?>/images/seta.png" width="5" height="7" />&nbsp; 
		<a href="<?=$this->baseUrl()?>/admin/cadastro/despesasfiscaiscad/desp/<?=md5($despesas->id)?>"><?=strtoupper($despesas->descricao)?></a>&nbsp;		
		<img src="<?=$this->baseUrl()?>/images/seta.png" width="5" height="7" />&nbsp; 
		<b><a href="<?=$this->baseUrl()?>/admin/cadastro/despesasfiscaisncm/desp/<?=md5($despesas->id)?>">NCM</a></b>&nbsp;
	</div>
	<div id="sistitulo">NCM</div>
	<div id="sisconteudo">
		<?php  if($this->objIns==true):?>
		<div style="margin-bottom: 5px">
    	<input type="button" class="button" onclick="window.location='<?=$this->baseUrl()?>/admin/cadastro/despesasfiscaisncmcad/desp/<?=md5($despesas->id)?>'" value="Novo NCM"></input>
    	</div>
		<?php endif; ?> 
		<div>
			<?php
			if (count($this->objList) > 0) :
			?>
			<table  class="mytable" >
		         <tr>
		            <th  class="th_canto_orc" align="center" width="15%">
		                ID
		            </th>
		            <th  class="th_orc" align="center" width="45%">
		                NCM
		            </th>
		            <?php if ($this->objEdi==true){  ?>
		            <th  class="th_orc" align="center" width="12%">
		                Op&ccedil;&otilde;es
		            </th>
		            <?php } ?>
		        </tr>		       
			<?php 
			$cor=0;
	    	foreach($this->objList as $lista):
	    	$cor++;
            if(($cor%2)==0) $class = 'td_orc_par';
            else $class = 'td_orc';
			?>
			
			<tr >
                <td  class="<?=$class?>" style="text-align: center;" >
                   <?php echo substr("000".$cor,-3,3)?>
                </td>
                <td  class="<?=$class?>" style="text-transform: uppercase; text-align: center;" >
                   <?=$lista->ncm." ".$lista->ncmex?>
                </td>
                <?php if ($this->objEdi==true):  ?>
                <td  class="<?=$class?>" style="text-align: center;" >
                	<a href="<?=$this->baseUrl()?>/admin/cadastro/despesasfiscaisncmcad/desp/<?=md5($despesas->id)?>/ncmcli/<?=md5($lista->id)?>" >
                	<img src="<?=$this->baseUrl(); ?>/images/edit_orc.gif" width="15" height="15" border="0" title="Editar" ></a>
                </td>
                <?php  endif;  ?>
            </tr>
            
			<?php  endforeach;
			?>        
			
			</table>
			</div>

         	 <?php 
			else :
			?>
			<div style="margin-top: 30px; text-align: center;">Nenhum NCM Cadastrado</div>			
			<?php 
			endif;
		?>
		</div>
	</div>
	