<script src="<?php echo $this->baseUrl(); ?>/public/sistema/js/buscaajax/cadastroMontadoras.js"></script>


<?php 
if($this->flashMessages()){ 
	$mes = explode("|", $this->flashMessages());
	?><script>jAlert("<?php echo $mes[1]?>","<?php echo $mes[0]?>")</script><?php
}?>


	<div class="content">
       <!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a> </li>
                	<li class="lastB">Montadoras</li>         
                </ul>
            </div>
        </div>       
        
        <div class="title"><h5>Montadoras</h5></div>
        <!-- Busca ------------------------------------------------------ -->
		<div class="widgets" >
			<div class="" style="margin-top: 5px; margin-bottom: 5px; border: 1px solid #d5d5d5; padding: 10px" >  
				<form method="post" name="busca" id="busca" class="mainForm">
					<input type="text" name="montadora" style="width: 250px" placeholder="Montadora">
    				<input type="button" class="blueBtn" value="Pesquisar" id="btnbusca" >
    			</form>
    		</div>
    	</div>
			
	        
	    <div class="clear"></div>
		
		<div id="resultado"></div>
	    
	</div>
	
	
	