<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>SisZTL 2.0 Alpha - ztlbrasil.com.br</title>
<link href="<?=$this->baseUrl()?>/public/sistema/imagens/ztl.ico" rel="shortcut icon" type="image/x-ico"/>
<link href="<?=$this->baseUrl()?>/public/sistema/css/mainprint.css" rel="stylesheet" type="text/css" />	

</head>
<!-- Content -->

<body onload="window.print();">
    <div class="content" style="width: 1000px; margin: auto">
    	<div class="widgets">
    		<div class="left">SisZTL 2.0 Alpha</div>
    		<div class="right" style="text-align: right;"><?php echo date('d/m/Y H:i')?></div>
    		<div class="clear"></div>	
    	</div>   
    	
    	<div class="title"><h5>Lista de produtos</h5></div>

	        <?php 
			if (count($this->objList) > 0) :
				?>
				<div class="widget first">
	 			<table style="width: 100%" class="tableStatic">
	            	<thead>
	                	<tr>
	                        <td ><?=$this->translate->_("C&oacute;digo")?></td>
	                        <td ><?=$this->translate->_("Descri&ccedil;&atilde;o")?></td>
	                        <td ><?=$this->translate->_("Grupo/Subgrupo")?></td>
	                        <td ><?=$this->translate->_("Fornecedor")?></td>
	                        <td ><?=$this->translate->_("Preço")?></td>
	                        <td ><?=$this->translate->_("Situa&ccedil;&atilde;o")?></td>
	                    </tr>
	                </thead>
	                <tbody>				
					<?php 
					foreach($this->objList as $lista):
			    		?>
						<tr >
			                <td align="center" >
			                   <?=$lista->CODIGO?>
			                </td>
			                <td align="left" style="text-transform: uppercase;">
			                   <?=stripcslashes(($lista->DESCRICAO))?>
			                </td>
			                <td align="left" ><?php echo $lista->grupo."/".$lista->subgrupo?></td>
			                <td align="left" ><?php echo $lista->EMPRESA?></td>
			                <td align="left" ><?php if(!empty($lista->custo_valor_shuntai)) echo $lista->moeda." ".number_format($lista->custo_valor_shuntai,2,",",".")?></td>
			                <td align="center" >
			                   <?php if($lista->situacao == 0):?>
			                   		ATIVO
			                   <?php elseif($lista->situacao == 1): ?>
			                   		DESEN
			                   <?php elseif($lista->situacao == 2): ?>
			                   		INATIVO
			                   <?php endif;?>
			                   	
			                </td>		                
			            </tr>
			<?php  endforeach; ?>
                </tbody>
            </table>            
        </div>
       
		<?php 
		else :
		?>
		<div class="widget first">
 			Nenhum Produto Encontrado
		</div>	
		<?php 
		endif;
		?>
	</div>
		
</body>
</html>