<div id="siscorpo">
	<div id="sisnavegacao">
		<a href="<?php echo $this->baseUrl(); ?>/admin/painel">HOME</a>&nbsp; 
		<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
		<a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/produtos"><?=$this->translate->_("PRODUTOS");?></a> &nbsp; 
		<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp; 
		<b><a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/produtosmaterial"><?=$this->translate->_("MATERIAL");?></a></b>
	</div>
	<div id="sistitulo"><?=$this->translate->_("MATERIAL")?></div>
	<?php if($this->objIns == true): ?>
	<div style="border: 1px solid; padding: 10px; margin-top: 10px">
	<form action="<?=$this->baseUrl()?>/admin/cadastro/gravarprodmaterial" method="post" name="prepedido">
		<input type="hidden" name="iddesc">
		Descrição:<br /><input type="text" name="desc" style="width: 60%"><br /><br />
		Descrição chinês:<br /><input type="text" name="descchines" style="width: 60%"><br /><br />
		<input type="submit" value="Salvar">		
	</form>
	</div>
	<?php endif; ?>
	<div>	
		<?php if(count($this->objMaterial)>0): ?>
		<table  class="mytable" style="margin-top: 6px">			
		    <tr>
	            <th  class="th_canto" style="text-align: center;" width="10%">
	                <?=$this->translate->_("ID")?>
	            </th>
	            <th  class="th_pedido" align="center" width="80%">
	                <?=$this->translate->_("DESCRIÇÂO")?>
	            </th>
	             <th  class="th_pedido" align="center" width="10%">
	                &nbsp;
	            </th>	            
	        </tr>
			
			<?php 
	    	$cor=0;
	    		    	
			foreach($this->objMaterial as $lista):	    	
			$cor++;
            if(($cor%2)==0) $class = 'td_orc_par';
            else $class = 'td_orc';
			?>
			
			<tr >
                <td  class="<?=$class?>" style="text-align: center;">
                   <?=$cor?>                  
                </td>
                <td class="<?=$class?>" align="left" >
                   <?=$lista->descricao."<br>".$lista->descricaochines?>                  
                </td>
                <td  class="<?=$class?>" style="text-align: center;" >
                	<?php 
                	if($this->objEdi==true):
                		?>
                		<a href="javascript:void(0);" onclick="editarRegra(<?=$lista->id?>,'<?=$lista->descricao?>','<?=$lista->descricaochines?>');"><img src="<?=$this->baseUrl()?>/images/edit_orc.gif" width="15" border="0" title="Editar"></a>&nbsp;&nbsp;
                		<a href="javascript:void(0);" onclick="if(confirm('Remover regra?')){window.location='<?=$this->baseUrl()?>/admin/cadastro/removematerial/iddesc/<?=md5($lista->id)?>';};" ><img src="<?=$this->baseUrl()?>/images/window-close.png" width="13" border="0" title="Remover"></a> 
                		<?php
                	endif;
                	?>
                </td>
            </tr>
            
			<?php  endforeach;
			?>
		</table>	
		<?php endif; ?>		
	</div>
</div>		
<script>
	function editarRegra(id,ing,chin){
		document.prepedido.desc.value		= ing;
		document.prepedido.descchines.value		= chin;
		document.prepedido.iddesc.value	= id;
	}
</script>

<div style="display: none">
<!-- Essa caixa quarda textos para ser traduzidos. 
Isso devido ao Gettext nao buscar dentro das tags javascript
 --> 
<?=$this->translate->_("Regra salva com sucesso!")?>
<?=$this->translate->_("Remover regra!")?>
<?=$this->translate->_("Remover")?>
</div>