<!-- Content -->
    <div class="content">   
	<!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a> </li>
                	<li ><a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/referenciacruzada">Referência cruzada</a></li>         
                	<li class="lastB">Códigos</li>
                </ul>
            </div>
        </div>       

        <div class="title"><h5>Códigos</h5></div>

        <div class="widgets">
        	<div class="left" style="margin-top: 10px">
	        	<form action="<?php echo $this->baseUrl(); ?>/admin/cadastro/referenciacruzadacad" method="post" name="busca" class="mainForm">
					<table style="border: 1px solid #d5d5d5;;" >
					    <tr>
					    	<td style="padding: 10px">
					    		Busca:<br>
					    		<div class="styled-select" style="width: 170px">
						    	<select name="buscafabrica" id="buscafabrica" style="width: 212px;">
						    		<option value="0">TODOS</option>
									<?php foreach ($this->objFabricas as $listfab): ?>
									<option value="<?=$listfab->id?>" ><?=$listfab->no_fabricante?></option>
									<?php endforeach; ?>
								</select>
								</div>								
					    	</td>
					    	<td style="padding: 10px">
					    		<br>
						    	<input type="text" name="buscacod" id="buscacod" style="text-transform: uppercase; width: 80px">
								<input type="submit" value="<?=$this->translate->_("Buscar")?>" class="blueBtn">
					    	</td>
						</tr>
					</table>  
				</form>
        	</div>
        	<div class="right" style="text-align: right; padding-top: 10px; width: 30%">
	        	<a href="<?=$this->baseUrl(); ?>/admin/cadastro/referenciacruzada"><?=$this->translate->_("Referência cruzada")?></a> |
	    		<a href="<?=$this->baseUrl(); ?>/admin/cadastro/referenciacruzadarel"><?=$this->translate->_("Cruzamento entre empresas")?></a>
	        </div>
	        
	        <div class="clear"></div>
	        
	        
			<form action="<?php echo $this->baseUrl(); ?>/admin/cadastro/cadcodigoprodfabricas" method="post" name="edit" id="edit"  onsubmit="return validaformedit();" class="mainForm">
			<?php 
			if(!empty($this->objProdutos)) :
			?>
			<div class="widget">
				<table style="width: 100%" class="tableStatic" id="tbcodigos">
	            	<thead>
	                	<tr>
	                        <td ><?=$this->translate->_("Fabricante")?></td>
	                        <td ><?=$this->translate->_("Código")?></td>
	                        <?php if($this->objEdi==1): ?>
	                        <td ><?=$this->translate->_("Tipo")?></td>
	                        <td ><?=$this->translate->_("Opções")?></td>
	                        <?php endif;?>
	                    </tr>
	                </thead>
	                <tbody>
	               
					<?php 
					foreach($this->objProdutos as $lista):
			    	?>
				
					<tr >
		                <td >
		                   <?php echo ($lista->no_fabricante)?>	                   
		                </td>
		                <td style="text-transform: uppercase; ">
		                	<?php if($lista->idcodigo == $this->prodEdit): ?>
		                	<input type='text' name='codigo' id='codigoedit' value='<?=$lista->codigo?>' style="width: 80px" onkeypress='if(event.keyCode == 13){ validaformeditenter(); return false; }'  class="alpha" >
		                	<input type='hidden' name='idcodigo' value='<?=$lista->idcodigo?>' >
		                	<?php else: ?>
		                	<a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/referenciacruzada/buscacod/<?=$lista->codigo?>/fabricamd/<?=md5($lista->idfabricante)?>" ><?=utf8_encode($lista->codigo)?></a>
		                	<?php endif; ?>
		                </td>
		                <?php if($this->objEdi==1): ?>
		                <td style="text-align: left; width: 10%; line-height: 30px">
		                	<?php 
		                	if($lista->idcodigo == $this->prodEdit): 
		                		$checv 	= "";
		                		$checp	= "";
			                	if($lista->principal == 1){
			                		$checp = "checked='checked'";
			                	}
			                	
			                	if($lista->visualizar == 1){
			                		$checv = "checked='checked'";
			                	}
		                	?>
		                	<input <?=$checp?> type='checkbox' name='principal' value='1'> &nbsp; Compras<br />
		                	<input <?=$checv?> type='checkbox' name='visualizar' value='1'> &nbsp;  Vendas 
		                	<?php 
		                	else:
		                		if($lista->principal == 1) echo " C ";
								if($lista->visualizar == 1) echo " V ";
							endif; ?>					
						</td>
		                <td  style="text-align: center;" >
		                <?php if($lista->idcodigo == $this->prodEdit): ?>	
		                	<input type='button' name='principal' value='Salvar' onclick='validaformedit();' class="greenBtn">
		                <?php else: ?>
		                	<a href="<?=$this->baseUrl()?>/admin/cadastro/referenciacruzadacad/proded/<?=$lista->idcodigo?>" ><img src="<?=$this->baseUrl()?>/public/sistema/imagens/icons/middlenav/pencil.png" width="14" border="0" title="Editar"></a> &nbsp;
		                	<a onclick="removeCodigo('<?=$lista->codigo?>','<?=$lista->idcodigo?>');" href="javascript:void(0);"><img src="<?php echo $this->baseUrl(); ?>/public/sistema/imagens/icons/middlenav/close.png" width="14" border="0" title="Remover"></a>
			            <?php endif; ?>
		                </td>
		                <?php endif; ?>
		            </tr>
		            <?php  endforeach; ?>
				</tbody>        
				</table>
				<?php 
			endif;
			?>
			</div>
			</form>
		</div>
	</div>
	
	
<script type="text/javascript">

(function(){
	document.busca.buscafabrica.focus();
})();

function validaform(){
	if(document.cad.codigo.value==""){
		jAlert('O Código do produto não pode ficar em branco!', 'Erro!');
		document.cad.codigo.focus();
		return false; 
	}else if(document.cad.fabrica.value==0){
		jAlert('Selecione o fabricante do produto!', 'Erro!');
		return false; 
	}else{
		return true;	
	}
}

function validaformedit(){
	if(document.getElementById("codigoedit").value==""){
		jAlert('O Código do produto não pode ficar em branco!', 'Erro!');
		document.getElementById("codigoedit").focus();
	}else{
		document.edit.submit();
	}
}

function validaformeditenter(){
	if(document.getElementById("codigoedit").value!=""){
		document.edit.submit();
	}
}

function removeCodigo(codigo,idcodigo){
	jConfirm('Você deseja remover o código '+codigo+'?', 'Confirme', function(r) {
		if(r==true){
			window.location='<?php echo $this->baseUrl(); ?>/admin/cadastro/remcodigoprodfabricas/idcodigo/'+idcodigo;
			
		}
	});
}


</script>