<?php 
// definimos o tipo de arquivo

if($this->tipo==1):
	header("Content-type: application/vnd.oasis.opendocument.spreadsheet");
	// Como será gravado o arquivo
	header("Content-Disposition: attachment; filename=Referencia_cruzada.ods");
else:
	header("Content-type: application/msexcel");
	// Como será gravado o arquivo
	header("Content-Disposition: attachment; filename=Referencia_cruzada.xls");
endif;
?>
<link href="<?php echo $this->baseUrl(); ?>/css/pedidos_imp.css" rel="stylesheet" type="text/css" />
<table width="800" align="center" cellpadding="0" cellspacing="0">
<tr>
	<td colspan="3" align="center">
		<?=$this->translate->_("REFER&Ecirc;NCIA CRUZADA")?>
	</td>
</tr>
<tr>
	<td width="51%" align="left" valign="top">				
		<?php 
			$cont = 0;
			if(!empty($this->objProdutos)) :
        		foreach($this->objProdutos as $lista);
        		?>
				<table align="left" class="mytable"  cellspacing="0" width="98%" align="left">
			         <tr>
			            <th  class="th_canto_orc" align="center" width="50%">
			                <?php echo utf8_encode($lista->fabrica1)?>
			            </th>
			            <th  class="th_orc" align="center" >
			                <?php echo utf8_encode($lista->fabrica2)?>
			            </th>
			        </tr>
			       
				<?php 
				$cor=0;
		    	foreach($this->objProdutos as $lista):
			    	$cont++;
		    		if(($cont%2)==1):
			            $cor++;
				    	if(($cor%2)==0) $class = 'td_orc_par';
			            else $class = 'td_orc';
			            ?>
						<tr >
			                <td  class="<?=$class?>" align="left" style="text-transform: uppercase;">
			                	<?=utf8_encode($lista->codigo1)?>
			                </td>
			                <td  class="<?=$class?>" align="left" style="text-transform: uppercase;">
			                	<?=utf8_encode($lista->codigo2)?>
			                </td>
			            </tr>				            
					<?php  
					endif;
				endforeach; ?>
				</table>
				<?php 
			endif;
			?>
		</td>
		<td >
		&nbsp;
		</td>
		<td width="50%" align="right"  valign="top">			
		<?php 
			$cont = 0;
			if(count($this->objProdutos)>1) :
        		foreach($this->objProdutos as $lista);
        		?>
				<table align="left" class="mytable" cellspacing="0" width="100%" align="right">
			         <tr>
			            <th  class="th_canto_orc" align="center" width="50%">
			                <?php echo utf8_encode($lista->fabrica1)?>
			            </th>
			            <th  class="th_orc" align="center" >
			                <?php echo utf8_encode($lista->fabrica2)?>
			            </th>
			        </tr>					       
				<?php 
				$cor2=0;
		    	foreach($this->objProdutos as $lista):
			    	$cont++;
		    		if(($cont%2)==0):
			    		$cor2++;
				    	if(($cor2%2)==0) $class = 'td_orc_par';
			            else $class = 'td_orc';
			            ?>
						<tr >
			                <td  class="<?=$class?>" align="left" style="text-transform: uppercase;">
			                	<?=utf8_encode($lista->codigo1)?>
			                </td>
			                <td  class="<?=$class?>" align="left" style="text-transform: uppercase;">
			                	<?=utf8_encode($lista->codigo2)?>
			                </td>
			            </tr>				            
					<?php  
					endif;
				endforeach; ?>
				</table>
				<?php 
			endif;
			?>
		</td>
</tr>
</table>