<!-- Content -->
    <div class="content">   
	<!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a> </li>
                	<li ><a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/referenciacruzada">Referência cruzada</a></li>         
                	<li class="lastB">Cruzamento entre empresas</li>
                </ul>
            </div>
        </div>       

        <div class="title">
        	<h5>Códigos</h5>
        	<?php 
    		if(!empty($this->objProdutos)) :
        		foreach($this->objProdutos as $lista); ?>
	        	<div style="float: right; padding: 10px">
					<a href="<?=$this->baseUrl(); ?>/admin/cadastro/referenciacruzadarelxls/buscafabrica/<?=$lista->idfabrica1?>/buscafabrica2/<?=$lista->idfabrica2?>"><img title="MS Excel" src="<?=$this->baseUrl(); ?>/public/sistema/imagens/icons/middlenav/excelDocwhite.png" border="0" width="18" /> </a>
		    		<a target="_blank" href="<?=$this->baseUrl(); ?>/admin/cadastro/referenciacruzadarelimp/buscafabrica/<?=$lista->idfabrica1?>/buscafabrica2/<?=$lista->idfabrica2?>"><img title="Imprimir" src="<?=$this->baseUrl(); ?>/public/sistema/imagens/icons/middlenav/printerwhite.png" border="0" width="18" /> </a>
				</div>
				<?php 
	    	endif;	
	    	?>
        </div>

        <div class="widgets">
        	<div class="left" style="margin-top: 10px; width: 50%">
	        	<form action="<?php echo $this->baseUrl(); ?>/admin/cadastro/referenciacruzadarel" method="post" name="busca" class="mainForm">
					<table style="border: 1px solid #d5d5d5; width: 100%;" >
					    <tr>
					    	<td style="padding: 10px">
					    		Fabricante 1:<br>
					    		<div class="styled-select" style="width: 170px">
						    	<select name="buscafabrica" id="buscafabrica" style="width: 1920px; ">
						    		<?php foreach ($this->objFabricas as $listfab): ?>
									<option value="<?=$listfab->id?>" <?php if($listfab->id == 1) echo 'selected="selected"'; ?>><?=$listfab->no_fabricante?></option>
									<?php endforeach; ?>
								</select>
								</div>									
					    	</td>
					    	<td style="padding: 10px">
					    		Fabricante 2:<br>
					    		<div class="styled-select" style="width: 170px">
						    	<select name="buscafabrica2" id="buscafabrica2" style="width: 192px;">
						    		<?php foreach ($this->objFabricas as $listfab): ?>
									<option value="<?=$listfab->id?>"><?=$listfab->no_fabricante?></option>
									<?php endforeach; ?>
								</select>
								</div>
							</td>
							<td style="padding: 10px">
								<br /><input type="submit" value="<?=$this->translate->_("Gerar")?>" class="greenBtn">
					    	</td>
						</tr>
					</table>  
				</form>
        	</div>
        	<div class="right" style="text-align: right; padding-top: 10px; width: 30%">
	        	<a href="<?=$this->baseUrl(); ?>/admin/cadastro/referenciacruzada"><?=$this->translate->_("Referência cruzada")?></a> |
	    		<a href="<?=$this->baseUrl(); ?>/admin/cadastro/referenciacruzadacad"><?=$this->translate->_("Códigos")?></a>
	        </div>
	        
	        <div class="clear"></div>
	        
	       	<div class="left" style="margin-top: 10px; width: 48%">
			<?php 
			$cont = 0;
			if(!empty($this->objProdutos)) :
        		foreach($this->objProdutos as $lista);
        		?>
        		<div class="widget">
				<table style="width: 100%" class="tableStatic" id="tbcodigos">
	            	<thead>
	                	<tr>
	                        <td ><?php echo utf8_encode($lista->fabrica1)?></td>
	                        <td ><?php echo utf8_encode($lista->fabrica2)?></td>
	                    </tr>	                    
	                </thead>
	                <tbody>
					   
					<?php 
					$cor=0;
			    	foreach($this->objProdutos as $lista):
				    	$cont++;
			    		if(($cont%2)==1):
				            $cor++;
					    	?>
							<tr >
				                <td style="text-transform: uppercase;">
				                	<a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/referenciacruzada/buscacod/<?=$lista->codigo1?>/fabricamd/<?=md5($lista->idfabrica1)?>" ><?=utf8_encode($lista->codigo1)?></a>
				                </td>
				                <td style="text-transform: uppercase;">
				                	<a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/referenciacruzada/buscacod/<?=$lista->codigo2?>/fabricamd/<?=md5($lista->idfabrica2)?>" ><?=utf8_encode($lista->codigo2)?></a>
				                </td>
				            </tr>				            
						<?php  
						endif;
					endforeach; ?>
					</tbody>
				</table>
				</div>
				<?php 
			endif;
			?>
			</div>
			
			<div class="right" style="margin-top: 10px; width: 48%">
				<?php 
				$cont = 0;
				if(count($this->objProdutos)>1) :
	        		foreach($this->objProdutos as $lista);
	        		?>
					<div class="widget">
					<table style="width: 100%" class="tableStatic" id="tbcodigos">
		            	<thead>
		                	<tr>
		                        <td ><?php echo utf8_encode($lista->fabrica1)?></td>
		                        <td ><?php echo utf8_encode($lista->fabrica2)?></td>
		                    </tr>	                    
		                </thead>
		                <tbody>				       
						<?php 
						$cor2=0;
				    	foreach($this->objProdutos as $lista):
					    	$cont++;
				    		if(($cont%2)==0):
					    		$cor2++;
						    	if(($cor2%2)==0) $class = 'td_orc_par';
					            else $class = 'td_orc';
					            ?>
								<tr >
				                <td style="text-transform: uppercase;">
				                	<a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/referenciacruzada/buscacod/<?=$lista->codigo1?>/fabricamd/<?=md5($lista->idfabrica1)?>" ><?=utf8_encode($lista->codigo1)?></a>
				                </td>
				                <td style="text-transform: uppercase;">
				                	<a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/referenciacruzada/buscacod/<?=$lista->codigo2?>/fabricamd/<?=md5($lista->idfabrica2)?>" ><?=utf8_encode($lista->codigo2)?></a>
				                </td>
				            </tr>				            
						<?php  
						endif;
					endforeach; ?>
					</tbody>
				</table>
				</div>
				<?php 
			endif;
			?>
			</div>
		</div>
	</div>		
		
<script type="text/javascript">

(function(){
	document.busca.buscafabrica.focus();
})();




</script>