<div id="siscorpo">
	<div id="sisnavegacao">
		<a href="<?php echo $this->baseUrl(); ?>/admin/painel">HOME</a>&nbsp; 
		<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
		<a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/despesasfiscais">TRIBUTOS</a>&nbsp;
		<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
		<a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/tributocfop">CFOP</a>&nbsp;
		<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp; 
		<a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/tributocst">CST ICMS</a>&nbsp;
		<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp; 
		<b><a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/tributocst">CADASTRO CST ICMS</a></b>
	</div>
	<div id="sistitulo">CADASTRO CST ICMS</div>
    <div id="sisconteudo">    
		<form action="<?php echo $this->baseUrl(); ?>/admin/cadastro/gravatributocst" method="post" name="grava" id="grava">
		<?php foreach ($this->objList as $list); ?>
		<table style="margin-top: 5px">
		    <tr>
		    	<td align="left" width="8%" >
		    		CST: <br>
		    		<input value="<?=$list->csticms?>" type="text" size="5" maxlength="2" name="cst" >
		            <input value="<?=$list->id?>" type="hidden" name="idcst" id="idcst" >
		    	</td>
				<td align="left" width="45%">
		    		Descrição: <br>
		    		<input value="<?=$list->descicms?>" type="text" size="50" name="descricao" >
		    	</td>
				<td align="left" valign="bottom" >
		    		<input type="submit" value="Salvar">
		    	</td>
			</tr>
		</table>
		</form>
	</div>
</div>
		
	