<div id="siscorpo">
	<div id="sisnavegacao">
		<a href="<?php echo $this->baseUrl(); ?>/admin/painel">HOME</a>&nbsp; 
		<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
		<a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/despesasfiscais">TRIBUTOS</a>&nbsp;
		<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp; 
		<a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/produtosncm">NCM</a>&nbsp;
		<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp; 
		<a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/tributocstipi">CST IPI</a>&nbsp;
		<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp; 
		<b><a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/tributocstcadipi">CADASTRO CST IPI</a></b>
	</div>
	<div id="sistitulo">CADASTRO CST IPI</div>
    <div id="sisconteudo">    
		<form action="<?php echo $this->baseUrl(); ?>/admin/cadastro/gravatributocstipi" method="post" name="grava" id="grava">
		<?php foreach ($this->objList as $list); ?>
		<table style="margin-top: 5px" >
		    <tr>
		    	<td align="left" width="8%" >
		    		CST: <br>
		    		<input value="<?=$list->cstipi?>" type="text" size="5" maxlength="2" name="cst" >
		            <input value="<?=$list->id?>" type="hidden" name="idcst" id="idcst" >
		    	</td>
				<td align="left" width="45%" >
		    		Descrição: <br>
		    		<input value="<?=$list->descipi?>" type="text" size="50" name="descricao" >
		    	</td>				
			</tr>
			<tr>
		    	<td align="left" colspan="2">
		    		Tipo: <br>
		    		<input type="radio" name="tipo" value="1" <? if($list->tipo == 1):?> checked="checked" <?php endif; ?>> Tributado<br />
		    		<input type="radio" name="tipo" value="2" <? if($list->tipo == 2):?> checked="checked" <?php endif; ?>> Não Tributado 
		    	</td>
			</tr>
			<tr>
		    	<td align="left" colspan="2" style="padding-top: 20px">
		    		<input type="submit" value="Salvar">
		    	</td>
			</tr>
		</table>
		</form>
	</div>
</div>
		
	