<div id="siscorpo">
	<div id="sisnavegacao">
		<a href="<?=$this->baseUrl(); ?>/admin/painel">HOME</a>&nbsp; 
		<img src="<?=$this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
		<a href="<?=$this->baseUrl(); ?>/admin/cadastro/despesasfiscais">TRIBUTOS</a>&nbsp;
		<img src="<?=$this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp; 
		<b><a href="<?=$this->baseUrl(); ?>/admin/cadastro/tributocfop">CFOP</a></b>
	</div>
	<div id="sistitulo">CFOP</div>
    <div id="sisconteudo">  
		<?php  if($this->objIns==true):?>
		<div style="margin-bottom: 5px; ">
    	<input type="button" class="button" onclick="window.location='<?=$this->baseUrl()?>/admin/cadastro/tributocfopcad'" value="Novo CFOP"></input>
    	</div>
    	<?php endif;?>
    	<div style="text-align: left;">
	        <?php 
        	if (count($this->objList) > 0) :
			?>
			<table class="mytable" >
		         <tr>
		            <th  class="th_canto_orc" align="center" width="10%">
		                ID
		            </th>
		            <th  class="th_orc" align="center" width="15%">
		                CFOP
		            </th>
		            <th  class="th_orc" align="center" width="65%">
		                DESCRIÇÃO
		            </th>
		            <?php if ($this->objEdi==true){  ?>
		            <th  class="th_orc" align="center" width="10%">
		                Op&ccedil;&otilde;es
		            </th>
		            <?php } ?>
		        </tr>		       
			<?php 
			$cor=0;
	    	foreach($this->objList as $lista):
	    	$cor++;
            if(($cor%2)==0) $class = 'td_orc_par';
            else $class = 'td_orc';
			?>			
			<tr >
                <td  class="<?=$class?>" style="text-align: center;">
                   <?php echo substr("000".$cor,-3,3)?>
                </td>
                <td  class="<?=$class?>"  style="text-align: center;">
                   <?=$lista->cfop?>
                </td>
                <td  class="<?=$class?>" align="left" style="text-transform: uppercase;">
                   <?=$lista->descricao?>
                </td>
                <?php if ($this->objEdi==true){  ?>
                <td  class="<?=$class?>" style="text-align: center;">
                	<a href="<?=$this->baseUrl()?>/admin/cadastro/tributocfopcad/idcfop/<?=md5($lista->id)?>" >
                	<img src="<?=$this->baseUrl(); ?>/images/edit_orc.gif" width="15" height="15" border="0" title="Editar" ></a>
                </td>
                <?php  }  ?>
            </tr>            
			<?php  endforeach;
			?>        
			</table>
		</div>
	 	<?php 
		else :
		?>
		<br>
		<center>Nenhum CFOP Cadastrado</center>			
		<?php 
		endif;
		?>
	</div>
</div>
