<div id="siscorpo">
	<div id="sisnavegacao">
		<a href="<?php echo $this->baseUrl(); ?>/admin/painel">HOME</a>&nbsp; 
		<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
		<a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/despesasfiscais">TRIBUTOS</a>&nbsp;
		<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
		<a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/produtosncm">NCM</a>&nbsp;
		<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp; 
		<a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/tributocstpis">CST PIS/PASEP</a>&nbsp;
		<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp; 
		<b><a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/tributocstpiscad">CADASTRO CST PIS/PASEP</a></b>
	</div>
	<div id="sistitulo">CADASTRO CST PIS/PASEP</div>
    <div id="sisconteudo">    
		<form action="<?php echo $this->baseUrl(); ?>/admin/cadastro/gravatributocstpis" method="post" name="grava" id="grava">
		<?php foreach ($this->objList as $list); ?>
		<table style="margin-top: 5px" >
		    <tr>
		    	<td align="left" width="8%" >
		    		CST: <br>
		    		<input value="<?=$list->cstpis?>" type="text" size="5" maxlength="2" name="cst" >
		            <input value="<?=$list->id?>" type="hidden" name="idcst" id="idcst" >
		    	</td>
				<td align="left" width="45%" >
		    		Descrição: <br>
		    		<input value="<?=$list->descpis?>" type="text" size="50" name="descricao" >
		    	</td>				
			</tr>
			<tr>
		    	<td align="left" colspan="2">
		    		Tipo: <br>
		    		<input type="radio" name="tipo" value="1" <? if($list->tipo == 1):?> checked="checked" <?php endif; ?>> Aliquota<br />
		    		<input type="radio" name="tipo" value="2" <? if($list->tipo == 2):?> checked="checked" <?php endif; ?>> Quantidade<br />
		    		<input type="radio" name="tipo" value="3" <? if($list->tipo == 3):?> checked="checked" <?php endif; ?>> Não Tributado<br />
		    		<input type="radio" name="tipo" value="4" <? if($list->tipo == 4):?> checked="checked" <?php endif; ?>> Outros 
		    	</td>
			</tr>
			<tr>
		    	<td align="left" colspan="2" style="padding-top: 20px">
		    		<input type="submit" value="Salvar">
		    	</td>
			</tr>
		</table>
		</form>
	</div>
</div>
		
	