<script src="<?php echo $this->baseUrl(); ?>/public/sistema/js/buscaajax/cadastroVeiculos.js"></script>


<?php 
if($this->flashMessages()){ 
	$mes = explode("|", $this->flashMessages());
	?><script>jAlert("<?php echo $mes[1]?>","<?php echo $mes[0]?>")</script><?php
}

if(count($this->objMontadora)>0){
    foreach ($this->objMontadora as $montadora);    
}
?>


	<div class="content">
       <!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a> </li>
                	<li ><a href="<?php echo $this->baseUrl(); ?>/admin/cadastro/montadoras">Montadoras</a> </li>
                	<li class="lastB">Veículos <?php echo $montadora->nome?></li>         
                </ul>
            </div>
        </div>       
        
        <div class="title"><h5>Veículos <?php echo $montadora->nome?></h5></div>
        
        	        
	        
	    <!-- Busca ------------------------------------------------------ -->
		<div class="widgets" >
			<div class="" style="margin-top: 5px; margin-bottom: 5px; border: 1px solid #d5d5d5; padding: 10px" >  
				<form method="post" name="busca" id="busca" class="mainForm">
					<input type="text" name="veiculo" style="width: 250px" placeholder="Veículo">
    				<input type="button" class="blueBtn" value="Pesquisar" id="btnbusca" >
    				
    				<input type="hidden" name="montadora" value="<?php echo $montadora->id?>">
    				<input type="hidden" name="coluna">
    				<input type="hidden" name="ordem">
    				
    			</form>
    		</div>
    	</div>
			
	        
	    <div class="clear"></div>
		
		<div id="resultado"></div>
	    
	</div>
	
	
	