<!-- Content -->
    <div class="content">   
    	<!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="#">Home</a> </li>
                	<li><a href="<?php echo $this->baseUrl()?>/admin/marketing">Mailing</a></li>
                	<li><a href="<?php echo $this->baseUrl()?>/admin/marketing/mailingnovo">Novo mailing</a></li>
                	<li class="lastB">Enviar mailing</li>         
                </ul>
            </div>
        </div>       
        
        <div class="title"><h5>Enviar mailing</h5></div>
        <div class="widgets" id="resultado" style="text-align: center;">   
        	<img alt="Enviando ..." src="<?php echo $this->baseUrl()?>/public/sistema/imagens/loaders/loader8.gif" alt="" class="p12" />
        	<h3>Eviando E-mails. Aguarde...</h3>
        </div>
    	<div class="fix"></div>
    
    </div>
   