<!-- Content -->
	<div class="content">   

<!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a> </li>
                	<li class="lastB">Erro</li>         
                </ul>
            </div>
        </div>       
        
        <div class="title"><h5>Erro de acesso</h5></div>

        <div class="widgets" style="text-align: center; padding: 30px">
			<img src="<?php echo $this->baseUrl(); ?>/images/forbidden.jpg" width="100" height="100"><br><br>
			<span style="font: bold 14px 'Trebuchet MS', Verdana, Arial, Helvetica, sans-serif; ">
			Voc&ecirc; n&atilde;o tem permiss&atilde;o para acessar essa funcionalidade!
			</span><br />
			<a href="#" onclick="history.go(-2);">Voltar</a>
		</div>
	</div>
		