        <div class="widget">
 			<table style="width: 100%" class="tableStatic">
            	<thead>
                	<tr>
                        <td rowspan="2" style="font-size: 15px; vertical-align: middle"><?php echo $this->translate->_("Invoice")?></td>
                        <td colspan="3" style="font-size: 15px"><?php echo $this->translate->_("Date")?></td>
                        <td colspan="8" style="font-size: 15px"><?php echo $this->translate->_("Values")?></td>
                    </tr>
                    <tr>
                        <td style="border-left: 1px solid #d4d4d4"><?php echo $this->translate->_("Invoice")?></td>
                        <td ><?php echo $this->translate->_("Shipment")?></td>
                        <td ><?php echo $this->translate->_("Rebate")?></td>
                        <td ><?php echo $this->translate->_("Purchase")?></td>
                        <td ><?php echo $this->translate->_("Cost")?></td>
                        <td ><?php echo $this->translate->_("Rebate Forecast")?></td>
                        <td ><?php echo $this->translate->_("Rebate Real")?></td>
                        <td ><?php echo $this->translate->_("SMT Expense")?></td>
                        <td ><?php echo $this->translate->_("% Forecast / Cost")?></td>
                        <td ><?php echo $this->translate->_("% Expenses / Purchase")?></td>
                        <td ><?php echo $this->translate->_("% Expenses / Real")?></td>
                    </tr>
                </thead>
                <tbody>
                <?php
                    foreach($this->objRetono as $lista){
                        ?>
                        <tr>
                            <td style="text-align: center">S<?php echo str_pad($lista->id, 6, '0', STR_PAD_LEFT)?> </td>
                            <?php
                            if($lista->sitInvoice != 0) {
                            ?>
                            <td style="text-align: center"><?php echo $lista->dtInvoice?> </td>
                            <td style="text-align: center"><?php echo $lista->dtEmbarque?> </td>
                            <td style="text-align: center"><?php echo $lista->dtRebate?> </td>
                            <td style="text-align: right"><?php echo number_format($lista->pagtoTotal, 2,",",".")?> </td>
                            <td style="text-align: right"><?php echo number_format($lista->pagtoTotal - $lista->rebate,2,",",".")?> </td>
                            <td style="text-align: right"><?php echo number_format($lista->rebate,2,",",".")?> </td>
                            <td style="text-align: right"><?php echo number_format($lista->rebateEfetivo,2,",",".")?> </td>
                            <td style="text-align: right"><?php echo number_format($lista->despesas,2,",",".")?> </td>
                            <td style="text-align: right"><?php echo number_format(($lista->rebate / ($lista->pagtoTotal - $lista->rebate)) * 100,2,",",".")?> </td>
                            <td style="text-align: right"><?php echo number_format(($lista->despesas / ($lista->pagtoTotal)) * 100,2,",",".")?> </td>
                            <td style="text-align: right"><?php echo number_format(($lista->despesas / $lista->rebateEfetivo) * 100,2,",",".")?> </td>
                            <?php
                            } else {
                            ?>
                            <td style="text-align: center" colspan="11">CANCELLED</td>
                            <?php
                            }
                            ?>
                        </tr>
                        <?php
                    }
                ?>
                </tbody>
			</table>
		</div>