<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <title>Google Maps JavaScript API v3 Example: Geocoding Simple</title>
    <link href="/maps/documentation/javascript/examples/default.css" rel="stylesheet">
    <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script>
      var geocoder;
      var map;
      function initialize() {
        geocoder = new google.maps.Geocoder();
        var latlng = new google.maps.LatLng(-15.78895, -47.836533);
        var mapOptions = {
          zoom: 10,
          center: latlng,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        map = new google.maps.Map(document.getElementById('map_canvas'), mapOptions);

        codeAddress();
      }

      function codeAddress() {
        var address = "Brasília, DF"; //document.getElementById('address').value;
       var address2 = "Taguatinga, DF";
       
        geocoder.geocode( { 'address': address}, function(results, status) {
          if (status == google.maps.GeocoderStatus.OK) {
            map.setCenter(results[0].geometry.location);
            var marker = new google.maps.Marker({
                map: map,
                position: results[0].geometry.location
            });
          } else {
            alert('Geocode was not successful for the following reason: ' + status);
          }
        });

        geocoder.geocode( { 'address': address2}, function(results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
              map.setCenter(results[0].geometry.location);
              var marker = new google.maps.Marker({
                  map: map,
                  position: results[0].geometry.location,
                  title: "ZTL do Brasil Importação e Exportação.\nQI 8 Lotes 45/48 Taguatinga Norte, Taguatinga \nCleiton Silva Barbosa\n61 34337777"
              });
            } else {
              alert('Geocode was not successful for the following reason: ' + status);
            }
          });
      }
    </script>
  </head>
  <body onload="initialize()">
    <div id="map_canvas" style="width: 1000px; height: 600px;"></div>
  </body>
</html>

