
		<div class="widget">
 			<div class="head" style="border-bottom: 0px"><h5 class="iFrames">Produtos</h5></div>
        	<table class="tableStatic" id="txtHint" style="width: 100%">
            	<thead>
                	<tr>
                        <td width="25%">Código</td>
                        <td width="20%">Enviados para análise</td>
                        <td width="20%">Pagos</td>
                    </tr>
                </thead>
                <tbody>
        	   	<?php	
		       	$cont = 0;
		       	$compra = $garantia = $pagos = 0;
		       	//foreach($this->objVendas as $produtos):
		       	foreach ($this->objProdutos as $produtos):
		       		$cont ++;
			       	?> 
			       	<tr>
			       		<td style="text-align: center;" ><?=$produtos->CODIGO?></td>
			       		<td style="text-align: center;" >
			       		<?
			       		echo $qtgarantia = $produtos->qttotal;
			       		$compra += $produtos->qttotal;
			       		?>
			       		</td>
			       		<!-- <td style="text-align: center;" >
			       		<?php 
			       		/* $qtgarantia = 0;
			       		if(count($this->objProdutos)>0):
			       			foreach ($this->objProdutos as $gar):
			       				if($gar->idproduto == $produtos->idproduto): 
			       					$qtgarantia = $gar->qttotal;
			       					$garantia += $gar->qttotal;
			       				endif;
			       			endforeach;
			       		endif;
			       		
			       		echo $qtgarantia; */			       		
			       		?>
			       		
			       		</td>  -->
			       		<td style="text-align: center;" >
			       		<?
			       		if($qtgarantia == 0) $qtpago = "-";
			       		else $qtpago = 0;
			       		if(count($this->objProcede)>0):
			       			foreach ($this->objProcede as $procede):
			       				if($procede->idproduto == $produtos->idproduto): 
			       					$qtpago = $procede->qttotal;
			       					$pagos += $procede->qttotal;
			       				endif;
			       			endforeach;
			       		endif;
			       		
			       		echo $qtpago;
			       		
			       		?></td>
		       		</tr>
		       <?php 
		       endforeach;
		       ?>
		       </tbody>
		       <thead>
                	<tr>
                        <td width="25%" style="font-weight: bold;">Total</td>
                        <td width="20%" style="font-weight: bold;"><?=$compra?></td>
                        <!--  <td width="20%" style="font-weight: bold;"><?=$garantia?></td>  -->
                        <td width="20%" style="font-weight: bold;"><?=$pagos?></td>
                    </tr>
                </thead>
			</table>
		 </div>