<div id="siscorpo">
	<div id="sisnavegacao">
		<a href="<?=$this->baseUrl()?>/admin/painel"><?=$this->translate->_("HOME")?></a>&nbsp; 
		<img src="<?=$this->baseUrl()?>/images/seta.png" width="5" height="7" />&nbsp;
		<a href="<?=$this->baseUrl(); ?>/admin/venda/garantias"><?=$this->translate->_("GARANTIAS")?></a>&nbsp;
		<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
		<b><a href="<?php echo $this->baseUrl(); ?>/admin/venda/dicasop"><?=$this->translate->_("DICAS")?></a></b>
	</div>
	<div id="sistitulo">DICAS</div>
	<div id="sisconteudo">  
		<div style="margin-bottom: 5px">
 			<input type="button" onclick="window.location='dicasopcad'" value="Nova Dica">
	    	<div style="float: right; font-weight: bold;">
		    	<a href="<?php echo $this->baseUrl(); ?>/admin/venda/analiseop"><b>ANÁLISES</b></a>
		  	</div>
 		</div>
		<div>
			<?php if(!empty($this->objDicas)): ?>
	        <table class="mytable" >
	        <tr>
	            <th  class="th_canto_orc" align="center" width="7%">
	                ID
	            </th>
	            <th  class="th_orc" align="center" width="">
	                Título
	            </th>
	            <th  class="th_orc" align="center" width="10%">
	                Op&ccedil;&otilde;es
	            </th>
	        </tr>
			<?php 
				$cor =0;
				foreach ($this->objDicas as $lista){
				$cor++;
	            if(($cor%2)==0) $class = 'td_orc_par';
	            else $class = 'td_orc';
				?>
				
				<tr >
	                <td  class="<?=$class?>" style="text-align: center;" >
	                   <?php echo substr("000".$lista->id,-3,3)?>
	                </td>
	                <td  class="<?=$class?>" align="left" style="text-transform: uppercase;">
	                   <?php echo $lista->descricao?>
	                  
	                </td>
	                
	                <td  class="<?=$class?>" style="text-align: center;">
	                   <a href="<?php echo $this->baseUrl(); ?>/admin/venda/dicasopdet/dica/<?=md5($lista->id)?>" ><img src="<?php echo $this->baseUrl(); ?>/images/visualizar_orc.gif" width="19" height="19" border="0" title="Visualize"></a> 
	                   
	                </td>
	            </tr>
	            
				
				<?php 
				}
			?>
			
			</table>
		</div>
		<?php
		else:
		?>
		<div style="text-align: center; margin-top: 30px">NENHUMA DICA CADASTRADA</div>
		<?php 
		endif;
		?>
		
		<script>
			

			var alertaPadrao = function(titulo, msg, tipo, altura, largura) {
					$('body').append('<a href="#" id="alerta-padrao"></a>');
					$('#alerta-padrao').m2brDialog({
							draggable: true,
							texto: msg,
							tipo: tipo,
							titulo: titulo,
							altura: altura,
							largura: largura,
							botoes: {
								1: {
									label: 'Fechar',
									tipo: 'fechar'
								}
							}									   
					});
					$('#alerta-padrao')
						.click()
						.remove();
			}; // fim alertaPadrao
		</script>
	</div>
</div>