<?php

if(!empty($this->objDicas)):
	foreach ($this->objDicas as $lista);
endif;

?>

<div id="siscorpo">
	<div id="sisnavegacao">
		<a href="<?=$this->baseUrl()?>/admin/painel"><?=$this->translate->_("HOME")?></a>&nbsp; 
		<img src="<?=$this->baseUrl()?>/images/seta.png" width="5" height="7" />&nbsp;
		<a href="<?=$this->baseUrl(); ?>/admin/venda/garantias"><?=$this->translate->_("GARANTIAS")?></a>&nbsp;
		<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
		<a href="<?php echo $this->baseUrl(); ?>/admin/venda/dicasop"><?=$this->translate->_("DICAS")?></a>&nbsp;
		<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
		<b><a href="<?php echo $this->baseUrl(); ?>/admin/venda/dicasopdet/dica/<?=md5($lista->iddicas)?>"><?=$this->translate->_("DETALHA DICA")?></a></b>
	</div>
	<div id="sistitulo">DICAS</div>
	<div id="sisconteudo">  
		<table  width="100%" style="border: 1px solid #000; margin: 6px 0px 6px; padding: 5px" cellspacing="5" cellpadding="10">
			<tr>
				<td width="10%" align="left" colspan="2">
					Título:<br>
				<b><?php echo ($lista->desc); ?></b>
				</td>
			</tr>
			<tr>
				<td  align="left" colspan="2">
				Informações técnicas:<br>
				<?php echo ($lista->info);
				?>
				</td>
			</tr>
			<tr>
				<td  align="left" colspan="2">
				Relação com análises:<br>
				<?php 
				foreach ($this->objDicas as $list):
				?>
					<a target="_black" href="<?php echo $this->baseUrl(); ?>/admin/venda/analiseopdet/analise/<?php echo md5($list->idanalise)?>" >
					- <?php echo ($list->descricao)?></a><br>
					<?php 
				endforeach;
				?>
				</td>
			</tr>
			<tr>
				<td align="left" colspan="2"><br>
				
				<input type="hidden" name="id_analise"  >
				
				<input type="button" onclick="window.location='<?php echo $this->baseUrl(); ?>/admin/venda/dicasopcad/dica/<?php echo md5($lista->iddicas)?>'" name="salvar" value="Editar" >
				</td>
			</tr>
        </table>
        	
        
		<script>
			function editaAnalise(id,desc,tipo){
				document.cad.diag.value=desc;
				document.cad.tipo.value=tipo;
				document.cad.id_analise.value=id;

			}
					
			function validaCampos(){
				if(document.cad.diag.value==""){
					alertaPadrao('Erro!', 'O campo DIAGNÓSTICO não pode ficar em branco!', 'erro', 110, 300);
					return false;
				}
			}

			var alertaPadrao = function(titulo, msg, tipo, altura, largura) {
					$('body').append('<a href="#" id="alerta-padrao"></a>');
					$('#alerta-padrao').m2brDialog({
							draggable: true,
							texto: msg,
							tipo: tipo,
							titulo: titulo,
							altura: altura,
							largura: largura,
							botoes: {
								1: {
									label: 'Fechar',
									tipo: 'fechar'
								}
							}									   
					});
					$('#alerta-padrao')
						.click()
						.remove();
			}; // fim alertaPadrao
		</script>
	</div>
</div>
	