<script src="<?=$this->baseUrl()?>/public/javascript/janelamodal.js"></script>
<script src="<?=$this->baseUrl()?>/public/javascript/nfe/nfegarantiacancela.js"></script>
<script src="<?=$this->baseUrl()?>/public/javascript/jquery-1.4.min.js" type="text/javascript"></script>

<link type="text/css" rel="stylesheet" href="<?=$this->baseUrl()?>/public/css/modalestilo.css" ></link>

<style>
#divbarra{
	border:1px solid #DFDFDF;
	text-align:left;	
}

#barraprogresso{
	width:1px; 
	background: -moz-linear-gradient(top, #00bfbf, #007d7d);
	background: -webkit-gradient(linear, left top, left bottom, from(#00bfbf), to(#007d7d)) repeat-X;
	background-color: #00bfbf;
	height:20px;
}
</style>


<?php 
	if(count($this->objCli)>0):
		foreach ($this->objCli as $listPed);
	endif;
?>

<div class="content">
	<!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a> </li>
                	<li ><a href="<?php echo $this->baseUrl(); ?>/admin/venda/garantias">Garantias</a></li>
                	<?php if($this->objNivel == 2): ?>
                	<li ><a href="<?php echo $this->baseUrl(); ?>/admin/venda/garantiasnfe">Garantias pagas</a></li>
                	<?php endif; ?>
                	<li class="lastB"><?="NFe".substr("000000".$listPed->id,-6,6);?></li>         
                </ul>
            </div>
        </div>       
        
        <div class="title"><h5><?="NFe".substr("000000".$listPed->id,-6,6);?></h5></div>
        
        <div class="widget first" >
            <div class="head" style="margin-top: -10px"><h5 class="iUser">Informações do cliente</h5></div>
            <div class="body">
				<table >
			    <tr>
	                <td width="12%">Cliente:</td>
	                <td colspan="3"><b><?=$listPed->empresa?></b></td>                
	            </tr>
	            <tr>
	                <td>CPF/CNPJ:</td>
	                <td width="35%"><b><?=$listPed->cnpj?></b></td>
	                <td width="12%">RG/INSC:</td>
	                <td ><b><?=$listPed->inscricao?></b></td>
	            </tr>
	            <tr>
	                <td>Cidade:</td>
	                <td><b><?=$listPed->cidade?></b></td>
	                <td>Estado:</td>
	                <td ><b><?=$listPed->uf?></b></td>
	            </tr>
	            <tr>
	            	<td>Pais:</td>
	                <td ><b>Brasil</b></td>
	                <td>Transportadora:</td>
	                <td ><b><?=$listPed->transportadora?></b></td>
	            </tr>
	            <tr>
	            	<td style="vertical-align: top;">Nat Op:</td>
	                <td colspan="3"><b><?=$listPed->cfop?> - <?=$listPed->naturezaop?></b></td>                
	            </tr>	            
	        </table>
        </div>
    </div>
        <?php 
        if(count($this->objProd)>0): 
			$qtprods = count($this->objProd);
		?>
		<div class="widget">
 			<div class="head" style="border-bottom: 0px"><h5 class="iFrames">Produtos</h5></div>
        	<table class="tableStatic" id="txtHint" style="width: 100%">
            	<thead>
                	<tr>
                        <td width="10%">Id</td>
                        <td width="25%">Código</td>
                        <td width="40%">Descrição</td>
                        <td width="">Qt</td>
                        <td width="">Preço</td>
                    </tr>
                </thead>
                <tbody>
                
		        <?php 
		        $cor = 0;
		        $total_pedido = $total_prod = 0;
		        $v_estoque = 0;
		        foreach ($this->objProd as $produtos):
		        	$cor++;
			        if(($cor%2)==0) $class = 'td_orc_par';
			        else $class = 'td_orc';
					?>
					<tr >
		                <td  class="<?=$class?>" style="text-align: center;" >
		                   <?=$cor?>
		                </td>
		                <td class="<?=$class?>" style="text-align: center;" >
		                	<?=$produtos->codigo?>
		                </td>
		                <td class="<?=$class?>" style="text-align: left;" >
		                	<?=$produtos->descricao?>
		                </td>                
		                <td  class="<?=$class?>" style="text-align: center;" >
		                	<?=$produtos->qt?>
		                </td>
		                <td class="<?=$class?>" style="text-align: right;" >
		                	<?=number_format($produtos->preco,2,",",".")?>
		                </td>	                	                           
		            </tr>  
		        	<?php
			        $total_prod 	+= $produtos->qt;
			        $total_pedido 	+= $produtos->preco;
		        endforeach;?>
	        </tbody>
	    </table>
	    </div>
	    
	    
	   	<div class="widget">
 			<div class="head" ><h5 class="iView">Informações adicionais</h5></div>
        	<div class="body">
        	<table  style="width: 100%">
            	<tr>
			    	<td  class="td" align="left" colspan="7" >
			    		<table style="width: 100%">
			            	<tr>
					            <td   align="left"  valign="middle" style="padding-top: 5px; padding-bottom: 5px" colspan="4">
					              Frete:<br>
					              <span style="font-size:14px; font-weight:bold;">
		                    	  <?=number_format($listPed->frete,2,",",".")?>
		                    	  </span>
					            </td>
					    	</tr>
				            <tr>
					            <td   align="left"  valign="middle" style="padding-top: 5px; padding-bottom: 5px" >
					               Base do calculo ICMS:<br>
		                    	   <span style="font-size:14px; font-weight:bold;">
			                    	   	<?=number_format(0,2,',','.')?>				                    
		                    	   </span>
					            </td>
					            <td   align="left"  valign="middle" style="padding-top: 5px; padding-bottom: 5px" >
					               	Base do calculo ICMS S.T.:<br>
		                    	   	<span style="font-size:14px; font-weight:bold;">
		                    	   		<?=number_format(0,2,',','.')?>
		                    	   	</span>
					            </td>
					            <td   align="left"  valign="middle" style="padding-top: 5px; padding-bottom: 5px" >
					               Valor total do IPI:<br>
		                    	   <span style="font-size:14px; font-weight:bold;">
		                    	        <?=number_format(0,2,',','.')?>     
		                    	   </span>
					            </td>
					            <td   align="left"  valign="middle" style="padding-top: 5px; padding-bottom: 5px" >
					              Valor Total dos produtos:<br>
		                    	  <span style="font-size:14px; font-weight:bold;" id="spantotal">
		                    	  	<?=number_format($listPed->totalprodutos,2,',','.')?>
		                    	  </span>
					            </td>
					    	</tr>
							    <tr >
						    		<td   align="left"  valign="middle" style="padding-top: 5px; padding-bottom: 5px" >
						               Valor ICMS:<br>
			                    	   <span style="font-size:14px; font-weight:bold;">
			                    	   		<?=number_format(0,2,',','.')?>
			                    	   </span>
						            </td>
						            <td   align="left"  valign="middle" style="padding-top: 5px; padding-bottom: 5px" >
						               Valor ICMS S.T.:<br>
			                    	   <span style="font-size:14px; font-weight:bold;">
			                    	   	<?=number_format(0,2,',','.')?>
			                    	   </span>
						            </td>
						            <td   align="left"  valign="middle" style="padding-top: 5px; padding-bottom: 5px" >
						               Outras despesas:<br>
			                    	   <span style="font-size:14px; font-weight:bold;"><?=number_format("0",2,',','.')?></span>
						            </td>
						            <td   align="left"  valign="middle" style="padding-top: 5px; padding-bottom: 5px" >
						              Valor Total da nota:<br>
			                    	  <span style="font-size:14px; font-weight:bold; color:#0010e1;" >
			                    	  <?=number_format($listPed->totalnota,2,',','.')?>
			                    	  </span>		                    	  
						            </td>
					            </tr>
				       		</table>  
			            </td>		            		            
				    </tr>	
		        <tr>
			    	<td  class="td" align="left" colspan="7" >
			            <table  style="width: 100%" >
				            <tr>
					            <td style="width: 250px;">
					            	<span style="font-weight: bold;">Transporte:</span><br />
					            	<table>
					            		<tr>
					            			<td>Qt pacotes:</td>
					            			<td>
						            			<b><?=$listPed->especie?></b>
					            			</td>
					            		</tr>
					            		<tr>
					            			<td>Por conta:</td>
					            			<td>
					            				<b><? if($listPed->tipofrete == 0) echo "EMITENTE"; else echo "DESTINATÁRIO"; ?></b>
								            </td>
					            		</tr>
					            		<tr>
					            			<td>Peso Bruto:</td>
					            			<td>
					            				<b><?=number_format($listPed->pesobruto,2,',','.')?></b>
					            			</td>
					            		</tr>
					            		<tr>
					            			<td>Peso Líquido:</td>
					            			<td>
					            				<b><?=number_format($listPed->pesoliquido,2,',','.')?></b>
					            			</td>
					            		</tr>
					            		<tr>
					            			<td>Placa/UF:</td>
					            			<td>
					            				<b><?=$listPed->transplaca?></b>
					            			</td>
					            		</tr>
					            		<tr>
					            			<td>ANTT:</td>
					            			<td>
					            				<b><?=$listPed->transantt?></b>
					            			</td>
					            		</tr>
					            	</table>					            	
					            </td>
					            <td style="vertical-align: top;">
					            	<span >Total de pe&ccedil;as:</span><br>
				                    <span style="font-size:14px; font-weight:bold; text-align:right;" >
				                    	<?=$total_prod?>
				                    </span>
					            </td>	
					    	</tr>
						    <tr >
					    		<td  align="left" valign="top" colspan="2" >
					                <br />Observa&ccedil;&otilde;es da NFe<br>
					                <b><?=$listPed->obs;?></b>
					            </td>
				            </tr>
				            <tr >
					    		<td  align="left" valign="top" colspan="2" >
					    			<div style="border: 1px solid #ccc; padding: 10px; line-height: 15px">
					                XML da NFe<br>
					                <a href="<?=$this->baseUrl()?>/public/nfe/nfe/producao/enviadas/aprovadas/<?=$listPed->chave?>-nfe.xml"><?=$listPed->chave?>-nfe.xml</a>
					                <br />
					                Danfe<br>
					                <a href="<?=$this->baseUrl()?>/public/nfe/nfe/producao/pdf/<?=$listPed->chave?>.pdf"><?=$listPed->chave?>.pdf</a>
					                </div>
					            </td>
				            </tr>
			       		</table>  
		            	</td>
		            </tr>			               
			        		
			    </table>	
			 </div>
		</div>
			
		<div style="margin-top: 10px">
	    	<?php 
	    	if($this->objNivel == 2):
		    	if(strtotime($listPed->data.'+1 days') > strtotime(date("Y-m-d H:i:s"))):
		    	?>
		    	<input type="button" class="redBtn" value="Cancelar NFe" onclick="if(document.getElementById('divcanc').style.display=='none'){document.getElementById('divcanc').style.display='block'}"> <br />
		    	<div style="border: 1px solid #ccc; padding: 10px; line-height: 15px; display: none; margin-top: 5px" id="divcanc">
		    	Motivo:<br />
		    	<textarea name="obscancela" id="obscancela" tabindex="412" cols="50" rows="2" class="borda_text"></textarea> <br />
		    	<input  value="Enviar" janela="#jconfirma"  type="button" name="janelamodal" class="basicBtn">
		    	
		    	<input type="hidden" name="ped" value="<?=$listPed->id?>">
		    	<input type="hidden" name="idnfe" value="<?=$listPed->id?>">
		    	</div>
		    	<?php 
		    	endif;
		    endif;
	    	?>
	    </div>  
			    
		<?php endif;?>	   
	</div>

<!-- Janelas modal -->
<div class="window" id="jconfirma" style="width: 320px; height: 110px" >
    <span class="titulojanela" >Cancelar Garantia?</span><br />
    <span class="subtitulojanela">O estoque será ajustado de acordo com a garantia</span>
    <div style="margin-top: 30px; text-align: center;">
	    <a class="botaoconfirma" href="javascript:void(0)" 
		onclick="criaModal({'largura': 340, 'altura': 110, 'titulo':'Cancelando garantia','subtitulo':'Cancelando NFe...','btsim':0,'clicksim':'','btnao':0,'tpj':'1'}); cancelarGarantia();"> &nbsp; Sim &nbsp; </a> &nbsp;
		<a class="botaocancela" href="javascript:void(0)" onclick="$('#mascara').hide(); $('.window').hide();"> Cancelar </a>
    </div> 
</div>

<!-- mascara para cobrir o site -->
<div id="mascara"></div>