	<div class="content">
	
	<!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a> </li>
                	<li ><a href="<?php echo $this->baseUrl(); ?>/admin/venda/garantias">Garantias</a></li>
                	<li class="lastB">Garantias pagas</li>         
                </ul>
            </div>
        </div>       

        
        <div class="title"><h5>Garantias Pagas</h5></div>

		<div class="widgets" >
        	<!-- Busca -->
        	<div style="margin-top: 5px; margin-bottom: 5px" >   
	        	<?php 
				if($this->objIns==true):
					?>
				    <input type="button" class="basicBtn" onclick="window.location='<?=$this->baseUrl(); ?>/admin/venda/garantiasgeranfe'" value="Novo Pagamento" />
		    		<?php		    	
			    endif; 
			    ?>              
            </div>
            
            <!-- Busca -->
        	<div  style="margin-bottom: 5px; border: 1px solid #d5d5d5; padding: 10px" >    
				<form action="" method="post" name="busca" id="busca" class="mainForm" >
					Cliente:<br>
					<div class="styled-select" style="width: 250px;" >
					<select name="buscacli" id="buscacli" onchange="document.busca.submit();" style="width: 272px">
						<option value="0">Selecione</option>
						<?php foreach ($this->objCli as $listcli): ?>
							<option value="<?=$listcli->ID?>"><?=$listcli->EMPRESA ?></option>
						<?php endforeach; ?>
					</select>
					</div>
				</form>
			</div>
            
        </div>
        

      	<?php 
		if ( count($this->objList) > 0) :
		?>		
		<div class="widget first">
 			<table style="width: 100%" class="tableStatic">
            	<thead>
                	<tr>
                        <td width="10%">NF-e</td>
                        <td width="25%">Cliente</td>
                        <td width="15%">Data</td>
                        <td width="10%">Opções</td>
                    </tr>
                </thead>
                <tbody>
                
				<?php 
				foreach($this->objList as $lista):
		    	?>
					<tr >
		                <td style="text-align: center;" >
		                   <?="NFe".substr("000000".$lista->id,-6,6);?>
		                </td>
		                <td align="left" > 
		                   <?=($lista->empresa)?>                  
		                </td>
		                <td style="text-align: center;"> 
		                   <?=substr($lista->data,8,2)."/".substr($lista->data,5,2)."/".substr($lista->data,0,4)?>                  
		                </td>
		                <td style="text-align: center;" >
		                	<a href="<?=$this->baseUrl(); ?>/admin/venda/garantiasnfeview/nfe/<?=md5($lista->id)?>"><img src="<?=$this->baseUrl(); ?>/public/sistema/imagens/icons/middlenav/magnify.png" width="16" border="0" title="Visualizar"></a>                	
		                </td>                
		            </tr>
            	<?php  
            	endforeach; 
            	?>
            	</tbody>        
			</table>
		</div>	
		<div style="margin-top: 20px">
			<?php 
			if ( count($this->objList) > 0) :
				echo $this->objList;
			endif;
		    ?>
		</div>
		<?php 
		else :
		?>
		<div class="widget first" style="padding: 15px; border-top: 1px solid #d5d5d5;"> 
 			Nenhuma garantia Encontrada
		</div>	
		<?php 
		endif;
		?>
	</div>