<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>ZTL Brasil - www.ztlbrasil.com.br </title>
	<link href="<?=$this->baseUrl()?>/public/sistema/imagens/ztl.ico" rel="shortcut icon" type="image/x-ico"/>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="rolamentos, cubo de roda, rolamento, embreagem, embreagens, ponta de eixo, pontas de eixo, bomba dagua, bombas dagua, roda, scania, homocinetica, homocineticas, transmissoes" />
	
	<link href="<?=$this->baseUrl()?>/public/sistema/css/mainprint.css" rel="stylesheet" type="text/css" />
</head>

<body onload="window.print()">

	<div class="content" style="width: 800px; margin: 0 auto">
	    
        <div class="title">
        	<h5 >Lista de preço resumida</h5>
        	<div style="text-align: right; padding: 7px">
        	www.ztlbrasil.com.br - Gerado em <?=date("d/m/Y")?>
        	</div>
        </div>
		
		<?php 
		$count = 0;
		$coluna1 = "";
		$coluna2 = "";
		$coluna3 = "";
		foreach ($this->objProdutos as $produtos){
			if($produtos->situacao == 0){
				$count++;
			
				if(empty($produtos->PRECO_UNITARIO)) $preco = 0;
				else $preco = $produtos->PRECO_UNITARIO;
		
				if($count == 1):
					$coluna1 .= "<tr><td>".$produtos->CODIGO."</td><td style='text-align: right;'>".number_format($preco,2,",",".")."</td></tr>";
				elseif($count == 2):
					$coluna2 .= "<tr><td>".$produtos->CODIGO."</td><td style='text-align: right;'>".number_format($preco,2,",",".")."</td></tr>";
				elseif($count == 3):
					$coluna3 .= "<tr><td>".$produtos->CODIGO."</td><td style='text-align: right;'>".number_format($preco,2,",",".")."</td></tr>";
					$count = 0;
				endif;
			}
		}
		?>
				
		<div class="widgets">
		<div style="width: 30%; margin-right: 5%" class="left">
			<div class="widget" style="margin-top: 0px">
	 			<table style="width: 100%;" class="tableStatic">
	            	<thead>
	                	<tr>
	                        <td width="">Código</td>
	                        <td width="">Valor (R$)</td>
	                    </tr>
	                </thead>
	                <tbody>
	                	<?=$coluna1?>
	                </tbody>
	          	</table>
			</div>
		</div>
		
		<div style="width: 30%;" class="left" >
			<div class="widget" style="margin-top: 0px">
	 			<table style="width: 100%" class="tableStatic">
	            	<thead>
	                	<tr>
	                        <td width="" >Código</td>
	                        <td width="">Valor (R$)</td>
	                    </tr>
	                </thead>
	                <tbody>
	                	<?=$coluna2?>
	                </tbody>
	          	</table>
			</div>
		</div>
				
		<div style="width: 30%;" class="right">
			<div class="widget" style="margin-top: 0px">
	 			<table style="width: 100%" class="tableStatic">
	            	<thead>
	                	<tr>
	                        <td width="">Código</td>
	                        <td width="">Valor (R$)</td>
	                    </tr>
	                </thead>
	                <tbody>
	                	<?=$coluna3?>
	                </tbody>
	          	</table>
			</div>
		</div>   
		
		</div>      
	</div>
</body>
</html>