<script src="<?php echo $this->baseUrl(); ?>/public/sistema/js/buscaajax/vendaProdutos.js"></script>
<script type="text/javascript">
	
</script>
<?php 
	foreach ($this->objCliente as $listCli);
	foreach ($this->objTrib as $listTri);
	foreach ($this->objEmail as $listEmail);	
?>

<style>
a.dcontexto:hover span{ 
  top:2em;
  left: 0px;  
}
</style>

<div class="content">
<!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="#">Home</a> </li>
                	<li><a href="<?php echo $this->baseUrl()?>/admin/venda/pedidos">Pedidos</a></li>
                	<li><a href="<?php echo $this->baseUrl()?>/admin/venda/pedorcamentos">Orçamentos</a></li>
                	<li class="lastB">Ajuste de orçamento</li>         
                </ul>
            </div>
        </div>       

        
        <div class="title"><h5>Ajuste de orçamento</h5>
        <div style="width: 20px; float: right; padding: 10px 10px 0px 0px;">
        	<a href="<?=$this->baseUrl()?>/admin/venda/pedidosorcimp/ped/<?=md5($this->objPed)?>" target="_blank"><img src="<?=$this->baseUrl()?>/public/sistema/imagens/icons/middlenav/printerwhite.png" width="18" border="0" title="Imprimir"></a>&nbsp;&nbsp;
        </div>
        </div>
            
        <div class="widget first">
            <div class="head" style="margin-top: -10px"><h5 class="iUser">Informações do cliente</h5></div>
            <div class="body">
				<table class="borda" style="width: 100%; border-spacing: 5px">
		            <tr>
		                <td width="20%">Cliente:</td>
		                <td colspan="3"><b><?=$listCli->EMPRESA?></b></td>
		            </tr>
		            <tr>
		                <td>Raz&atilde;o Social:</td>
		                <td colspan="3"><b><?=$listCli->RAZAO_SOCIAL?></b></td>
		            </tr>
		            <tr>
		                <td>CPF/CNPJ:</td>
		                <td width="35%"><b><?=$listCli->CPF_CNPJ?></b></td>
		                <td width="15%">RG/INSC:</td>
		                <td ><b><?=$listCli->RG_INSC?></b></td>
		            </tr>
		            <tr>
		                <td>Cidade:</td>
		                <td width="35%"><b><?=($listCli->CIDADE)?></b></td>
		                <td width="15%">Estado:</td>
		                <td ><b><?=($listCli->nome)?></b></td>
		            </tr>
		            <tr>
		                <td>Transportadora:</td>
		                <td width="35%" colspan="3"><b><?=$listCli->trans?></b></td>
		            </tr>
		            <tr>
		            	<td style="vertical-align: top;">Nat Op:</td>
		                <td colspan="3"><b><?php if(isset($listTri)) echo $listTri->cfop." - ".substr($listTri->desccfop,0,60)?></b></td>                
		            </tr>
		            <tr>
		                <td>Email NFe:</td>
		                <td><b><?=$listEmail->EMAIL?></b></td>
		                <td>Contato NFe:</td>
		                <td><b><?=$listEmail->NOME_CONTATO?></b></td>
		            </tr>
		        </table>
			</div>
		</div>	
			
			
		<form name="prepedido" id="prepedido" action="<?php echo $this->baseUrl(); ?>/admin/venda/pedidosentorc" method="post" class="mainForm">
	    <input type="hidden" name="ped" value="<?=$this->objPed;?>">
	    <input type="hidden" name="pedcli" value="<?=$listCli->idcli;?>">
	    <input type="hidden" name="pedidosnovo" value="true">
	    
		<div class="widget">
 			<div class="head" style="border-bottom: 0px;"><h5 class="iFrames">Produtos</h5></div>
        	<table class="tableStatic" style="width: 100%;">
            	<thead>
                	<tr>
                        <td width="3%">Id</td>
                        <td width="">Código</td>
                        <td width="10%">NCM</td>
                        <td width="5%">QT</td>
                        <?php if($this->objCmv == 1){ ?>
                        <td width="5%">Custo</td>
                        <?php } ?>
                        <td width="">Tabela</td>
                        <td width="">Preço NF</td>
                        <td width="">IPI</td>
                        <td width="">ICMS</td>
                        <td width="">ICMS-ST</td>
                        <td width="">MVA</td>
                        <td width="">Preço prod</td>
                        <td width="">Preço Total</td>
                        <td >Opções</td>
                    </tr>
                </thead>
                <tbody>
		        <?php 
		        
		        $markupmin = $markup = 0;		        
		        $cor=0;
		        $total_pedido = $ipi = $precoOrig = 0;
		        $total_pedido_liquido = 0;

		        $arrId = "";
		        $total_prod = $pesoliquido = $totalcusto = 0;
		        foreach ($this->objPend as $listaProd):
		        	$arrId .=  $listaProd->ID.";";
		        	$cor++;

		        	//-- valor unitario normal --------------------------------------
		        	$valor_unitario = $listaProd->PRECO_UNITARIO;
		        	$valor_unitario = (!empty($listCli->desc1)) ? $valor_unitario - (($listCli->desc1 / 100)*$valor_unitario) : $valor_unitario;
		        	$valor_unitario = (!empty($listCli->desc2)) ? $valor_unitario - (($listCli->desc2 / 100)*$valor_unitario) : $valor_unitario;
		        	$valor_unitario = (!empty($listCli->desc3)) ? $valor_unitario - (($listCli->desc3 / 100)*$valor_unitario) : $valor_unitario;
		        	$valor_unitario = (!empty($listCli->desc4)) ? $valor_unitario - (($listCli->desc4 / 100)*$valor_unitario) : $valor_unitario;
		        	$valor_unitario = (!empty($listCli->desc5)) ? $valor_unitario - (($listCli->desc5 / 100)*$valor_unitario) : $valor_unitario;
		        	
		        	//-- valor com desconto promocional -----------------------------
		        	$valor_unitario = (!empty($listaProd->promo) and $listaProd->valor_promo!='' and $listaProd->valor_promo!=0) ? $listaProd->valor_promo : $valor_unitario;
		        	
		        	//-- valor com desconto percentual ------------------------------
		        	$valor_unitario = (!empty($listaProd->promo) and $listaProd->valor_desc!='' and $listaProd->valor_desc!=0) ? $valor_unitario - (($listCli->valor_desc / 100)*$valor_unitario): $valor_unitario;
		        					
					$valor_unitario = round($valor_unitario * 100) / 100; 
					
					//-- markups ---------------------------------------
					$markupmin 	+= (!empty($listaProd->makupmin)) ? $listaProd->makupmin * $listaProd->qttotal : 100 * $listaProd->qttotal;
					$markup 	+= (!empty($listaProd->makup)) ? $listaProd->makup * $listaProd->qttotal : 100 * $listaProd->qttotal;
										
			        ?>
			        <tr >
			        	<td  style="text-align: center;" ><span style="color:#FF0000;"><?=$cor?>*</span></td>
		                <td  style="text-align: center;" >
		                    <a href="javascript:void(0);" class="dcontexto" >
		                		<?=$listaProd->CODIGO?>
		                    	<span style="width: 250px"><?=($listaProd->DESCRICAO)?></span>		                    
		                	</a>
		                </td>
		                <td  style="text-align: center;" ><span style="color: #999"><?=$listaProd->ncm." ".$listaProd->ncmex?></span></td>
		                <td  style="text-align: center;" ><?=$listaProd->qttotal?><input type="hidden" name="<?=$listaProd->ID?>" value="<?=$listaProd->qttotal?>"></td>
		                <?php if($this->objCmv == 1){ ?>			               
			                <td  style="text-align: right;">
			                    <?php			                    
			                    echo number_format($listaProd->custo,2,',','.');
			                    $totalcusto += $listaProd->custo*$listaProd->qttotal;			                    
			                    ?>
			                </td>
			          	<?php } ?> 
		                		               
		                <td  style="text-align: right;"><?=number_format($listaProd->PRECO_UNITARIO,3,',','.')?></td>
		                <td  style="text-align: right;"><?=number_format($valor_unitario,3,',','.')?></td>
		                <td  style="text-align: right;" >
		                    <span style="color: #999">
			                    <?php 
			                    $ipiprod = 0;
			                    if($listTri->semipi==false){
									$ipiprod = ($valor_unitario*$listaProd->ipi)/100;
			                    	echo number_format($ipiprod,2,',','.');	
			                    	echo " (".number_format($listaProd->ipi,2,',','.')."%)";
			                    }else{
			                    	echo number_format(0,2,',','.');
			                    	echo " (0,00%)";
			                    } ?>
		                    </span>
		                </td>
		                <td  style="text-align: right;" >
		                	<span style="color: #999">
			                    <?php 
			                    if($listTri->usevendaicms==true){
			                    	echo number_format((($valor_unitario)*$listTri->vendaicms)/100,2,',','.');
			                    	echo " (".number_format($listTri->vendaicms,2,',','.')."%)";
			                    }else{
			                    	echo number_format(0,2,',','.');
			                    	echo " (0,00%)";
			                    }			                    
			                    ?>
		                    </span>
		                </td>
		                <td  style="text-align: center;" ><span style="color: #999">
		                <?php 		        
			                $bicms	= $valor_unitario;
			                $vicms	= ($bicms*$listTri->vendaicms)/100;
			                 
			                if($listTri->usectm==true){
				                /*-- Regra valida somente para o estado do  Mato Grosso, para alguns casos especiais ---------*/
				                if(($listTri->vendaicmsdest!=0) and ($listTri->usevendaicmsdest==true)){
					                $vst	= (($ipiprod+$bicms)*$listTri->ctm)/100;
					                $bst	= ($vicms+$vst)/($listTri->vendaicmsdest/100);
				                }else{
					                $bst	= 0;
					                $vst	= 0;
				                }
			                }else{
				                if(($listTri->vendaicmsdest!=0) and ($listTri->usevendaicmsdest==true)){
					                $bst	= $ipiprod+$bicms + ((($ipiprod+$bicms)*$listTri->vendast)/100);
					                $vst	= (($bst*$listTri->vendaicmsdest)/100) - $vicms;
				                }else{
					                $bst	= 0;
					                $vst	= 0;
				                }
			                }
			                
			                if($listTri->usevendaicmsdest==true){
			                	$perc = ($vst*100)/$bicms;
			                	echo number_format($vst,2,',','.')." (".number_format($perc,2,',','.')."%)";
			                }else{
			                	echo number_format(0,2,',','.')." (0,00%)";
			                }					    
					    ?>
	                	
		                </span></td>
		                <td  style="text-align: center;" ><span style="color: #999"><?php echo number_format($listTri->vendast,2,',','.')?>%</span></td>
		                <td  style="text-align: right;"><b>
		                <?php 
		                	$valorprod = 0;
		                	$valorprod = $valor_unitario+$ipiprod+$vst;
		                	echo number_format(($valorprod),3,',','.');		                	
		                ?></b>
		                </td>
		                <td  style="text-align: right;"><b><?=number_format(($listaProd->qttotal*$valorprod),3,',','.')?></b></td>
		                <td  style="text-align: center;" >
		                    <a href="#" class="remProdpend" rel="<?=$listaProd->idpend;?>" ><img src="<?=$this->baseUrl(); ?>/public/sistema/imagens/icons/middlenav/close.png" title="Remover" width="13"  border="0"></a>
		                </td>		                
		            </tr>
			        <?php
			       			        
			        $total_prod 			+= $listaProd->qttotal;
			        $total_pedido 			+= $listaProd->PRECO_UNITARIO*$listaProd->qttotal;
			        $total_pedido_liquido 	+= $listaProd->qttotal*$valor_unitario;
			        
			        if(($listaProd->ipi!=0) and ($listTri->semipi==false)): //--Se IPI nao for zero, e se perfil fiscal obriga ter ipi -----------------
			        	$ipi				+= (($listaProd->qttotal*$valor_unitario)*$listaProd->ipi)/100;
			        endif;
			        
			        $peso = 0;
			        $peso = str_replace(",", ".", $listaProd->PESO);
			        $pesoliquido += $listaProd->qttotal*$peso;
			        
		        endforeach;
		          		        
		        foreach ($this->objList as $listaProd):
		       		$arrId .=  $listaProd->id_prod.";";
		        	$cor++;
		            		            		            
		            //--Calcula valor produto----------------------------------
		           	
		        	//-- valor unitario normal --------------------------------------
		        	$valor_unitario = $listaProd->PRECO_UNITARIO;
		        	$valor_unitario = (!empty($listCli->desc1)) ? $valor_unitario - (($listCli->desc1 / 100)*$valor_unitario) : $valor_unitario;
		        	$valor_unitario = (!empty($listCli->desc2)) ? $valor_unitario - (($listCli->desc2 / 100)*$valor_unitario) : $valor_unitario;
		        	$valor_unitario = (!empty($listCli->desc3)) ? $valor_unitario - (($listCli->desc3 / 100)*$valor_unitario) : $valor_unitario;
		        	$valor_unitario = (!empty($listCli->desc4)) ? $valor_unitario - (($listCli->desc4 / 100)*$valor_unitario) : $valor_unitario;
		        	$valor_unitario = (!empty($listCli->desc5)) ? $valor_unitario - (($listCli->desc5 / 100)*$valor_unitario) : $valor_unitario;
		        	 
		        	//-- valor com desconto promocional -----------------------------
		        	$valor_unitario = (!empty($listaProd->promo) and $listaProd->valor_promo!='' and $listaProd->valor_promo!=0) ? $listaProd->valor_promo : $valor_unitario;
		        	 
		        	//-- valor com desconto percentual ------------------------------
		        	$valor_unitario = (!empty($listaProd->promo) and $listaProd->valor_desc!='' and $listaProd->valor_desc!=0) ? $valor_unitario - (($listCli->valor_desc / 100)*$valor_unitario): $valor_unitario;
		        	 
		        	//-- valor com preco alterado ------------------------------
		        	$valor_unitario = (!empty($listaProd->preco_alt)) ? $listaProd->preco_alt : $valor_unitario;
		        	
					$valor_unitario = round($valor_unitario * 100) / 100; 

					$markupmin 	+= (!empty($listaProd->markupmin)) ? $listaProd->markupmin * $listaProd->qt : 100 * $listaProd->qt;
					$markup 	+= (!empty($listaProd->markup)) ? $listaProd->markup * $listaProd->qt : 100 * $listaProd->qt;
					
			        ?>
			        
			        <tr >
			        	<td  style="text-align: center;" ><?=$cor?></td>
		                <td  style="text-align: center;" >
		                    <a href="javascript:void(0);" class="dcontexto" >
		                		<?=$listaProd->CODIGO?>
		                    	<span style="width: 300px"><?=($listaProd->DESCRICAO)?></span>		                    
		                	</a>
		                </td>
		                <td  style="text-align: center;" ><span style="color: #999"><?=$listaProd->ncm." ".$listaProd->ncmex?></span></td>
		                <td  style="text-align: center;" >
		                	<a href="javascript:void(0);" rel="<?php echo $listaProd->ID?>" class="qtprod" ><?=$listaProd->qt?></a>		                	
		                	<input style="display: none" type="text" size="5" name="editqt_<?=$listaProd->ID?>" value="<?=$listaProd->qt?>" class="inteiro edicaoqt">
		                	<input type="hidden" name="<?=$listaProd->ID?>" value="<?=$listaProd->qt?>">	                    
		                </td>		
		                <?php if($this->objCmv == 1){ ?>			               
			                <td  style="text-align: right;">
			                    <?php 
			                    echo number_format($listaProd->custo,2,',','.');
			                    $totalcusto += $listaProd->custo*$listaProd->qt;
			                    ?>
			                </td>
			          	<?php } ?>               
		                <td  style="text-align: right;">
		                    <?php
		                    echo number_format($listaProd->PRECO_UNITARIO,3,',','.');
		                    ?>
		                </td>
		                
		                <td  style="text-align: right;">
			                <?php 
		                	if($this->objNivel==0): 
		                		echo number_format($valor_unitario,3,',','.');
		                	else:
		                	?>
			                <a href="#" class="vlprod" rel="<?=$listaProd->idprorc?>" ><?=number_format($valor_unitario,2,',','.')?></a>
			                <input style="display: none" type="text" name="editvl_<?=$listaProd->idprorc?>" id="<?php echo $listaProd->idprorc?>" value="<?=number_format($valor_unitario,2,',','.')?>" class="moeda edicaovl">
			                <?php 
		                	endif;
		                	if($listaProd->preco_alt!=""):
		                	?>
			                <input type="hidden" name="pendvl_<?=$listaProd->ID?>" value="<?=$valor_unitario?>" >
			                <?php 
			                endif;
			                ?>
		                </td>
		                <td  style="text-align: right;" >
		                    <span style="color: #999">
			                    <?php 
			                    $ipiprod = 0;
			                    if($listTri->semipi==false){
									$ipiprod = ($valor_unitario*$listaProd->ipi)/100;
			                    	echo number_format($ipiprod,2,',','.');	
			                    	echo " (".number_format($listaProd->ipi,2,',','.')."%)";
			                    }else{
			                    	echo number_format(0,2,',','.');
			                    	echo " (0,00%)";
			                    } ?>
		                    </span>
		                </td>
		                <td  style="text-align: right;" >
		                	<span style="color: #999">
			                    <?php 
			                    if($listTri->usevendaicms==true){
			                    	echo number_format((($valor_unitario)*$listTri->vendaicms)/100,2,',','.');
			                    	echo " (".number_format($listTri->vendaicms,2,',','.')."%)";
			                    }else{
			                    	echo number_format(0,2,',','.');
			                    	echo " (0,00%)";
			                    } 
			                    
			                    ?>
		                    </span>
		                </td>
		                <td  style="text-align: center;" ><span style="color: #999">
		                <?php 		        
			                $bicms	= $valor_unitario;
			                $vicms	= ($bicms*$listTri->vendaicms)/100;
			                 
			                if($listTri->usectm==true){
				                /*-- Regra valida somente para o estado do  Mato Grosso, para alguns casos especiais ---------*/
				                if(($listTri->vendaicmsdest!=0) and ($listTri->usevendaicmsdest==true)){
					                $vst	= (($ipiprod+$bicms)*$listTri->ctm)/100;
					                $bst	= ($vicms+$vst)/($listTri->vendaicmsdest/100);
				                }else{
					                $bst	= 0;
					                $vst	= 0;
				                }
			                }else{
				                if(($listTri->vendaicmsdest!=0) and ($listTri->usevendaicmsdest==true)){
					                $bst	= $ipiprod+$bicms + ((($ipiprod+$bicms)*$listTri->vendast)/100);
					                $vst	= (($bst*$listTri->vendaicmsdest)/100) - $vicms;
				                }else{
					                $bst	= 0;
					                $vst	= 0;
				                }
			                }
			                
			                if($listTri->usevendaicmsdest==true){
			                	$perc = ($vst*100)/$bicms;
			                	echo number_format($vst,2,',','.')." (".number_format($perc,2,',','.')."%)";
			                }else{
			                	echo number_format(0,2,',','.')." (0,00%)";
			                }
					    
					    ?>
	                	
	               
		                </span></td>
		                <td  style="text-align: center;" ><span style="color: #999"><?php echo number_format($listTri->vendast,2,',','.')?>%</span></td>
		                <td  style="text-align: right;"><b>
		                <?php 
		                	$valorprod = 0;
		                	$valorprod = $valor_unitario+$ipiprod+$vst;
		                	echo number_format(($valorprod),3,',','.');
		                	
		                ?></b></td>
		                <td  style="text-align: right;"><b><?=number_format(($listaProd->qt*$valorprod),3,',','.')?></b></td>
		                <td  style="text-align: center;" >
		                    <a href="#" class="remProduto" rel="<?=$listaProd->idprorc;?>" ><img src="<?php echo $this->baseUrl(); ?>/public/sistema/imagens/icons/middlenav/close.png" title="Remover" width="13"  border="0"></a>
		                </td>		                
		            </tr>
			        <?php
			        $total_prod 			+= $listaProd->qt;
			        $total_pedido 			+= $listaProd->PRECO_UNITARIO*$listaProd->qt;
			        $total_pedido_liquido 	+= $listaProd->qt*$valor_unitario;
			        if(($listaProd->ipi!=0) and ($listTri->semipi==false)): //--Se IPI nao for zero, e se perfil fiscal obriga ter ipi -----------------
			        	$ipi				+= (($listaProd->qt*$valor_unitario)*$listaProd->ipi)/100;
			        endif;
			        $peso = 0;
			        $peso = str_replace(",", ".", $listaProd->PESO);
			        $pesoliquido += $listaProd->qt*$peso;
		        endforeach;
			    //onkeyup="buscaProdlista(this.value);"
		        ?>
		         <tr>
                    <td  class="td" align="left" colspan="4" >
                    	<input type="hidden" name="promo" id="promo" >
		                <input style="text-transform: uppercase; width: 80px" type="text" name="codigo" id="codigo">		                
		            	<input type="hidden" name="qtprod" id="qtprod" >
		                <input type="text" style="width: 50px" name="qt" id="qt" >	                
		            </td>
		            <td  class="td" style="text-align: center;" colspan="8" style="color:#FF0000; font-weight: bold;">
		            	<input type="hidden" name="arrId" id="arrId" value="<?=$arrId?>">
		               <div id="resultado" ></div>
		            </td>		            
		        </tr>
		        </tbody>
            </table>
     	</div>    
        <?php 		        
        $bicms	= $total_pedido_liquido;
        $vicms	= ($total_pedido_liquido*$listTri->vendaicms)/100;
       		        
        if($listTri->usectm==true):
        	/*-- Regra valida somente para o estado do  Mato Grosso, para alguns casos especiais ---------*/
        	if(($listTri->vendaicmsdest!=0) and ($listTri->usevendaicmsdest==true)):
		        $vst	= (($ipi+$total_pedido_liquido)*$listTri->ctm)/100; 
		        $bst	= ($vicms+$vst)/($listTri->vendaicmsdest/100);				        	        
		    else:
		    	$bst	= 0;
		        $vst	= 0;
		    endif;		
        else:
	        if(($listTri->vendaicmsdest!=0) and ($listTri->usevendaicmsdest==true)):
		        $bst	= $ipi+$total_pedido_liquido + ((($ipi+$total_pedido_liquido)*$listTri->vendast)/100);
		        $vst	= (($bst*$listTri->vendaicmsdest)/100) - $vicms;
		    else:
		    	$bst	= 0;
		        $vst	= 0;
		    endif;
		endif;
	    			    
	    $vltotalnota	=	$total_pedido_liquido+$ipi+$vst;
	    
        ?>
		<div class="widget">
 			<div class="head" ><h5 class="iView">Informações adicionais</h5></div>
        	<div class="body">
                <table style="width: 100%; border-spacing: 7px ">     
                	<tr>
			            <td   align="left"  valign="middle" style="padding-top: 5px; padding-bottom: 5px" >
			               Base do calculo ICMS:<br>
                    	   <span style="font-size:14px; font-weight:bold;">
	                    	   	<?php if($listTri->usevendaicms==true): ?>
			                    <?=number_format($total_pedido_liquido,2,',','.')?>
			                    <?php else: ?>
			                    <?=number_format(0,2,',','.')?>
			                    <?php endif;?>
                    	   </span>
			            </td>
			            <td   align="left"  valign="middle" style="padding-top: 5px; padding-bottom: 5px" >
			               	Base do calculo ICMS S.T.:<br>
                    	   	<span style="font-size:14px; font-weight:bold;">
                    	   		<?php if($listTri->usevendaicmsdest==true): ?>
			                    <?=number_format($bst,2,',','.')?>
			                    <?php else: ?>
			                    <?=number_format(0,2,',','.')?>
			                    <?php endif;?>
                    	   	</span>
			            </td>
			            <td   align="left"  valign="middle" style="padding-top: 5px; padding-bottom: 5px" >
			               Valor total do IPI:<br>
                    	   <span style="font-size:14px; font-weight:bold;">
                    	        <?php if($listTri->semipi==false): ?>
			                    <?=number_format($ipi,2,',','.')?>
                    	   		<?php else: ?>
			                    <?=number_format(0,2,',','.')?>
			                    <?php endif;?>     
                    	   </span>
			            </td>
			            <td   align="left"  valign="middle" style="padding-top: 5px; padding-bottom: 5px" >
			              Valor Total dos produtos:<br>
                    	  <span style="font-size:14px; font-weight:bold; "><?=number_format($total_pedido_liquido,2,',','.')?></span>
			            </td>
			    	</tr>
				    <tr >
			    		<td   align="left"  valign="middle" style="padding-top: 5px; padding-bottom: 5px" >
			               Valor ICMS:<br>
                    	   <span style="font-size:14px; font-weight:bold;">
                    	   		<?php if($listTri->usevendaicms==true): ?>
			                    <?=number_format($vicms,2,',','.')?>
			                    <?php else: ?>
			                    <?=number_format(0,2,',','.')?>
			                    <?php endif;?>
                    	   </span>
			            </td>
			            <td   align="left"  valign="middle" style="padding-top: 5px; padding-bottom: 5px" >
			               Valor ICMS S.T.:<br>
                    	   <span style="font-size:14px; font-weight:bold;">
                    	   		<?php if($listTri->usevendaicmsdest==true): ?>
			                    <?=number_format($vst,2,',','.')?>
			                    <?php else: ?>
			                    <?=number_format(0,2,',','.')?>
			                    <?php endif;?>
                    	   </span>
			            </td>
			            <td   align="left"  valign="middle" style="padding-top: 5px; padding-bottom: 5px" >
			               Outras despesas:<br>
                    	   <span style="font-size:14px; font-weight:bold;"><?=number_format("0",2,',','.')?></span>
			            </td>
			            <td   align="left"  valign="middle" style="padding-top: 5px; padding-bottom: 5px" >
			              Valor Total da nota:<br>
                    	  <span style="font-size:14px; font-weight:bold; color:#0010e1;">
                    	  <?php
                    	  if(!empty($listPed->frete)) $vltotalnota += $listPed->frete;
                    	  if(!empty($listPed->seguro)) $vltotalnota += $listPed->seguro;
                    	  if(!empty($listPed->desconto)) $vltotalnota -= $listPed->desconto;
                    	  
                    	  echo number_format($vltotalnota,2,',','.')?>
                    	  </span>
			            </td>
		            </tr>
	       			<tr>			            
			            <td align="left"  valign="top" colspan="2">
			            
				            Prazo <span style="color:#FF0000;">*</span>: <b>
			               	<?php if($listCli->prazo1 != '') echo $listCli->prazo1;?> &nbsp; 
			               	<?php if($listCli->prazo2 != '') echo $listCli->prazo2;?> &nbsp; 
			               	<?php if($listCli->prazo3 != '') echo $listCli->prazo3;?> &nbsp; 
			               	<?php if($listCli->prazo4 != '') echo $listCli->prazo4;?> &nbsp; 
			               	<?php if($listCli->prazo5 != '') echo $listCli->prazo5;?>
			               	</b>					               
			           		<input type="hidden" name="prazo1" class="borda_input" size="3" onkeypress="mascara_num(this)" value="<?php if($listCli->prazo1 != '') echo $listCli->prazo1;?>">
			                <input type="hidden" name="prazo2" class="borda_input" size="3" onkeypress="mascara_num(this)" value="<?php if($listCli->prazo2 != '') echo $listCli->prazo2;?>">
			                <input type="hidden" name="prazo3" class="borda_input" size="3" onkeypress="mascara_num(this)" value="<?php if($listCli->prazo3 != '') echo $listCli->prazo3;?>">
			                <input type="hidden" name="prazo4" class="borda_input" size="3" onkeypress="mascara_num(this)" value="<?php if($listCli->prazo4 != '') echo $listCli->prazo4;?>">
			                <input type="hidden" name="prazo5" class="borda_input" size="3" onkeypress="mascara_num(this)"  onblur="document.prepedido.obs.focus();" value="<?php if($listCli->prazo5 != '') echo $listCli->prazo5;?>">
			            
			            	<br /><br />
			            	
			               	Observa&ccedil;&otilde;es<br>
					        <textarea name="obs" id="obs" style="width: 80%"></textarea>
		            	</td>
		            	<td style="padding-top: 20px">			                    
			                <?php 
			                
			                $makupdesejado 		= ($markup > 0) ? $markup/$total_prod : 0;
			                $makupmindesejado 	= ($markupmin > 0) ? $markupmin/$total_prod : 0;
			                $totalmarkup 		= ($total_pedido_liquido > 0) ? ($total_pedido_liquido/$totalcusto)*100-100 : 0;
			                
			                $validaprecos = 1;
			                $validaprecos = ($totalmarkup >= $makupmindesejado) ? 1 : 0;
			                
			                //$validaprecos = ($totalmarkup >= $makupmindesejado) ? "salvarorc" : "salvarorcb";
			                
			                
			                ?>
			                
			                <?php if($this->objCmv == 1): ?>				                
		                    Custo total:<br>
		                    <span style="font-size:14px; font-weight:bold;"><?=number_format($totalcusto,2,',','.')?></span><br>
		                    Média markup:<br>
		                    <span style="font-size:14px; font-weight:bold;"><?php if($totalcusto !=0) { echo number_format(($total_pedido_liquido/$totalcusto)*100-100,2,',','.'); }?></span><br>
		                    Markup mínimo:<br>
		                    <span style="font-size:14px; font-weight:bold;"><?php if($makupmindesejado !=0) { echo number_format($makupmindesejado,2,',','.'); }?></span><br>
		                    <?php endif; ?>
			                
			            </td>
			            <td >			                    
		                    <span >Total de pe&ccedil;as:</span><br>
		                    <span style="font-size:14px; font-weight:bold; text-align:right;" ><?=$total_prod?></span><br /><br />		                    
		                    Valor Total bruto:<br>
		                    <span style="font-size:14px; font-weight:bold;">R$ <?=number_format($total_pedido,3,',','.')?></span><br>			                    
			            </td>			            
			        </tr>
				</table>            
	    </div>
    </div>	
      	
    <div style="margin-top: 10px">    
    	<?php if($validaprecos == 1){ ?>        
		<input type="button" id="salvarorc" class="greenBtn" value="Gerar Pedido">
		<?php }else{?>
		<input type="button" id="salvarorcb" class="redBtn" value="Pedido não autorizado">
		<br />Orçamento com valores abaixo do permitido. Revise os preços dos produtos!
		<?php } ?>
	</div>
	
	<div style="margin-top: 10px">
    	<span style="color:#FF0000;">*</span> <i>Produtos pendentes de outras compras.</i>
        Deseja remover todos? <input type="button" value="Sim" class="basicBtn" id="confPendencias">
	</div>	
	</form>
</div>

