<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>ZTL Brasil - www.ztlbrasil.com.br </title>
	<link href="<?=$this->baseUrl()?>/public/images/ztl_favicon1.ico" rel="shortcut icon" type="image/x-ico"/>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="rolamentos, cubo de roda, rolamento, embreagem, embreagens, ponta de eixo, pontas de eixo, bomba dagua, bombas dagua, roda, scania, homocinetica, homocineticas, transmissoes" />
	
	<link href="<?=$this->baseUrl()?>/public/css/estiloimpressao.css" rel="stylesheet" type="text/css" />
</head>

<?php 
	foreach ($this->objCliente as $listCli);
	foreach ($this->objTrib as $listTri);
	//onload="window.print()"
?>
<body >
<div id="siscorpo">
	<div id="sistopo">ORÇAMENTO Nº <?=$listCli->idped?>
		<div style="float: right;"><?=$listCli->dtvenda?></div>
	</div>
	<div id="sistitulo">INFORMAÇÕES DO CLIENTE</div>
    <div id="sisconteudo">
    	<div>
			<table width="100%" style="border: 1px solid;" cellspacing="7">
	            <tr>
	                <td width="20%">Cliente:</td>
	                <td colspan="3"><b><?=$listCli->EMPRESA?></b></td>
	            </tr>
	            <tr>
	                <td>Raz&atilde;o Social:</td>
	                <td colspan="3"><b><?=$listCli->RAZAO_SOCIAL?></b></td>
	            </tr>
	            <tr>
	                <td>CPF/CNPJ:</td>
	                <td width="35%"><b><?=$listCli->CPF_CNPJ?></b></td>
	                <td width="15%">RG/INSC:</td>
	                <td ><b><?=$listCli->RG_INSC?></b></td>
	            </tr>	  
	            <tr>
	            	<td style="vertical-align: top;">Nat Op:</td>
	                <td colspan="3"><b><?=$listTri->cfop." - ".substr($listTri->desccfop,0,60)?></b></td>                
	            </tr>   
	        </table>
        </div>
       
        <div id="sisconteudo">
        	<table class="mytable" >
        		<tr>
		        	<th  class="th_orc" style="text-align: center;" width="">
		                ID
		            </th>
		            <th  class="th_orc" style="text-align: center;" width="">
		                Codigo
		            </th>
		            <th  class="th_orc" style="text-align: center;" width="">
		                NCM
		            </th>
		            <th  class="th_orc" style="text-align: center;" width="">
		                QT
		            </th>
		            <th  class="th_orc" style="text-align: center;" width="">
		                Tabela
		            </th>
		            <th  class="th_orc" style="text-align: center;" width="">
		                Preço NF
		            </th>
		            <th  class="th_orc" style="text-align: center;" width="">
		                IPI
		            </th>
		            <th  class="th_orc" style="text-align: center;" width="">
		                ICMS
		            </th>
		            <th  class="th_orc" style="text-align: center;" width="">
		                ICMS-ST
		            </th>
		            <th  class="th_orc" style="text-align: center;" width="">
		                MVA
		            </th>
		            <th  class="th_orc" style="text-align: center;" width="">
		                Unit prod
		            </th>
		            <th  class="th_orc" style="text-align: center;" width="">
		                Pre&ccedil;o Total
		            </th>		                        
		        </tr>
		   
		        <?php 
		        $cor=0;
		        $total_pedido = 0;
		        $total_pedido_liquido = 0;
		        
		        foreach ($this->objPend as $listaProd):
		        	$cor++;
		            if(($cor%2)==0) $class = 'td_orc_par';
		            else $class = 'td_orc';
		            
		            if(!empty($listaProd->promo)): 
						if(($listaProd->valor_promo!='') and ($listaProd->valor_promo!=0)): 
		                	$valor_unitario = $listaProd->valor_promo;
		                
		                elseif(($listaProd->valor_desc!='') and ($listaProd->valor_desc!=0)):
		                    $valor_unitario = $listaProd->PRECO_UNITARIO;
		                    
		                    $valor_unitario = $valor_unitario - (($listCli->desc1 / 100)*$valor_unitario);
		                    $valor_unitario = $valor_unitario - (($listCli->desc2 / 100)*$valor_unitario);
		                    $valor_unitario = $valor_unitario - (($listCli->desc3 / 100)*$valor_unitario);
		                    $valor_unitario = $valor_unitario - (($listCli->desc4 / 100)*$valor_unitario);
		                    $valor_unitario = $valor_unitario - (($listCli->desc5 / 100)*$valor_unitario);
		                
		                    $valor_unitario = $valor_unitario - (($listCli->valor_desc / 100)*$valor_unitario);
			            else:
			                $valor_unitario = $listaProd->PRECO_UNITARIO;
			                $valor_unitario = $valor_unitario - (($listCli->desc1 / 100)*$valor_unitario);
			            	$valor_unitario = $valor_unitario - (($listCli->desc2 / 100)*$valor_unitario);
			                $valor_unitario = $valor_unitario - (($listCli->desc3 / 100)*$valor_unitario);
			                $valor_unitario = $valor_unitario - (($listCli->desc4 / 100)*$valor_unitario);
			                $valor_unitario = $valor_unitario - (($listCli->desc5 / 100)*$valor_unitario);
						endif;
		            else:
		                $valor_unitario = $listaProd->PRECO_UNITARIO;
		                $valor_unitario = $valor_unitario - (($listCli->desc1 / 100)*$valor_unitario);
		            	$valor_unitario = $valor_unitario - (($listCli->desc2 / 100)*$valor_unitario);
		                $valor_unitario = $valor_unitario - (($listCli->desc3 / 100)*$valor_unitario);
		                $valor_unitario = $valor_unitario - (($listCli->desc4 / 100)*$valor_unitario);
		                $valor_unitario = $valor_unitario - (($listCli->desc5 / 100)*$valor_unitario);
		               
					endif;
					
					$valor_unitario = round($valor_unitario * 100) / 100; 
		            
			        ?>
			       <tr >
			        	<td class="<?=$class?>" style="text-align: center;" ><?=$cor?>*</td>
		                <td class="<?=$class?>" style="text-align: center;" ><?=$listaProd->CODIGO?></td>
		                <td class="<?=$class?>" style="text-align: center;" ><span style="color: #999"><?=$listaProd->ncm." ".$listaProd->ncmex?></span></td>
		                <td class="<?=$class?>" style="text-align: center;" ><?=$listaProd->qttotal?></td>		               
		                <td class="<?=$class?>" style="text-align: right;"><?=number_format($listaProd->PRECO_UNITARIO,3,',','.')?></td>
		                <td class="<?=$class?>" style="text-align: right;"><?=number_format($valor_unitario,3,',','.')?></td>
		                <td class="<?=$class?>" style="text-align: right;" >
		                    <span style="color: #999">
			                    <?php 
			                    $ipiprod = 0;
			                    if($listTri->semipi==false){
									$ipiprod = ($valor_unitario*$listaProd->ipi)/100;
			                    	echo number_format($ipiprod,2,',','.');	
			                    	echo " (".number_format($listaProd->ipi,2,',','.')."%)";
			                    }else{
			                    	echo number_format(0,2,',','.');
			                    	echo " (0,00%)";
			                    } ?>
		                    </span>
		                </td>
		                <td class="<?=$class?>" style="text-align: right;" >
		                	<span style="color: #999">
			                    <?php 
			                    if($listTri->usevendaicms==true){
			                    	echo number_format((($valor_unitario)*$listTri->vendaicms)/100,2,',','.');
			                    	echo " (".number_format($listTri->vendaicms,2,',','.')."%)";
			                    }else{
			                    	echo number_format(0,2,',','.');
			                    	echo " (0,00%)";
			                    } 
			                    
			                    ?>
		                    </span>
		                </td>
		                <td class="<?=$class?>" style="text-align: center;" ><span style="color: #999">
		                <?php 		        
			                $bicms	= $valor_unitario;
			                $vicms	= ($bicms*$listTri->vendaicms)/100;
			                 
			                if($listTri->usectm==true){
				                /*-- Regra valida somente para o estado do  Mato Grosso, para alguns casos especiais ---------*/
				                if(($listTri->vendaicmsdest!=0) and ($listTri->usevendaicmsdest==true)){
					                $vst	= (($ipiprod+$bicms)*$listTri->ctm)/100;
					                $bst	= ($vicms+$vst)/($listTri->vendaicmsdest/100);
				                }else{
					                $bst	= 0;
					                $vst	= 0;
				                }
			                }else{
				                if(($listTri->vendaicmsdest!=0) and ($listTri->usevendaicmsdest==true)){
					                $bst	= $ipiprod+$bicms + ((($ipiprod+$bicms)*$listTri->vendast)/100);
					                $vst	= (($bst*$listTri->vendaicmsdest)/100) - $vicms;
				                }else{
					                $bst	= 0;
					                $vst	= 0;
				                }
			                }
			                
			                if($listTri->usevendaicmsdest==true){
			                	$perc = ($vst*100)/$bicms;
			                	echo number_format($vst,2,',','.')." (".number_format($perc,2,',','.')."%)";
			                }else{
			                	echo number_format(0,2,',','.')." (0,00%)";
			                }
					    
					    ?>
	                	
	               
		                </span></td>
		                <td class="<?=$class?>" style="text-align: center;" ><span style="color: #999"><?php echo number_format($listTri->vendast,2,',','.')?>%</span></td>
		                <td class="<?=$class?>" style="text-align: right;"><b>
		                <?php 
		                	$valorprod = 0;
		                	$valorprod = $valor_unitario+$ipiprod+$vst;
		                	echo number_format(($valorprod),3,',','.');
		                	
		                ?></b>
		                </td>
		                <td class="<?=$class?>" style="text-align: right;"><b><?=number_format(($listaProd->qttotal*$valorprod),3,',','.')?></b></td>
		            </tr>
			        <?php
					
			        $total_prod 			+= $listaProd->qttotal;
			        $total_pedido 			+= $listaProd->PRECO_UNITARIO*$listaProd->qttotal;
			        $total_pedido_liquido 	+= $listaProd->qttotal*$valor_unitario;
			        if(($listaProd->ipi!=0) and ($listTri->semipi==false)): //--Se IPI nao for zero, e se perfil fiscal obriga ter ipi -----------------
			       		$ipi				+= (($listaProd->qttotal*$valor_unitario)*$listaProd->ipi)/100;
			        endif;
			        $peso = 0;
			        $peso = str_replace(",", ".", $listaProd->PESO);
			        $pesoliquido += $listaProd->qttotal*$peso;
			        
		        endforeach;
		        
		        foreach ($this->objList as $listaProd):
		        	$arrId .=  $listaProd->id_prod.";";
		        	$cor++;
		            if(($cor%2)==0) $class = 'td_orc_par';
		            else $class = 'td_orc';
		            		            
		           	//--Calcula valor produto----------------------------------
		           	
		            if(!empty($listaProd->promo)): 
						if(($listaProd->valor_promo!='') and ($listaProd->valor_promo!=0)): 
		                	$valor_unitario = $listaProd->valor_promo;
		                
		                elseif(($listaProd->valor_desc!='') and ($listaProd->valor_desc!=0)):
		                    $valor_unitario = $listaProd->PRECO_UNITARIO;
		                    
		                    $valor_unitario = $valor_unitario - (($listCli->desc1 / 100)*$valor_unitario);
		                    $valor_unitario = $valor_unitario - (($listCli->desc2 / 100)*$valor_unitario);
		                    $valor_unitario = $valor_unitario - (($listCli->desc3 / 100)*$valor_unitario);
		                    $valor_unitario = $valor_unitario - (($listCli->desc4 / 100)*$valor_unitario);
		                    $valor_unitario = $valor_unitario - (($listCli->desc5 / 100)*$valor_unitario);
		                
		                    $valor_unitario = $valor_unitario - (($listCli->valor_desc / 100)*$valor_unitario);
			            else:
			                $valor_unitario = $listaProd->PRECO_UNITARIO;
			                $valor_unitario = $valor_unitario - (($listCli->desc1 / 100)*$valor_unitario);
			            	$valor_unitario = $valor_unitario - (($listCli->desc2 / 100)*$valor_unitario);
			                $valor_unitario = $valor_unitario - (($listCli->desc3 / 100)*$valor_unitario);
			                $valor_unitario = $valor_unitario - (($listCli->desc4 / 100)*$valor_unitario);
			                $valor_unitario = $valor_unitario - (($listCli->desc5 / 100)*$valor_unitario);
						endif;
		            else:
		                $valor_unitario = $listaProd->PRECO_UNITARIO;
		                $valor_unitario = $valor_unitario - (($listCli->desc1 / 100)*$valor_unitario);
		            	$valor_unitario = $valor_unitario - (($listCli->desc2 / 100)*$valor_unitario);
		                $valor_unitario = $valor_unitario - (($listCli->desc3 / 100)*$valor_unitario);
		                $valor_unitario = $valor_unitario - (($listCli->desc4 / 100)*$valor_unitario);
		                $valor_unitario = $valor_unitario - (($listCli->desc5 / 100)*$valor_unitario);
		               
					endif;
					
					$valor_unitario = round($valor_unitario * 100) / 100; 
		    				            
			        ?>
			        <tr >
			        	<td class="<?=$class?>"  style="text-align: center;" ><?=$cor?></td>
		                <td class="<?=$class?>"  style="text-align: center;" ><?=$listaProd->CODIGO?></td>
		                <td class="<?=$class?>"  style="text-align: center;" ><span style="color: #999"><?=$listaProd->ncm." ".$listaProd->ncmex?></span></td>
		                <td class="<?=$class?>"  style="text-align: center;" ><?php echo $listaProd->qt?></td>		               
		                <td class="<?=$class?>"  style="text-align: right;"><?=number_format($listaProd->PRECO_UNITARIO,3,',','.')?></td>
		                <td class="<?=$class?>"  style="text-align: right;"><?php echo number_format($valor_unitario,3,',','.')?></td>
		                <td class="<?=$class?>"  style="text-align: right;" >
		                    <span style="color: #999">
			                    <?php 
			                    $ipiprod = 0;
			                    if($listTri->semipi==false){
									$ipiprod = ($valor_unitario*$listaProd->ipi)/100;
			                    	echo number_format($ipiprod,2,',','.');	
			                    	echo " (".number_format($listaProd->ipi,2,',','.')."%)";
			                    }else{
			                    	echo number_format(0,2,',','.');
			                    	echo " (0,00%)";
			                    } ?>
		                    </span>
		                </td>
		                <td class="<?=$class?>"  style="text-align: right;" >
		                	<span style="color: #999">
			                    <?php 
			                    if($listTri->usevendaicms==true){
			                    	echo number_format((($valor_unitario)*$listTri->vendaicms)/100,2,',','.');
			                    	echo " (".number_format($listTri->vendaicms,2,',','.')."%)";
			                    }else{
			                    	echo number_format(0,2,',','.');
			                    	echo " (0,00%)";
			                    } 
			                    
			                    ?>
		                    </span>
		                </td>
		                <td class="<?=$class?>"  style="text-align: center;" ><span style="color: #999">
		                <?php 		        
			                $bicms	= $valor_unitario;
			                $vicms	= ($bicms*$listTri->vendaicms)/100;
			                 
			                if($listTri->usectm==true){
				                /*-- Regra valida somente para o estado do  Mato Grosso, para alguns casos especiais ---------*/
				                if(($listTri->vendaicmsdest!=0) and ($listTri->usevendaicmsdest==true)){
					                $vst	= (($ipiprod+$bicms)*$listTri->ctm)/100;
					                $bst	= ($vicms+$vst)/($listTri->vendaicmsdest/100);
				                }else{
					                $bst	= 0;
					                $vst	= 0;
				                }
			                }else{
				                if(($listTri->vendaicmsdest!=0) and ($listTri->usevendaicmsdest==true)){
					                $bst	= $ipiprod+$bicms + ((($ipiprod+$bicms)*$listTri->vendast)/100);
					                $vst	= (($bst*$listTri->vendaicmsdest)/100) - $vicms;
				                }else{
					                $bst	= 0;
					                $vst	= 0;
				                }
			                }
			                
			                if($listTri->usevendaicmsdest==true){
			                	$perc = ($vst*100)/$bicms;
			                	echo number_format($vst,2,',','.')." (".number_format($perc,2,',','.')."%)";
			                }else{
			                	echo number_format(0,2,',','.')." (0,00%)";
			                }
					    
					    ?>
	                	
	               
		                </span></td>
		                <td class="<?=$class?>"  style="text-align: center;" ><span style="color: #999"><?php echo number_format($listTri->vendast,2,',','.')?>%</span></td>
		                <td class="<?=$class?>"  style="text-align: right;"><b>
		                <?php 
		                	$valorprod = 0;
		                	$valorprod = $valor_unitario+$ipiprod+$vst;
		                	echo number_format(($valorprod),3,',','.');
		                	
		                ?></b></td>
		                <td class="<?=$class?>"  style="text-align: right;"><b><?=number_format(($listaProd->qt*$valorprod),3,',','.')?></b></td>	                
		            </tr>
			        <?php

			        $total_prod 			+= $listaProd->qt;
			        $total_pedido 			+= $listaProd->PRECO_UNITARIO*$listaProd->qt;
			        $total_pedido_liquido 	+= $listaProd->qt*$valor_unitario;
			        if(($listaProd->ipi!=0) and ($listTri->semipi==false)): //--Se IPI nao for zero, e se perfil fiscal obriga ter ipi -----------------
			        	$ipi				+= (($listaProd->qt*$valor_unitario)*$listaProd->ipi)/100;
			        endif;
			        $peso = 0;
			        $peso = str_replace(",", ".", $listaProd->PESO);
			        $pesoliquido += $listaProd->qt*$peso;
		        endforeach;
		        ?>
		        <?php 		        
		        $bicms	= $total_pedido_liquido;
		        $vicms	= ($total_pedido_liquido*$listTri->vendaicms)/100;
		       		        
		        if($listTri->usectm==true):
		        /*-- Regra valida somente para o estado do  Mato Grosso, para alguns casos especiais ---------*/
		        	if(($listTri->vendaicmsdest!=0) and ($listTri->usevendaicmsdest==true)):
				        $vst	= (($ipi+$total_pedido_liquido)*$listTri->ctm)/100; 
				        $bst	= ($vicms+$vst)/($listTri->vendaicmsdest/100);				        	        
				    else:
				    	$bst	= 0;
				        $vst	= 0;
				    endif;		
		        else:
			        if(($listTri->vendaicmsdest!=0) and ($listTri->usevendaicmsdest==true)):
				        $bst	= $ipi+$total_pedido_liquido + ((($ipi+$total_pedido_liquido)*$listTri->vendast)/100);
				        $vst	= (($bst*$listTri->vendaicmsdest)/100) - $vicms;
				    else:
				    	$bst	= 0;
				        $vst	= 0;
				    endif;
				endif;
			    			    
			    $vltotalnota	=	$total_pedido_liquido+$ipi+$vst;
			    
		        ?>
		        
		        <tr>
			    	<td  class="td_total_imp" align="left" colspan="12" >
			            <table style="width: 100%">
			            	<tr>
					            <td   align="left"  valign="middle" style="padding-top: 5px; padding-bottom: 5px" >
					               Base do calculo ICMS:<br />
		                    	   <span style="font-size:14px; font-weight:bold;">
			                    	   	<?php if($listTri->usevendaicms==true): ?>
					                    <?=number_format($total_pedido_liquido,2,',','.')?>
					                    <?php else: ?>
					                    <?=number_format(0,2,',','.')?>
					                    <?php endif;?>
		                    	   </span>
					            </td>
					            <td   align="left"  valign="middle" style="padding-top: 5px; padding-bottom: 5px" >
					               	Base do calculo ICMS S.T.:<br />
		                    	   	<span style="font-size:14px; font-weight:bold;">
		                    	   		<?php if($listTri->usevendaicmsdest==true): ?>
					                    <?=number_format($bst,2,',','.')?>
					                    <?php else: ?>
					                    <?=number_format(0,2,',','.')?>
					                    <?php endif;?>
		                    	   	</span>
					            </td>
					            <td   align="left"  valign="middle" style="padding-top: 5px; padding-bottom: 5px" >
					               Valor total do IPI:<br />
		                    	   <span style="font-size:14px; font-weight:bold;">
		                    	        <?php if($listTri->semipi==false): ?>
					                    <?=number_format($ipi,2,',','.')?>
		                    	   		<?php else: ?>
					                    <?=number_format(0,2,',','.')?>
					                    <?php endif;?>     
		                    	   </span>
					            </td>
					            <td   align="left"  valign="middle" style="padding-top: 5px; padding-bottom: 5px" >
					              Valor Total dos produtos:<br />
		                    	  <span style="font-size:14px; font-weight:bold; "><?=number_format($total_pedido_liquido,2,',','.')?></span>
					            </td>
					    	</tr>
						    <tr >
					    		<td   align="left"  valign="middle" style="padding-top: 5px; padding-bottom: 5px" >
					               Valor ICMS:<br />
		                    	   <span style="font-size:14px; font-weight:bold;">
		                    	   		<?php if($listTri->usevendaicms==true): ?>
					                    <?=number_format($vicms,2,',','.')?>
					                    <?php else: ?>
					                    <?=number_format(0,2,',','.')?>
					                    <?php endif;?>
		                    	   </span>
					            </td>
					            <td   align="left"  valign="middle" style="padding-top: 5px; padding-bottom: 5px" >
					               Valor ICMS S.T.:<br />
		                    	   <span style="font-size:14px; font-weight:bold;">
		                    	   		<?php if($listTri->usevendaicmsdest==true): ?>
					                    <?=number_format($vst,2,',','.')?>
					                    <?php else: ?>
					                    <?=number_format(0,2,',','.')?>
					                    <?php endif;?>
		                    	   </span>
					            </td>
					            <td   align="left"  valign="middle" style="padding-top: 5px; padding-bottom: 5px" >
					               Outras despesas:<br />
		                    	   <span style="font-size:14px; font-weight:bold;"><?=number_format("0",2,',','.')?></span>
					            </td>
					            <td   align="left"  valign="middle" style="padding-top: 5px; padding-bottom: 5px" >
					              Valor Total da nota:<br />
		                    	  <span style="font-size:14px; font-weight:bold; ">
		                    	  <?
		                    	  if(!empty($listPed->frete)) $vltotalnota += $listPed->frete;
		                    	  if(!empty($listPed->seguro)) $vltotalnota += $listPed->seguro;
		                    	  if(!empty($listPed->desconto)) $vltotalnota -= $listPed->desconto;
		                    	  
		                    	  echo number_format($vltotalnota,2,',','.')?>
		                    	  </span><br /><br />
		                    	  <span >Total de pe&ccedil;as:</span><br />
				                  <span style="font-size:14px; font-weight:bold; text-align:right;" ><?=$total_prod?></span><br />				                    
					            </td>					            
				            </tr>
			       		</table>  
		            </td>		            		            
			    </tr>
		        <tr>
		            <td  class="td_total" align="left" colspan="9" >
		               <i>* Produtos pendentes de compras anteriores</i>
		            </td>
		                      
		        </tr>
			   
			</table>
		</div>
	</div>
</div> 
 
 </body>
 </html>