<!-- Calendarios -->
<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/javascript/calendario/dhtmlgoodies_calendar.css?random=20051112" media="screen"></LINK>
<SCRIPT type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/javascript/calendario/dhtmlgoodies_calendar.js?random=20060118"></script>
  

<table width="100%" style="margin-bottom: 10px"  >
	<tr>
		<td align="left">
			<a href="<?php echo $this->baseUrl(); ?>/admin/painel">HOME</a>&nbsp; 
			<img src="<?php echo $this->baseUrl(); ?>/images/seta.png" width="5" height="7" />&nbsp;
			<a href="<?php echo $this->baseUrl(); ?>/admin/venda/pedidos"><b>PEDIDOS</b></a> 
			
		</td>
	</tr>
</table>
           
<table width="100%" class="borda_titulo">
	<tr>
		<td width="left">VENDAS</td>
	</tr>
</table>

<table width="100%" style="margin: 8px 0px" >
    <tr>
    	<td align="left">
    	<input type="button" class="button" value="Busca" onclick='javascript:mostrarPesquisa();'></input>
    	</td>
	</tr>
</table>  
 
<script>
function mostrarPesquisa(){
    nTr = document.getElementById("tabela");
    if(nTr.style.display == "none"){
        nTr.style.display = "block"
    }else{
        nTr.style.display = "none";
    }
}

function tipoPesquisa(valor){

	if(valor==1){
		document.getElementById("buscid").style.display = "block";
		document.getElementById("data").style.display = "none";
		document.getElementById("busccliente").style.display = "none";
		document.getElementById("dataini").value = "";
		document.getElementById("datafin").value = "";
		document.getElementById("buscacli").value = "";
	}else if(valor==2){
		document.getElementById("data").style.display = "block";
		document.getElementById("buscid").style.display = "none";
		document.getElementById("busccliente").style.display = "none";
		document.getElementById("buscaid").value = "";
		document.getElementById("buscacli").value = "";
	}else if(valor==3){
		document.getElementById("busccliente").style.display = "block";
		document.getElementById("buscid").style.display = "none";
		document.getElementById("data").style.display = "none";
		document.getElementById("buscaid").value = "";
	}
    
}
</script>
<table width="100%"> 
	<tr>
		<td align="left">
<form action="pedidoscli" method="post" name="busca" id="busca">
<table align="left" width="70%" style=" display: none; border: 1px solid #000; padding: 10px; " id="tabela">
    <tr>
    	<td align="left" >
	    	<select name="tipo" onchange="tipoPesquisa(this.value);" style="border: 1px solid #999">
			<option value="2">Por per&iacute;odo</option>
			</select>
			 &nbsp;  &nbsp;    
    	</td>
    	
    	<td align="left">
	    	<div style="display: none;" id="buscid">
				<input type="text" size="10" name="buscaid" id="buscaid">
				<input type="submit" value="Pesquisar">
			</div>
			<div style="display: block" id="data">
				<input type="text" size="10" name="dataini" id="dataini" onclick="displayCalendar(document.busca.dataini,'dd/mm/yyyy',this)">
				&agrave; <input type="text" size="10" name="datafin" id="datafin" onclick="displayCalendar(document.busca.datafin,'dd/mm/yyyy',this)">
				<input type="submit" value="Pesquisar">
			</div>
			
    	</td>
	</tr>
</table>  
</form>
</td></tr>
<tr><td>
        
           <?php 
			
        	
			if ( count($this->objList) > 0) :
			
			?>
			<table align="left" class="mytable" width="100%" cellspacing="0">
		        <tr>
		            <th  class="th_canto_orc" align="center" width="10%">
		                ID
		            </th>
		            <th  class="th_orc" align="center" width="12%" >
		                DATA VENDA 
		            </th>
		            <th  class="th_orc" align="center" width="30%">
		            	EMPRESA 
		            </th>
		            <th  class="th_orc" align="center" width="30%">
		            	SITUAÇÃO 
		            </th>
		            <th  class="th_orc" align="center" width="18%">
		                OP&Ccedil;&Otilde;ES
		            </th>
		       </tr>	
			
			<?php 
			$cor=0;
	    	foreach($this->objList as $lista):
	    	$cor++;
            if(($cor%2)==0) $class = 'td_orc_par';
            else $class = 'td_orc';
			?>
			
			<tr >
                <td  class="<?=$class?>" align="center" >
                   <?php echo $lista->id?>
                </td>
                <td  class="<?=$class?>" align="center" >
                	<?php echo $lista->dtvenda?>
                </td>
                <td  class="<?=$class?>" align="left" >
                	<?php echo utf8_encode($lista->EMPRESA)?>
                </td>
                <td  class="<?=$class?>" align="center" > 
                   <?php if($lista->status=="ped") echo "FINALIZADO"; 
                   else echo "EM ABERTO";?>                  
                </td>
                <td  class="<?=$class?>" align="center" >
                	<a href="http://www.ztlbrasil.com.br/public/legado/acessoRestrito/pedidos_fix.php?ped=<?=$lista->id?>" ><img src="<?php echo $this->baseUrl(); ?>/images/visualizar_orc.gif" width="17" height="17" border="0" title="Visualizar"></a>&nbsp;&nbsp;
                    <a target="_blank" href="http://www.ztlbrasil.com.br/public/legado/acessoRestrito/pedidos_vis.php?ped=<?=$lista->id?>"><img src="<?php echo $this->baseUrl(); ?>/images/imprimir_orc.gif" width="19" height="19" border="0" title="Imprimir"></a>
                </td>
                
            </tr>
            
			<?php  endforeach;
			?>        </table>
			<table width="100%">
			<tr><td align="center">
				&nbsp;
            </td></tr>
			<tr><td align="center">
				<?php 
		            if ( count($this->objList) > 0) :
		            	echo $this->objList;
		            endif;
            	?>
            </td></tr>
            
         </table>
         </td></tr>
         </table>
			 <?php 
			else :
			?>
			<br>
			<center>Nenhuma Venda cadastrada</center>
			
			<?php 
			endif;
		?>
	