<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>ZTL Brasil - www.ztlbrasil.com.br </title>
	<link href="<?=$this->baseUrl()?>/public/sistema/imagens/ztl.ico" rel="shortcut icon" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="description" content="<?=$this->translate->_("ZTL do Brasil importação, exportação e comercio")?>" />
	<meta name="keywords" content="rolamentos, cubo de roda, rolamento, embreagem, embreagens, ponta de eixo, pontas de eixo, bomba dagua, bombas dagua, roda, scania, homocinetica, homocineticas, transmissoes" />
	
	<link href="<?=$this->baseUrl()?>/public/css/estiloimpressao.css" rel="stylesheet" type="text/css" />
</head>

<?php 
	foreach ($this->objCli as $listCli);
	foreach ($this->objEnd as $listEnd);
	foreach ($this->objDes as $listDes);
	foreach ($this->objPed as $listPed);
?>
<body onload="window.print()">
<div style="width: 800px; margin: 0 auto;">
	<div id="sistopo">VENDA Nº <?=$listPed->id?>
		<div style="float: right;"><?=substr($listPed->data_vend,8,2)."/".substr($listPed->data_vend,5,2)."/".substr($listPed->data_vend,0,4)." ".substr($listPed->data_vend,9)?></div>
	</div>
	<div id="sistitulo">INFORMAÇÕES DO CLIENTE</div>
    <div id="sisconteudo">
		<div> 
		<table width="100%" style="border: 1px solid;"  cellspacing="7">
            <tr>
                <td width="20%">Cliente:</td>
                <td colspan="3"><b><?=$listCli->EMPRESA?></b></td>
            </tr>
            <tr>
                <td>Raz&atilde;o Social:</td>
                <td colspan="3"><b><?=$listCli->RAZAO_SOCIAL?></b></td>
            </tr>
            <tr>
                <td>CPF/CNPJ:</td>
                <td width="35%"><b><?=$listCli->CPF_CNPJ?></b></td>
                <td width="15%">RG/INSC:</td>
                <td ><b><?=$listCli->RG_INSC?></b></td>
            </tr>
            
        </table>
        </div>
        <div>
     		
		    <table align="center" class="mytable" width="100%" cellspacing="0">
		        <tr>
		        	<th  class="th_orc" align="center" width="4%">
		                ID
		            </th>
		            <th  class="th_orc" align="center" width="15%">
		                Codigo
		            </th>
		            <th  class="th_orc" align="center" width="5%">
		                QT
		            </th>
		            <th  class="th_orc" align="center" width="">
		                Descri&ccedil;&atilde;o
		            </th>
		             <th  class="th_orc" align="center" width="5%">
		                Pre&ccedil;o Tabela
		            </th>
		            <th  class="th_orc" align="center" width="5%">
		                Pre&ccedil;o NF
		            </th>
		            <th  class="th_orc" align="center" width="10%">
		                Pre&ccedil;o Total
		            </th>
		        </tr>
		        <?php 
		        $cor=0;
		        $total_pedido = 0;
		        $total_pedido_liquido = 0;
		        $v_estoque = 0;
		        foreach ($this->objList as $listaProd):
		        	$cor++;
		            if(($cor%2)==0) $class = 'td_orc_par';
		            else $class = 'td_orc';
			        ?>
			        <tr >
			        	<td  class="<?=$class?>" align="center" >
		                    <?=$cor?>
		                </td>
		                <td  class="<?=$class?>" align="center" >
		                    <?=$listaProd->CODIGO?>
		                </td>
		                <td  class="<?=$class?>" align="center" >
		                	<?=$listaProd->qt?>		                    
		                </td>
		                <td  class="<?=$class?>" " align="left">
		                   <?=($listaProd->DESCRICAO)?> 
		                </td>
		                <td  class="<?=$class?>" " align="center">
		                    <?=number_format($listaProd->preco_tabela,3,',','.')?>
		                </td>
		                <td  class="<?=$class?>" " align="right">
			                <?=number_format($listaProd->preco_unit,3,',','.')?>
		                </td>
		                <td  class="<?=$class?>" " align="right">
		                    <?=number_format(($listaProd->qt*$listaProd->preco_unit),3,',','.')?>
		                </td>
		            </tr>
			        <?php

			        $total_prod += $listaProd->qt;
			        $total_pedido += $listaProd->preco_tabela*$listaProd->qt;
			        $total_pedido_liquido += $listaProd->qt*$listaProd->preco_unit;
		        endforeach;
		        ?>
		         
		        <tr>
			    	<td  class="td_total" align="left" colspan="4" valign="top">
			            <table>
				            <tr>
					            <td   align="left"  valign="top" style="padding-top: 5px; padding-bottom: 5px" >
					               Prazo: <? 
					               	if(($listDes->prazo1 != '') and ($listDes->prazo1 != "0")) echo $listDes->prazo1;
					               	if(($listDes->prazo2 != '') and ($listDes->prazo2 != "0")) echo "/".$listDes->prazo2; 
					               	if(($listDes->prazo3 != '') and ($listDes->prazo3 != "0")) echo "/".$listDes->prazo3;
								   	if(($listDes->prazo4 != '') and ($listDes->prazo4 != "0")) echo "/".$listDes->prazo4;
								   	if(($listDes->prazo5 != '') and ($listDes->prazo5 != "0"))echo "/".$listDes->prazo5;?>
					            </td>
					    	</tr>
						    <tr >
					    		<td  align="left" valign="top"  >
					                Observa&ccedil;&otilde;es:<br>
					                <b><?=$listPed->obs?></b>
					            </td>
				            </tr>
			       		</table>  
			            </td>
			            <td class="td_total2"  align="left" colspan="3" >
			            	<table width="100%" border="0"><tr><td align="left">
			                    <span >Total de pe&ccedil;as:</span><br />
			                    <span style="font-size:14px; font-weight:bold; text-align:right;" ><?=$total_prod?></span><br />
			                    </td></tr><tr><td>
			                    Valor Total bruto:<br />
			                    <span style="font-size:14px; font-weight:bold;">R$ <?=number_format($total_pedido,3,',','.')?></span><br />
			                    </td></tr><tr><td>
			                    Valor Total l&iacute;quido:<br />
			                    <span style="font-size:14px; font-weight:bold; ">R$ <?=number_format($total_pedido_liquido,3,',','.')?></span><br />
			                    </td></tr>
			                </table>
			            </td>
			            
			        </tr>	
			    </table>
		</div>
	</div>
</div>			  
 </body>
 </html>