<script src="<?=$this->baseUrl()?>/public/sistema/js/buscaajax/vendaPedidos.js"></script>

<!-- Content -->
    <div class="content">   
    
    	<!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a> </li>
                	<li class="lastB">Pedidos</li>         
                </ul>
            </div>
        </div>       
        
        <div class="title"><h5>Pedidos</h5>
        	<div style="float: right; padding: 10px">
				<a href="<?php echo $this->baseUrl(); ?>/admin/venda/pedidosexp" ><img title="Exportar para MS Excel" src="<?=$this->baseUrl(); ?>/public/sistema/imagens/icons/middlenav/excelDocwhite.png" border="0" width="18" /> </a>
			</div>
        </div>
        
        <div class="widgets" >
        	<!-- Busca -->
        	<div class="left" style="margin-top: 5px; margin-bottom: 5px" >   
	        	<?php 
				if($this->objIns==true):
					?>
				    <input type="button" class="basicBtn" style="width: 110px" onclick="window.location='<?=$this->baseUrl()?>/admin/venda/pedidosbuscacli'" value="Novo Pedido" >
		    		<?php		    	
			    endif; ?>         
                                
            </div>
            <div class="right" style="text-align: right; padding-top: 7px; width: 40%">
	        	<a href="<?php echo $this->baseUrl(); ?>/admin/venda/pedorcamentos">Orçamentos</a>
		    	<?php 
		    	if($this->objVisrel==1):
		    	?>
		    	| <a href="<?php echo $this->baseUrl(); ?>/admin/relatorios/faturamento" target="_blank">Relatórios</a>
		    	<?php endif; ?>
	        </div>
	        
        </div>
        	
 		<!-- Busca ------------------------------------------------------ -->
		<div class="widgets" >
			<div class="first" style="margin-top: 5px; margin-bottom: 5px; border: 1px solid #d5d5d5; padding: 10px" >  
				<form method="post" name="busca" id="busca" class="mainForm">
					<div >
						<table style="width: 100%">
							<tr>
						    	<td class="tdbusca">
					    			<input type="text" name="id" title="Nº do Pedido" placeholder="Nº do pedido" style="width: 100px"/>					    			
					    		</td>
					    		<td class="tdbusca">
					    			<input type="text" name="nfe" placeholder="NF-e" style="width: 100px"/>
					    		</td>
							 	<td style="vertical-align: bottom;" class="tdbusca" >
							 		<div class="styled-select" style="width: 120px">
										<select name="buscasit" id="buscasit" style="width: 140px">
											<option value="sit">Situação</option>
											<option value="1">Pedido</option>
											<option value="2">Faturado</option>
											<option value="3">Cancelado</option>
										</select>
									</div>
								</td>
							</tr>
							<?php if($this->objNivel==2 || $this->objNivel==1){ ?>
						    <tr>
						    	<td align="left" valign="top" class="tdbusca" colspan="3">
					    			<div class="styled-select" style="width: 250px">
						    			<select name="cliente" style="width: 272px">
							    			<option value="0">Clientes</option>
							    			<?php foreach ($this->objCli as $cli){ ?>
							    				<option value="<?php echo $cli->ID?>"><?php echo (substr($cli->EMPRESA,0,50))?></option>
							    			<?php } ?>    				
						    			</select>
					    			</div>
								</td>
							 </tr>
							 <?php }
							 
							 if($this->objNivel==2){
							 ?>
							 <tr>
							 	<td style="vertical-align: bottom;" class="tdbusca">
							 		<div class="styled-select" style="width: 290px">
						    			<select name="representante" style="width: 312px">
						    			<option value="0">Regiões</option>
						    			<?php 
						    			foreach ($this->objReg as $func){ 
						    				if($func->id_clientes != ""){
						    				?>
						    				<option value="<?=$func->id_clientes?>"><?=$func->NOME." - ".$func->EMPRESA?></option>
						    				<?php 
						    				}
						    			}
						    			?>    				
						    			</select>
						    		</div>
								</td>
								<td style="vertical-align: bottom;" class="tdbusca" colspan="2">
							 		<div class="styled-select" style="width: 290px">
						    			<select name="televenda" style="width: 312px">
							    			<option value="0">Teleregiões</option>
							    			<?php foreach ($this->objTel as $tel){ 
							    			    if($tel->iduser != ""){
							    			    ?>
							    				<option value="<?php echo $tel->iduser?>"><?php echo $tel->regiao." - ".$tel->usuario?></option>
							    				<?php 
												}
											} ?>    				
						    			</select>
					    			</div>
								</td>
							</tr>
							<?php } ?>
							<tr>								
				    			<td style="vertical-align: bottom; width: 80%" class="tdbusca" colspan="2">
				    				<div style="float: left; width: 40%">
					    				<input type="radio" name="tpdata" value="1" checked="checked"><label>Dt pedido</label>
						    			<input type="radio" name="tpdata" value="2"><label>Dt venda</label>		
									</div>
									<div style="float: left; width: 15%"> 
										<input placeholder="Data inicio" type="text" style="margin-right: 3px; width: 80px" name="dataini" id="dataini" class="data datepicker">
									</div>
									<div style="float: left;">
										<input placeholder="Data fim" type="text" style="margin-right: 3px; width: 80px" name="datafim" id="datafim" class="data datepicker">
									</div>
								</td>
								<td class="tdbusca">
									<input type="button" class="blueBtn btnpesq" value="Pesquisar" id="btnbusca">
								</td>
							</tr>								
						</table>
					</div>
				</form>
			</div>
		</div>
		
		<div class="clear"></div>
		
		<div style="display: none; " id="resultado">
			<div style="padding: 10px; border: 1px solid #d5d5d5;">
				<img src="<?php echo $this->baseUrl?>/public/sistema/imagens/loaders/loader6.gif"> <i>Aguarde...</i>
			</div>
		</div>	
 		
	</div>
	