<script type="text/javascript" src="<?=$this->baseUrl()?>/public/javascript/buscaajax/buscaajaxsubgrupo.js"></script>

<!-- Content -->
    <div class="content">   
    
<!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="<?php echo $this->baseUrl(); ?>/admin">Home</a> </li>
                	<li ><a href="<?=$this->baseUrl(); ?>/admin/venda/pendenciasprod/fil/comp">Pendências</a></li>         
                	<li class="lastB"><?=$this->codigo?></li>
                </ul>
            </div>
        </div>  
        
        <div class="title"><h5>Pedidos</h5></div>
        
        <div class="widgets" >
        
		<!-- Static table -->
        <?php
		if (count($this->objList) > 0):			
		?>       
        <div class="widget first">
 			<table style="width: 100%" class="tableStatic">
            	<thead>
                	<tr>
                        <td width="10%">ID</td>
                        <td width="30%">Empresa</td>
                        <td width="">CNPJ</td>
                        <td width="15%">Pedido</td>
                        <td width="15%">Dt pend</td>
                        <td width="10%">Qt</td>
                        <td width="10%">Opções</td>
                    </tr>
                </thead>
                <tbody>
         			<?php 
					$cor=0;
			    	foreach($this->objList as $lista):
			    	?>
					
					<tr >
						<td align="left" >
		                   	<?=$lista->id_cliente?></a>  
		                </td>
		                <td align="left" >
		                   	<a href="<?=$this->baseUrl();?>/admin/cadastro/parceirosvisualizar/idparceiro/<?=md5($lista->id_cliente)?>" target="_blank">
						 	<?=$lista->EMPRESA?></a>  
		                </td>
		                <td class="<?=$class?>" align="left" >
		                	<?=$lista->CPF_CNPJ?>
		                </td>
		                <td class="<?=$class?>" align="center" >
		                	<?=$lista->id_ped?>
		                </td>                
		                <td align="center" >
		                	<?=$lista->dtpend?>
		                </td>
		                <td align="center" >
		                	<?=$lista->qtprod?>               	
		                </td>
		                <td align="center" >
		                	<a href="<?=$this->baseUrl()?>/admin/venda/pendenciasemp/empresa/<?=md5($lista->id_cliente)?>" ><img src="<?=$this->baseUrl()?>/public/sistema/imagens/icons/middlenav/magnify.png" width="16" border="0" title="Visualizar"></a>
		                </td>                
		            </tr>            
					<?php  endforeach; ?>
				</tbody>
			</table>
		</div>					
		
		<?php 
		else :
		?>
		<div class="first">
 			Nenhuma pendência encontrada
		</div>	
		<?php 
		endif;
		?>
	</div>
</div>