<script src="<?=$this->baseUrl()?>/public/javascript/buscaajax/buscaajaxgrupofor.js" type="text/javascript"></script>
<script src="<?=$this->baseUrl()?>/public/javascript/buscaajax/buscaajaxsubgrupo.js" type="text/javascript"></script> 

	<div class="content">
	<!-- Navegacao --> 
    	<div class="breadCrumbHolder module" style="margin-top: 0px; margin-bottom: 10px">
        	<div class="breadCrumb module">
            	<ul>
                	<li class="firstB"><a href="#">Home</a> </li>
                	<li><a href="<?php echo $this->baseUrl()?>/admin/venda/pedidos">Pedidos</a></li>
                	<li class="lastB">Curva de produtos</li>         
                </ul>
            </div>
        </div>       
        
        <div class="title"><h5>Curva de produtos</h5></div>

        <div class="widget" style="border-top: 1px solid #d5d5d5; padding: 10px">
	    	<form action="<?php echo $this->baseUrl(); ?>/admin/venda/relatoriovendascurva" method="post" name="busca" id="busca" class="mainForm">
			<table style="width: 100%" id="tabela" >
		    <tr>
		    	<td align="left" colspan="4"  width="400">
			    	Fornecedor:<br>
			    	<div class="styled-select" style="width: 250px">
					<select name="buscafor" id="buscafor" style="width: 272px" onchange="Buscagruposfornecedor(this.value);">
						<option value="0"><?=$this->translate->_("Todos")?></option>
						<?php foreach ($this->objFor as $listfor): ?>
							<option <?php if($this->objFsel==$listfor->ID) echo 'selected="selected"'?>  value="<?=$listfor->ID?>"><?=$listfor->EMPRESA?></option>
						<?php endforeach; ?>
					</select>	
					</div>							
		    	</td>
			</tr>
			<tr>
		    	<td align="left" width="200">
					Grupos de Venda:<br>
					<div class="styled-select" style="width: 190px">
					<select name="grupovenda" id="grupovenda" onchange="Mostrasubgrupos(this.value,3);" style="width: 212px; text-transform: uppercase;">
						<option value="0">SELECIONE</option>
						<?php foreach ($this->objGrupov as $listG): ?>
						<option value="<?php echo $listG->id?>"><?php echo $listG->descricao?></option>
						<?php endforeach;?>					
					</select>	
					</div>								
				</td>
				<td align="left" colspan="3">
				<div id="subgrupo" align="left">
				</div>
				</td>	
			</tr>		
			<tr>
		    	<td align="left"  >
		    		Grupos de Compra<br>
		    		<div class="styled-select" style="width: 190px">
					<select name="buscagrupo" id="buscagrupo" style="width: 212px; text-transform: uppercase;">
						<option value="0"><?=$this->translate->_("SELECIONE")?></option>
						<?php foreach ($this->objGrupo as $list): ?>
							<option value="<?php echo $list->id?>" 
							<?php if($this->objGselec==$list->id) echo 'selected="selected"';?>  ><?php echo substr($list->purchasing,0,20)?></option>
						<?php endforeach; ?>
					</select>
					</div>
				</td>
				<td align="left" >&nbsp;
				</td>
		    	<td align="left" >
		    		Período<br>
		    		<div class="styled-select" style="width: 110px">
		    		<select name="periodo" id="periodo" style="width: 132px">
		    			<?php 
		    			if((empty($this->objQtmes))|| ($this->objQtmes==6)) $sel6 = 'selected="selected"';
		    			elseif($this->objQtmes==1) $sel1 = 'selected="selected"';
		    			elseif($this->objQtmes==2) $sel2 = 'selected="selected"';
		    			elseif($this->objQtmes==3) $sel3 = 'selected="selected"';
		    			elseif($this->objQtmes==4) $sel4 = 'selected="selected"';
		    			?>
		    		
						<option value="1" <?=$sel1?>>1 Mês</option>
						<option value="2" <?=$sel2?>>2 Meses</option>
						<option value="3" <?=$sel3?>>3 Meses</option>
						<option value="4" <?=$sel4?>>4 Meses</option>
						<option value="6" <?=$sel6?>>6 Meses</option>
					</select>
					</div>										
		    	</td>		
		    	<td style="vertical-align: bottom;">
		    	<input type="submit"  value="<?=$this->translate->_("Pesquisar")?>" class="basicBtn" >
		    	</td>    	   	
			</tr>		    		
			</table>
		</form>
	</div>
		
	<?php
	if (count($this->objList) > 0):			
	?>       
        <!-- Static table -->
        <div class="widget first"> 		
        	<table style="width: 100%" class="tableStatic">
            	<thead>
                	<tr>
                        <td width="15%">Codigo</td>
                        <?php 
		            for($i=$this->objQtmes;$i>0;$i--):
		            ?>
		            <td style="text-align: center;">
		                <?=date('m/Y', mktime(0, 0, 0, date("m") - $i, 1, date("Y")));?>
		            </td>
		            <?php endfor; ?>
			            <td width="10%">
			                Total
			            </td>
                    </tr>
                </thead>
                <tbody>				       
				<?php 
				
				$cor=0;
				$idprod = "";
		    	foreach($this->objProd as $lista):		    		
			    	$cor++;
		            ?>
					<tr >
		                <td style="text-align: center;" >
		                   <a href="<?=$this->baseUrl();?>/admin/cadastro/produtoscad/produto/<?=md5($lista->idproduto)?>" target="_blank">
							<?=$lista->CODIGO?>
							</a>
		                </td>
			            <?php
			            $totalqtprod = 0;
			            for($i=$this->objQtmes;$i>0;$i--):
			            ?>
			            <td  style="text-align: center;">
		                   	<?php
		                   	$qtvenda = $qtped = 0;
							foreach ($this->objList as $vendas):
		                   	   	$mes = date('m', mktime(0, 0, 0, date("m") - $i, 1, date("Y")));
		                   	   	if($lista->ID == $vendas->idproduto):
									if($mes==$vendas->mes):
								   		$qtped 		= $vendas->qtvenda;
								   		$qtvenda 	= $vendas->qtv;
								   	endif;
							   	endif;
							endforeach;			
		
							if(empty($qtped)) $qtped = 0;
							if(empty($qtvenda)) $qtvenda = 0;
							
							echo $qtped."/".$qtvenda;
							$totalqtprod += $qtvenda;
						   	?>		               
		                </td>
			            <?php 
			            endfor; 	            
		            	?>
		            	<td style="text-align: center;">
		                	<?=$lista->qtvenda?>
		                </td>
		            </tr>	            
					<?php  
				endforeach;
				?>
			</tbody>
		</table>
		</div>
		<?php 
		else:
			if(!empty($this->objFsel)):
			?>
			<div class="widget first">
	 			Nenhum Produto Encontrado
			</div>
			<?php 
				endif;
         	endif;
		?>	
</div>
		
	